"""단계별 한→영 말하기 문장 (240문장)
초등 중학년 → 초등 고학년 → 중학교 → 고등학교 → 일상생활 → 외국인 도와주기
각 문장에 핵심 표현 힌트 포함. ID는 스피킹 드릴(1~500)과 겹치지 않도록 1001부터 시작.
"""

LEVEL_SENTENCES = [
    # ═══════════ 초등 중학년 (3~4학년) — 기초 문장 ═══════════
    {"id": 1001, "level": "elem_mid", "korean": "나는 강아지를 좋아해.", "english": "I like dogs.", "hint": "I like + 복수 명사 (일반적인 것을 말할 땐 복수)"},
    {"id": 1002, "level": "elem_mid", "korean": "내 이름은 지민이야.", "english": "My name is Jimin.", "hint": "My name is ~"},
    {"id": 1003, "level": "elem_mid", "korean": "나는 아홉 살이야.", "english": "I'm nine years old.", "hint": "I'm + 숫자 + years old"},
    {"id": 1004, "level": "elem_mid", "korean": "오늘은 날씨가 좋아.", "english": "The weather is nice today.", "hint": "The weather is + 형용사"},
    {"id": 1005, "level": "elem_mid", "korean": "나는 학교에 가.", "english": "I go to school.", "hint": "go to school (the 없이)"},
    {"id": 1006, "level": "elem_mid", "korean": "우리 엄마는 선생님이야.", "english": "My mom is a teacher.", "hint": "직업 앞에는 a를 붙여요"},
    {"id": 1007, "level": "elem_mid", "korean": "나는 파란색을 좋아해.", "english": "I like blue.", "hint": "색깔은 그냥 명사처럼 써요"},
    {"id": 1008, "level": "elem_mid", "korean": "이것은 내 책이야.", "english": "This is my book.", "hint": "This is + 소유격(my/your)"},
    {"id": 1009, "level": "elem_mid", "korean": "나는 배가 고파.", "english": "I'm hungry.", "hint": "I'm + 상태 형용사 (hungry/tired)"},
    {"id": 1010, "level": "elem_mid", "korean": "물 좀 주세요.", "english": "Can I have some water, please?", "hint": "Can I have ~, please? (정중한 요청)"},
    {"id": 1011, "level": "elem_mid", "korean": "나는 형이 한 명 있어.", "english": "I have one brother.", "hint": "I have + 숫자 + 명사"},
    {"id": 1012, "level": "elem_mid", "korean": "우리 집은 커.", "english": "My house is big.", "hint": "My + 명사 + is + 형용사"},
    {"id": 1013, "level": "elem_mid", "korean": "나는 축구를 할 수 있어.", "english": "I can play soccer.", "hint": "can + 동사원형 / play + 운동 이름"},
    {"id": 1014, "level": "elem_mid", "korean": "지금 몇 시야?", "english": "What time is it now?", "hint": "What time is it?"},
    {"id": 1015, "level": "elem_mid", "korean": "나는 사과를 먹고 있어.", "english": "I'm eating an apple.", "hint": "I'm + 동사-ing (지금 하는 중)"},
    {"id": 1016, "level": "elem_mid", "korean": "학교는 재미있어.", "english": "School is fun.", "hint": "fun = 재미있는"},
    {"id": 1017, "level": "elem_mid", "korean": "나는 노래하는 걸 좋아해.", "english": "I like singing.", "hint": "like + 동사-ing (~하는 것을 좋아하다)"},
    {"id": 1018, "level": "elem_mid", "korean": "내 친구는 아주 착해.", "english": "My friend is very kind.", "hint": "very + 형용사 / kind = 착한"},
    {"id": 1019, "level": "elem_mid", "korean": "오늘은 월요일이야.", "english": "It's Monday today.", "hint": "요일/날씨는 It's로 시작"},
    {"id": 1020, "level": "elem_mid", "korean": "나는 우유를 마셔.", "english": "I drink milk.", "hint": "milk는 셀 수 없어서 a를 안 붙여요"},
    {"id": 1021, "level": "elem_mid", "korean": "고양이가 의자 위에 있어.", "english": "The cat is on the chair.", "hint": "on = ~위에"},
    {"id": 1022, "level": "elem_mid", "korean": "나는 숙제를 해야 해.", "english": "I have to do my homework.", "hint": "have to + 동사원형 (~해야 한다)"},
    {"id": 1023, "level": "elem_mid", "korean": "우리 함께 놀자!", "english": "Let's play together!", "hint": "Let's + 동사원형 (~하자)"},
    {"id": 1024, "level": "elem_mid", "korean": "나는 그림 그리는 걸 좋아해.", "english": "I like drawing.", "hint": "drawing = 그림 그리기"},
    {"id": 1025, "level": "elem_mid", "korean": "내 가방은 빨간색이야.", "english": "My bag is red.", "hint": "색깔은 형용사처럼 be동사 뒤에"},
    {"id": 1026, "level": "elem_mid", "korean": "나는 피자를 먹고 싶어.", "english": "I want to eat pizza.", "hint": "want to + 동사원형"},
    {"id": 1027, "level": "elem_mid", "korean": "도와줘서 고마워.", "english": "Thank you for helping me.", "hint": "Thank you for + 동사-ing"},
    {"id": 1028, "level": "elem_mid", "korean": "미안해. 내 잘못이야.", "english": "I'm sorry. It's my fault.", "hint": "It's my fault = 내 잘못이야"},
    {"id": 1029, "level": "elem_mid", "korean": "나는 만화영화를 봐.", "english": "I watch cartoons.", "hint": "watch = (TV·영화를) 보다"},
    {"id": 1030, "level": "elem_mid", "korean": "우리 강아지는 하얀색이야.", "english": "My dog is white.", "hint": "My + 동물 + is + 색깔"},
    {"id": 1031, "level": "elem_mid", "korean": "나는 매일 아침 7시에 일어나.", "english": "I wake up at 7 every morning.", "hint": "at + 시각 / every morning"},
    {"id": 1032, "level": "elem_mid", "korean": "나는 수학을 잘해.", "english": "I'm good at math.", "hint": "be good at + 과목/활동"},
    {"id": 1033, "level": "elem_mid", "korean": "밖에 비가 와.", "english": "It's raining outside.", "hint": "It's raining = 비가 오고 있다"},
    {"id": 1034, "level": "elem_mid", "korean": "나는 책 읽는 걸 좋아해.", "english": "I like reading books.", "hint": "reading books = 책 읽기"},
    {"id": 1035, "level": "elem_mid", "korean": "우리 반에는 학생이 25명이야.", "english": "There are 25 students in my class.", "hint": "There are + 복수 명사 (~가 있다)"},
    {"id": 1036, "level": "elem_mid", "korean": "저 화장실 가도 돼요?", "english": "Can I go to the bathroom?", "hint": "Can I ~? (허락을 구할 때)"},
    {"id": 1037, "level": "elem_mid", "korean": "나는 여동생이 없어.", "english": "I don't have a sister.", "hint": "don't have + 명사 (없다)"},
    {"id": 1038, "level": "elem_mid", "korean": "이거 어떻게 하는 거야?", "english": "How do you do this?", "hint": "How do you ~? (방법을 물을 때)"},
    {"id": 1039, "level": "elem_mid", "korean": "나는 방학이 기다려져.", "english": "I can't wait for vacation.", "hint": "can't wait for + 명사 (몹시 기대되다)"},
    {"id": 1040, "level": "elem_mid", "korean": "잘 자! 내일 봐!", "english": "Good night! See you tomorrow!", "hint": "See you + 시간 표현"},

    # ═══════════ 초등 고학년 (5~6학년) — 과거·미래·비교 ═══════════
    {"id": 1041, "level": "elem_high", "korean": "나는 어제 친구와 놀았어.", "english": "I played with my friend yesterday.", "hint": "과거형은 동사 + -ed (play → played)"},
    {"id": 1042, "level": "elem_high", "korean": "주말에 뭐 했어?", "english": "What did you do on the weekend?", "hint": "did + 동사원형 (과거 질문)"},
    {"id": 1043, "level": "elem_high", "korean": "나는 지난주에 영화를 봤어.", "english": "I watched a movie last week.", "hint": "last week = 지난주에"},
    {"id": 1044, "level": "elem_high", "korean": "내일 비가 올 것 같아.", "english": "I think it will rain tomorrow.", "hint": "I think + will + 동사원형"},
    {"id": 1045, "level": "elem_high", "korean": "나는 커서 의사가 되고 싶어.", "english": "I want to be a doctor when I grow up.", "hint": "when I grow up = 내가 크면"},
    {"id": 1046, "level": "elem_high", "korean": "나는 방과 후에 학원에 가.", "english": "I go to an academy after school.", "hint": "after school = 방과 후에"},
    {"id": 1047, "level": "elem_high", "korean": "우리 가족은 작년에 제주도에 갔어.", "english": "My family went to Jeju Island last year.", "hint": "go의 과거형은 went (불규칙)"},
    {"id": 1048, "level": "elem_high", "korean": "나는 영어를 더 잘하고 싶어.", "english": "I want to get better at English.", "hint": "get better at = ~을 더 잘하게 되다"},
    {"id": 1049, "level": "elem_high", "korean": "그 책은 정말 재미있었어.", "english": "That book was really interesting.", "hint": "was + 형용사 (과거 상태)"},
    {"id": 1050, "level": "elem_high", "korean": "나는 피아노를 3년째 배우고 있어.", "english": "I've been learning piano for three years.", "hint": "for + 기간 (~동안 계속)"},
    {"id": 1051, "level": "elem_high", "korean": "내가 도와줄까?", "english": "Do you want me to help you?", "hint": "Do you want me to + 동사원형?"},
    {"id": 1052, "level": "elem_high", "korean": "너는 어떤 음악을 좋아해?", "english": "What kind of music do you like?", "hint": "What kind of + 명사 = 어떤 종류의"},
    {"id": 1053, "level": "elem_high", "korean": "나는 운동을 자주 하지 않아.", "english": "I don't exercise often.", "hint": "often = 자주 (빈도부사)"},
    {"id": 1054, "level": "elem_high", "korean": "우리 학교는 우리 집에서 가까워.", "english": "My school is close to my house.", "hint": "close to = ~에서 가까운"},
    {"id": 1055, "level": "elem_high", "korean": "나는 시험 때문에 긴장돼.", "english": "I'm nervous about the test.", "hint": "nervous about + 명사"},
    {"id": 1056, "level": "elem_high", "korean": "시간이 정말 빨리 지나가.", "english": "Time goes by so fast.", "hint": "go by = (시간이) 지나가다"},
    {"id": 1057, "level": "elem_high", "korean": "나는 친구들과 자전거 타는 걸 좋아해.", "english": "I like riding bikes with my friends.", "hint": "ride a bike = 자전거를 타다"},
    {"id": 1058, "level": "elem_high", "korean": "우리 이번 주말에 만날까?", "english": "Should we meet this weekend?", "hint": "Should we ~? (~할까? 제안)"},
    {"id": 1059, "level": "elem_high", "korean": "나는 아침을 거의 안 먹어.", "english": "I hardly ever eat breakfast.", "hint": "hardly ever = 거의 ~하지 않다"},
    {"id": 1060, "level": "elem_high", "korean": "그건 좋은 생각인 것 같아.", "english": "I think that's a good idea.", "hint": "I think that's ~ (내 생각엔 ~인 것 같아)"},
    {"id": 1061, "level": "elem_high", "korean": "나는 여름보다 겨울이 더 좋아.", "english": "I like winter better than summer.", "hint": "like A better than B"},
    {"id": 1062, "level": "elem_high", "korean": "우리 형은 나보다 키가 커.", "english": "My brother is taller than me.", "hint": "비교급: 형용사 + -er than"},
    {"id": 1063, "level": "elem_high", "korean": "나는 축구를 잘 못해.", "english": "I'm not good at soccer.", "hint": "not good at = ~을 잘 못하다"},
    {"id": 1064, "level": "elem_high", "korean": "숙제 다 했어?", "english": "Did you finish your homework?", "hint": "Did you finish ~?"},
    {"id": 1065, "level": "elem_high", "korean": "나는 강아지를 키우고 싶어.", "english": "I want to have a dog.", "hint": "have a dog = 강아지를 키우다"},
    {"id": 1066, "level": "elem_high", "korean": "오늘 기분이 안 좋아.", "english": "I'm not in a good mood today.", "hint": "in a good mood = 기분이 좋은"},
    {"id": 1067, "level": "elem_high", "korean": "우리 반에서 내가 제일 빨라.", "english": "I'm the fastest in my class.", "hint": "최상급: the + 형용사-est"},
    {"id": 1068, "level": "elem_high", "korean": "나는 여행 가는 걸 정말 좋아해.", "english": "I really love traveling.", "hint": "love + 동사-ing"},
    {"id": 1069, "level": "elem_high", "korean": "그 영화 본 적 있어?", "english": "Have you ever seen that movie?", "hint": "Have you ever + 과거분사? (경험)"},
    {"id": 1070, "level": "elem_high", "korean": "나 늦을 것 같아.", "english": "I think I'm going to be late.", "hint": "be going to + 동사원형 (~할 것 같다)"},
    {"id": 1071, "level": "elem_high", "korean": "우리 같이 도서관에 가자.", "english": "Let's go to the library together.", "hint": "Let's go to + 장소"},
    {"id": 1072, "level": "elem_high", "korean": "나는 방을 청소해야 해.", "english": "I have to clean my room.", "hint": "have to + 동사원형"},
    {"id": 1073, "level": "elem_high", "korean": "왜 그렇게 생각해?", "english": "Why do you think so?", "hint": "Why do you ~? (이유를 물을 때)"},
    {"id": 1074, "level": "elem_high", "korean": "나는 이 문제를 못 풀겠어.", "english": "I can't solve this problem.", "hint": "solve a problem = 문제를 풀다"},
    {"id": 1075, "level": "elem_high", "korean": "다시 한번 말해줄래?", "english": "Can you say that again?", "hint": "say that again = 다시 말하다"},
    {"id": 1076, "level": "elem_high", "korean": "나는 학교 축제가 기대돼.", "english": "I'm looking forward to the school festival.", "hint": "look forward to + 명사 (기대하다)"},
    {"id": 1077, "level": "elem_high", "korean": "우리 엄마가 나를 데리러 오실 거야.", "english": "My mom will pick me up.", "hint": "pick up = 데리러 오다"},
    {"id": 1078, "level": "elem_high", "korean": "나는 어제 일찍 잤어.", "english": "I went to bed early yesterday.", "hint": "go to bed = 자러 가다"},
    {"id": 1079, "level": "elem_high", "korean": "이 단어 뜻이 뭐야?", "english": "What does this word mean?", "hint": "What does ~ mean? (뜻을 물을 때)"},
    {"id": 1080, "level": "elem_high", "korean": "나는 최선을 다할 거야.", "english": "I'll do my best.", "hint": "do my best = 최선을 다하다"},

    # ═══════════ 중학교 — 접속사·완료시제·의견 ═══════════
    {"id": 1081, "level": "middle", "korean": "나는 시간이 없어서 아침을 못 먹었어.", "english": "I couldn't eat breakfast because I didn't have time.", "hint": "because + 주어 + 동사 (이유)"},
    {"id": 1082, "level": "middle", "korean": "비록 피곤했지만 나는 계속 공부했어.", "english": "Even though I was tired, I kept studying.", "hint": "Even though ~ (비록 ~이지만) / keep + -ing"},
    {"id": 1083, "level": "middle", "korean": "나는 3년째 이 동네에 살고 있어.", "english": "I've been living in this neighborhood for three years.", "hint": "현재완료진행: have been + -ing"},
    {"id": 1084, "level": "middle", "korean": "내 생각에는 그게 더 나은 것 같아.", "english": "In my opinion, that would be better.", "hint": "In my opinion, ~ (내 생각에는)"},
    {"id": 1085, "level": "middle", "korean": "만약 내일 비가 오면 집에 있을 거야.", "english": "If it rains tomorrow, I'll stay home.", "hint": "If + 현재시제, will + 동사원형"},
    {"id": 1086, "level": "middle", "korean": "나는 그를 한 번도 만난 적이 없어.", "english": "I've never met him before.", "hint": "have never + 과거분사 (경험 없음)"},
    {"id": 1087, "level": "middle", "korean": "그 일은 생각보다 어려웠어.", "english": "It was harder than I expected.", "hint": "than I expected = 예상했던 것보다"},
    {"id": 1088, "level": "middle", "korean": "나는 매일 30분씩 운동하려고 노력해.", "english": "I try to exercise for 30 minutes every day.", "hint": "try to + 동사원형 (~하려고 노력하다)"},
    {"id": 1089, "level": "middle", "korean": "사람들은 보통 주말에 늦잠을 자.", "english": "People usually sleep in on weekends.", "hint": "sleep in = 늦잠 자다"},
    {"id": 1090, "level": "middle", "korean": "나는 그 결정에 동의하지 않아.", "english": "I don't agree with that decision.", "hint": "agree with + 사람/의견"},
    {"id": 1091, "level": "middle", "korean": "이 문제를 해결할 방법이 있을까?", "english": "Is there a way to solve this problem?", "hint": "a way to + 동사원형 (~할 방법)"},
    {"id": 1092, "level": "middle", "korean": "나는 실수로 그의 컵을 깨뜨렸어.", "english": "I accidentally broke his cup.", "hint": "accidentally = 실수로"},
    {"id": 1093, "level": "middle", "korean": "그녀가 왜 화났는지 모르겠어.", "english": "I don't know why she's upset.", "hint": "간접의문문: why + 주어 + 동사 (어순 주의)"},
    {"id": 1094, "level": "middle", "korean": "나는 어릴 때 매일 피아노를 쳤어.", "english": "I used to play the piano every day when I was young.", "hint": "used to + 동사원형 (예전엔 ~하곤 했다)"},
    {"id": 1095, "level": "middle", "korean": "시간이 더 있으면 좋을 텐데.", "english": "I wish I had more time.", "hint": "I wish + 과거시제 (~하면 좋을 텐데)"},
    {"id": 1096, "level": "middle", "korean": "그 소식을 듣고 정말 놀랐어.", "english": "I was really surprised to hear the news.", "hint": "surprised to + 동사원형"},
    {"id": 1097, "level": "middle", "korean": "나는 사람들 앞에서 말할 때 떨려.", "english": "I get nervous when I speak in front of people.", "hint": "in front of = ~앞에서"},
    {"id": 1098, "level": "middle", "korean": "우리는 서로 도와야 한다고 생각해.", "english": "I think we should help each other.", "hint": "each other = 서로"},
    {"id": 1099, "level": "middle", "korean": "그 식당은 항상 사람이 많아.", "english": "That restaurant is always crowded.", "hint": "crowded = 붐비는"},
    {"id": 1100, "level": "middle", "korean": "나는 결국 그 일을 포기했어.", "english": "I ended up giving up on it.", "hint": "end up + -ing (결국 ~하게 되다)"},
    {"id": 1101, "level": "middle", "korean": "일이 계획대로 되지 않았어.", "english": "Things didn't go as planned.", "hint": "as planned = 계획대로"},
    {"id": 1102, "level": "middle", "korean": "이건 내가 지금까지 본 것 중 최고야.", "english": "This is the best thing I've ever seen.", "hint": "the best ~ I've ever + 과거분사"},
    {"id": 1103, "level": "middle", "korean": "나는 그가 무슨 말을 하는지 이해 못 했어.", "english": "I didn't understand what he meant.", "hint": "what he meant = 그가 의미한 것"},
    {"id": 1104, "level": "middle", "korean": "우리 팀이 이길 가능성이 높아.", "english": "There's a good chance our team will win.", "hint": "There's a good chance ~ (가능성이 높다)"},
    {"id": 1105, "level": "middle", "korean": "나는 성적을 올리려고 열심히 공부하고 있어.", "english": "I'm studying hard to improve my grades.", "hint": "to + 동사원형 (~하기 위해)"},
    {"id": 1106, "level": "middle", "korean": "그건 사람마다 다른 것 같아.", "english": "I think it depends on the person.", "hint": "depend on = ~에 달려 있다"},
    {"id": 1107, "level": "middle", "korean": "나는 영화를 보다가 잠들었어.", "english": "I fell asleep while watching the movie.", "hint": "while + -ing (~하는 동안)"},
    {"id": 1108, "level": "middle", "korean": "다른 사람의 의견도 존중해야 해.", "english": "We should respect other people's opinions.", "hint": "respect = 존중하다"},
    {"id": 1109, "level": "middle", "korean": "나는 늦게까지 깨어 있는 습관이 있어.", "english": "I have a habit of staying up late.", "hint": "a habit of + -ing / stay up late"},
    {"id": 1110, "level": "middle", "korean": "그 문제를 더 자세히 설명해 줄래?", "english": "Can you explain that in more detail?", "hint": "in more detail = 더 자세히"},
    {"id": 1111, "level": "middle", "korean": "처음에는 어려웠지만 지금은 익숙해졌어.", "english": "It was hard at first, but now I'm used to it.", "hint": "be used to + 명사 (~에 익숙하다)"},
    {"id": 1112, "level": "middle", "korean": "나는 그렇게 생각하지 않아.", "english": "I don't think so.", "hint": "I don't think so = 그렇게 생각 안 해"},
    {"id": 1113, "level": "middle", "korean": "우리는 더 많은 정보가 필요해.", "english": "We need more information.", "hint": "information은 셀 수 없는 명사 (-s 없음)"},
    {"id": 1114, "level": "middle", "korean": "그건 시간 낭비인 것 같아.", "english": "I think it's a waste of time.", "hint": "a waste of time = 시간 낭비"},
    {"id": 1115, "level": "middle", "korean": "나는 그 사실을 최근에서야 알았어.", "english": "I only found out about it recently.", "hint": "find out = 알게 되다"},
    {"id": 1116, "level": "middle", "korean": "계속 노력하면 언젠가 잘하게 될 거야.", "english": "If you keep trying, you'll get better someday.", "hint": "keep + -ing (계속 ~하다)"},
    {"id": 1117, "level": "middle", "korean": "그는 나에게 큰 영향을 주었어.", "english": "He had a big influence on me.", "hint": "influence on = ~에 대한 영향"},
    {"id": 1118, "level": "middle", "korean": "나는 둘 중에 아직 결정하지 못했어.", "english": "I haven't decided between the two yet.", "hint": "haven't + 과거분사 + yet (아직 ~안 했다)"},
    {"id": 1119, "level": "middle", "korean": "그 계획에는 몇 가지 문제가 있어.", "english": "There are a few problems with that plan.", "hint": "problems with = ~에 있는 문제"},
    {"id": 1120, "level": "middle", "korean": "결과와 상관없이 나는 최선을 다했어.", "english": "Regardless of the result, I did my best.", "hint": "regardless of = ~와 상관없이"},

    # ═══════════ 고등학교 — 가정법·관계사·추상 표현 ═══════════
    {"id": 1121, "level": "high", "korean": "내가 너라면 그 제안을 받아들일 거야.", "english": "If I were you, I would accept the offer.", "hint": "가정법: If I were you, I would + 동사원형"},
    {"id": 1122, "level": "high", "korean": "그가 말한 것은 전혀 사실이 아니었어.", "english": "What he said wasn't true at all.", "hint": "What + 주어 + 동사 = ~한 것 / not ~ at all"},
    {"id": 1123, "level": "high", "korean": "기술의 발전은 우리 삶을 크게 바꿔놓았어.", "english": "Advances in technology have greatly changed our lives.", "hint": "advances in = ~의 발전"},
    {"id": 1124, "level": "high", "korean": "나는 그 의견에 어느 정도 동의해.", "english": "I agree with that opinion to some extent.", "hint": "to some extent = 어느 정도는"},
    {"id": 1125, "level": "high", "korean": "더 일찍 시작했어야 했는데.", "english": "I should have started earlier.", "hint": "should have + 과거분사 (~했어야 했는데)"},
    {"id": 1126, "level": "high", "korean": "이 문제에는 여러 요인이 얽혀 있어.", "english": "Several factors are involved in this issue.", "hint": "be involved in = ~에 관련되어 있다"},
    {"id": 1127, "level": "high", "korean": "그 연구 결과는 예상과 정반대였어.", "english": "The results were the opposite of what we expected.", "hint": "the opposite of = ~의 정반대"},
    {"id": 1128, "level": "high", "korean": "나는 환경 보호가 시급하다고 생각해.", "english": "I believe protecting the environment is urgent.", "hint": "동명사 주어: protecting ~ is ..."},
    {"id": 1129, "level": "high", "korean": "그 정책은 장단점이 모두 있어.", "english": "That policy has both advantages and disadvantages.", "hint": "both A and B = A와 B 둘 다"},
    {"id": 1130, "level": "high", "korean": "사람들은 종종 눈에 보이는 것만 믿으려는 경향이 있어.", "english": "People tend to believe only what they can see.", "hint": "tend to + 동사원형 (~하는 경향이 있다)"},
    {"id": 1131, "level": "high", "korean": "성공은 운보다 노력에 달려 있다고 생각해.", "english": "I think success depends more on effort than on luck.", "hint": "depend more on A than on B"},
    {"id": 1132, "level": "high", "korean": "그 사건은 사회에 큰 파장을 일으켰어.", "english": "The incident had a huge impact on society.", "hint": "have an impact on = ~에 영향을 미치다"},
    {"id": 1133, "level": "high", "korean": "나는 다양한 관점을 고려하려고 노력해.", "english": "I try to consider different perspectives.", "hint": "perspective = 관점"},
    {"id": 1134, "level": "high", "korean": "이론적으로는 가능하지만 현실적으로는 어려워.", "english": "It's possible in theory, but difficult in practice.", "hint": "in theory / in practice (이론상 / 실제로는)"},
    {"id": 1135, "level": "high", "korean": "그가 무엇을 원하는지 도무지 모르겠어.", "english": "I have no idea what he wants.", "hint": "have no idea = 전혀 모르겠다"},
    {"id": 1136, "level": "high", "korean": "우리는 장기적인 관점에서 봐야 해.", "english": "We need to look at it from a long-term perspective.", "hint": "from a ~ perspective = ~의 관점에서"},
    {"id": 1137, "level": "high", "korean": "그 주장에는 근거가 부족해.", "english": "That argument lacks evidence.", "hint": "lack + 명사 = ~이 부족하다"},
    {"id": 1138, "level": "high", "korean": "나는 균형 잡힌 삶을 살고 싶어.", "english": "I want to live a balanced life.", "hint": "a balanced life = 균형 잡힌 삶"},
    {"id": 1139, "level": "high", "korean": "아무리 노력해도 그건 불가능해 보여.", "english": "No matter how hard I try, it seems impossible.", "hint": "No matter how + 형용사/부사 (아무리 ~해도)"},
    {"id": 1140, "level": "high", "korean": "그 결정은 신중하게 내려져야 해.", "english": "That decision should be made carefully.", "hint": "수동태: should be + 과거분사"},
    {"id": 1141, "level": "high", "korean": "나는 실패를 통해 많은 것을 배웠어.", "english": "I learned a lot through failure.", "hint": "through = ~을 통해"},
    {"id": 1142, "level": "high", "korean": "그게 바로 내가 말하려던 거야.", "english": "That's exactly what I was trying to say.", "hint": "That's exactly what ~ (그게 바로 ~이다)"},
    {"id": 1143, "level": "high", "korean": "시대가 변함에 따라 가치관도 변해.", "english": "As times change, values change too.", "hint": "As + 주어 + 동사 (~함에 따라)"},
    {"id": 1144, "level": "high", "korean": "나는 그 상황에서 어떻게 해야 할지 몰랐어.", "english": "I didn't know what to do in that situation.", "hint": "what to do = 무엇을 해야 할지"},
    {"id": 1145, "level": "high", "korean": "우리는 서로의 차이를 인정해야 해.", "english": "We need to acknowledge our differences.", "hint": "acknowledge = 인정하다"},
    {"id": 1146, "level": "high", "korean": "그 문제는 생각보다 훨씬 복잡해.", "english": "The issue is far more complicated than it seems.", "hint": "far more + 형용사 + than (훨씬 더 ~한)"},
    {"id": 1147, "level": "high", "korean": "나는 언제나 정직이 최선이라고 믿어.", "english": "I always believe honesty is the best policy.", "hint": "honesty is the best policy = 정직이 최선"},
    {"id": 1148, "level": "high", "korean": "미리 준비했더라면 이런 일은 없었을 거야.", "english": "If I had prepared in advance, this wouldn't have happened.", "hint": "가정법 과거완료: If + had p.p., would have p.p."},
    {"id": 1149, "level": "high", "korean": "그의 설명은 설득력이 있었어.", "english": "His explanation was convincing.", "hint": "convincing = 설득력 있는"},
    {"id": 1150, "level": "high", "korean": "나는 결과보다 과정이 더 중요하다고 생각해.", "english": "I think the process matters more than the result.", "hint": "matter = 중요하다 (동사)"},
    {"id": 1151, "level": "high", "korean": "요즘 사람들은 정보에 쉽게 접근할 수 있어.", "english": "These days, people have easy access to information.", "hint": "access to = ~에 대한 접근"},
    {"id": 1152, "level": "high", "korean": "이제 그 계획을 실행에 옮길 때야.", "english": "It's time to put that plan into action.", "hint": "put ~ into action = 실행에 옮기다"},
    {"id": 1153, "level": "high", "korean": "나는 그 말에 상처받았지만 티 내지 않았어.", "english": "I was hurt by his words, but I didn't show it.", "hint": "be hurt by = ~에 상처받다"},
    {"id": 1154, "level": "high", "korean": "문화적 차이를 이해하는 것이 중요해.", "english": "It's important to understand cultural differences.", "hint": "It's important to + 동사원형"},
    {"id": 1155, "level": "high", "korean": "우리는 실수로부터 배울 수 있어.", "english": "We can learn from our mistakes.", "hint": "learn from = ~로부터 배우다"},
    {"id": 1156, "level": "high", "korean": "그 기회를 놓친 게 후회돼.", "english": "I regret missing that opportunity.", "hint": "regret + -ing (~한 것을 후회하다)"},
    {"id": 1157, "level": "high", "korean": "나는 남의 시선을 신경 쓰지 않으려고 해.", "english": "I try not to care about what others think.", "hint": "try not to + 동사원형 (~하지 않으려 하다)"},
    {"id": 1158, "level": "high", "korean": "그건 오해에서 비롯된 일이야.", "english": "It came from a misunderstanding.", "hint": "come from = ~에서 비롯되다"},
    {"id": 1159, "level": "high", "korean": "나는 내 선택에 책임을 질 거야.", "english": "I'll take responsibility for my choices.", "hint": "take responsibility for = ~에 책임지다"},
    {"id": 1160, "level": "high", "korean": "결국 중요한 건 꾸준함이야.", "english": "At the end of the day, consistency is what matters.", "hint": "At the end of the day = 결국에는"},

    # ═══════════ 일상생활 — 실생활 필수 표현 ═══════════
    {"id": 1161, "level": "daily", "korean": "잠깐만 기다려 줄래?", "english": "Can you wait a second?", "hint": "wait a second = 잠깐 기다리다"},
    {"id": 1162, "level": "daily", "korean": "나 지금 가는 중이야.", "english": "I'm on my way.", "hint": "on my way = 가는 중"},
    {"id": 1163, "level": "daily", "korean": "이거 얼마예요?", "english": "How much is this?", "hint": "How much is ~? (가격 묻기)"},
    {"id": 1164, "level": "daily", "korean": "계산은 따로 해주세요.", "english": "Can we pay separately?", "hint": "pay separately = 따로 계산하다"},
    {"id": 1165, "level": "daily", "korean": "영수증 필요하세요?", "english": "Do you need a receipt?", "hint": "receipt = 영수증 (p는 묵음)"},
    {"id": 1166, "level": "daily", "korean": "이 자리 비었나요?", "english": "Is this seat taken?", "hint": "Is this seat taken? (직역 아님 — 관용 표현)"},
    {"id": 1167, "level": "daily", "korean": "조금만 비켜 주시겠어요?", "english": "Could you move over a little?", "hint": "move over = 옆으로 비키다"},
    {"id": 1168, "level": "daily", "korean": "다시 한번 확인해 볼게요.", "english": "Let me double-check.", "hint": "double-check = 재확인하다"},
    {"id": 1169, "level": "daily", "korean": "제가 도와드릴까요?", "english": "Do you need any help?", "hint": "Do you need any help?"},
    {"id": 1170, "level": "daily", "korean": "죄송한데 다시 말씀해 주시겠어요?", "english": "Sorry, could you repeat that?", "hint": "Could you repeat that?"},
    {"id": 1171, "level": "daily", "korean": "나 오늘 진짜 피곤해.", "english": "I'm really tired today.", "hint": "exhausted를 쓰면 더 강한 표현"},
    {"id": 1172, "level": "daily", "korean": "우리 뭐 먹을까?", "english": "What should we eat?", "hint": "What should we ~? (뭘 할지 상의)"},
    {"id": 1173, "level": "daily", "korean": "배달 시킬까?", "english": "Should we order delivery?", "hint": "order delivery = 배달 주문하다"},
    {"id": 1174, "level": "daily", "korean": "나 이거 처음 해봐.", "english": "This is my first time doing this.", "hint": "my first time + -ing"},
    {"id": 1175, "level": "daily", "korean": "별거 아니야.", "english": "It's no big deal.", "hint": "no big deal = 별일 아니다"},
    {"id": 1176, "level": "daily", "korean": "조심히 들어가.", "english": "Get home safe.", "hint": "Get home safe (헤어질 때 인사)"},
    {"id": 1177, "level": "daily", "korean": "무슨 일 있어?", "english": "Is something wrong?", "hint": "What's going on?도 자주 씀"},
    {"id": 1178, "level": "daily", "korean": "나중에 다시 얘기하자.", "english": "Let's talk about it later.", "hint": "talk about it later"},
    {"id": 1179, "level": "daily", "korean": "그거 좋은 생각이다!", "english": "That's a great idea!", "hint": "That's a great idea!"},
    {"id": 1180, "level": "daily", "korean": "이번엔 내가 살게.", "english": "It's on me this time.", "hint": "It's on me = 내가 낼게"},
    {"id": 1181, "level": "daily", "korean": "시간 괜찮아?", "english": "Do you have time?", "hint": "Do you have time? (시간 여유 묻기)"},
    {"id": 1182, "level": "daily", "korean": "나 길을 잃은 것 같아.", "english": "I think I'm lost.", "hint": "I'm lost = 길을 잃었다"},
    {"id": 1183, "level": "daily", "korean": "핸드폰 배터리가 다 됐어.", "english": "My phone is dead.", "hint": "My phone is dead (배터리 방전)"},
    {"id": 1184, "level": "daily", "korean": "예약하고 싶은데요.", "english": "I'd like to make a reservation.", "hint": "make a reservation = 예약하다"},
    {"id": 1185, "level": "daily", "korean": "이거 반품할 수 있나요?", "english": "Can I return this?", "hint": "return = 반품하다"},
    {"id": 1186, "level": "daily", "korean": "조금 더 생각해 볼게요.", "english": "Let me think about it a bit more.", "hint": "Let me think about it"},
    {"id": 1187, "level": "daily", "korean": "약속 시간을 바꿔도 될까?", "english": "Can we change the time?", "hint": "reschedule을 쓰면 더 격식 있는 표현"},
    {"id": 1188, "level": "daily", "korean": "나 감기 걸린 것 같아.", "english": "I think I'm coming down with a cold.", "hint": "come down with = (병에) 걸리다"},
    {"id": 1189, "level": "daily", "korean": "여기 와이파이 되나요?", "english": "Do you have Wi-Fi here?", "hint": "Do you have Wi-Fi?"},
    {"id": 1190, "level": "daily", "korean": "화장실이 어디예요?", "english": "Where's the restroom?", "hint": "restroom (미국) / toilet보다 정중"},
    {"id": 1191, "level": "daily", "korean": "이거 포장해 주세요.", "english": "Can I get this to go?", "hint": "to go = 포장으로"},
    {"id": 1192, "level": "daily", "korean": "조금만 조용히 해 주시겠어요?", "english": "Could you keep it down, please?", "hint": "keep it down = 소리를 낮추다"},
    {"id": 1193, "level": "daily", "korean": "제 차례인가요?", "english": "Is it my turn?", "hint": "my turn = 내 차례"},
    {"id": 1194, "level": "daily", "korean": "먼저 하세요.", "english": "Go ahead.", "hint": "Go ahead / After you (양보)"},
    {"id": 1195, "level": "daily", "korean": "잠깐 실례할게요.", "english": "Excuse me for a moment.", "hint": "Excuse me for a moment"},
    {"id": 1196, "level": "daily", "korean": "오랜만이야! 잘 지냈어?", "english": "Long time no see! How have you been?", "hint": "How have you been? (그동안 어떻게 지냈어?)"},
    {"id": 1197, "level": "daily", "korean": "나 좀 늦을 것 같아.", "english": "I'm running a bit late.", "hint": "run late = 늦어지다"},
    {"id": 1198, "level": "daily", "korean": "신경 써줘서 고마워.", "english": "Thanks for thinking of me.", "hint": "think of me = 나를 생각해주다"},
    {"id": 1199, "level": "daily", "korean": "천천히 해도 돼.", "english": "Take your time.", "hint": "Take your time = 천천히 하세요"},
    {"id": 1200, "level": "daily", "korean": "다음에 또 봐요!", "english": "See you next time!", "hint": "See you + 시간 표현"},

    # ═══════════ 외국인 도와주기 — 길 안내·안내·배려 ═══════════
    {"id": 1201, "level": "helper", "korean": "도와드릴까요?", "english": "Can I help you?", "hint": "Can I help you? (먼저 다가갈 때)"},
    {"id": 1202, "level": "helper", "korean": "어디를 찾고 계세요?", "english": "What are you looking for?", "hint": "look for = ~을 찾다"},
    {"id": 1203, "level": "helper", "korean": "여기서 직진하시면 돼요.", "english": "Just go straight from here.", "hint": "go straight = 직진하다"},
    {"id": 1204, "level": "helper", "korean": "두 번째 골목에서 오른쪽으로 도세요.", "english": "Turn right at the second corner.", "hint": "turn right/left at + 장소"},
    {"id": 1205, "level": "helper", "korean": "걸어서 5분 정도 걸려요.", "english": "It takes about five minutes on foot.", "hint": "It takes + 시간 / on foot = 걸어서"},
    {"id": 1206, "level": "helper", "korean": "지하철 2호선을 타세요.", "english": "Take subway line 2.", "hint": "take + 교통수단 / line 2 = 2호선"},
    {"id": 1207, "level": "helper", "korean": "다음 역에서 내리세요.", "english": "Get off at the next station.", "hint": "get off = (교통수단에서) 내리다"},
    {"id": 1208, "level": "helper", "korean": "시청역에서 환승하셔야 해요.", "english": "You need to transfer at City Hall Station.", "hint": "transfer = 환승하다"},
    {"id": 1209, "level": "helper", "korean": "제가 같이 가 드릴게요.", "english": "I'll walk you there.", "hint": "walk someone there = 데려다주다"},
    {"id": 1210, "level": "helper", "korean": "지도에서 보여드릴게요.", "english": "Let me show you on the map.", "hint": "Let me show you = 보여드릴게요"},
    {"id": 1211, "level": "helper", "korean": "저기 큰 건물 보이시죠?", "english": "Do you see that big building over there?", "hint": "over there = 저기에"},
    {"id": 1212, "level": "helper", "korean": "그 건물 바로 옆에 있어요.", "english": "It's right next to that building.", "hint": "right next to = 바로 옆에"},
    {"id": 1213, "level": "helper", "korean": "길 건너편에 있어요.", "english": "It's across the street.", "hint": "across the street = 길 건너편에"},
    {"id": 1214, "level": "helper", "korean": "여기서는 좀 멀어요. 택시를 타시는 게 좋겠어요.", "english": "It's a bit far from here. You'd better take a taxi.", "hint": "You'd better + 동사원형 (~하는 게 좋겠다)"},
    {"id": 1215, "level": "helper", "korean": "이 근처에 편의점이 있어요.", "english": "There's a convenience store nearby.", "hint": "nearby = 근처에"},
    {"id": 1216, "level": "helper", "korean": "한국 음식 좋아하세요?", "english": "Do you like Korean food?", "hint": "Do you like ~?"},
    {"id": 1217, "level": "helper", "korean": "이 식당 정말 맛있어요. 추천해요.", "english": "This restaurant is really good. I recommend it.", "hint": "I recommend it = 추천해요"},
    {"id": 1218, "level": "helper", "korean": "이건 조금 매워요.", "english": "This is a little spicy.", "hint": "spicy = 매운 / a little = 조금"},
    {"id": 1219, "level": "helper", "korean": "이건 한국 전통 음식이에요.", "english": "This is traditional Korean food.", "hint": "traditional = 전통적인"},
    {"id": 1220, "level": "helper", "korean": "제가 주문을 도와드릴까요?", "english": "Would you like me to help you order?", "hint": "Would you like me to + 동사원형?"},
    {"id": 1221, "level": "helper", "korean": "영어 메뉴판이 있는지 물어볼게요.", "english": "I'll ask if they have an English menu.", "hint": "ask if = ~인지 물어보다"},
    {"id": 1222, "level": "helper", "korean": "여기서는 신발을 벗으셔야 해요.", "english": "You need to take off your shoes here.", "hint": "take off = 벗다"},
    {"id": 1223, "level": "helper", "korean": "사진 찍어 드릴까요?", "english": "Would you like me to take a picture?", "hint": "take a picture = 사진을 찍다"},
    {"id": 1224, "level": "helper", "korean": "여기는 꼭 가보셔야 해요.", "english": "You should definitely visit this place.", "hint": "definitely = 꼭, 반드시"},
    {"id": 1225, "level": "helper", "korean": "주말에는 사람이 많아요.", "english": "It gets crowded on weekends.", "hint": "get crowded = 붐비게 되다"},
    {"id": 1226, "level": "helper", "korean": "입장료는 무료예요.", "english": "Admission is free.", "hint": "admission = 입장(료)"},
    {"id": 1227, "level": "helper", "korean": "오후 6시에 문을 닫아요.", "english": "It closes at 6 p.m.", "hint": "close at + 시각"},
    {"id": 1228, "level": "helper", "korean": "여기서는 사진 촬영이 금지예요.", "english": "Photography isn't allowed here.", "hint": "isn't allowed = 허용되지 않는다"},
    {"id": 1229, "level": "helper", "korean": "이 앱을 쓰시면 훨씬 편해요.", "english": "This app will make it much easier for you.", "hint": "make it easier = 더 쉽게 만들다"},
    {"id": 1230, "level": "helper", "korean": "교통카드를 사시는 게 좋아요.", "english": "You should buy a transportation card.", "hint": "transportation card = 교통카드"},
    {"id": 1231, "level": "helper", "korean": "편의점에서 충전할 수 있어요.", "english": "You can recharge it at a convenience store.", "hint": "recharge = 충전하다"},
    {"id": 1232, "level": "helper", "korean": "제 번호를 드릴게요. 도움이 필요하면 연락하세요.", "english": "Let me give you my number. Contact me if you need help.", "hint": "Contact me if ~ = ~하면 연락하세요"},
    {"id": 1233, "level": "helper", "korean": "한국에 오신 걸 환영합니다!", "english": "Welcome to Korea!", "hint": "Welcome to + 장소"},
    {"id": 1234, "level": "helper", "korean": "한국 여행은 어떠세요?", "english": "How do you like Korea so far?", "hint": "so far = 지금까지"},
    {"id": 1235, "level": "helper", "korean": "조금만 천천히 말씀해 주시겠어요?", "english": "Could you speak a little slower?", "hint": "speak slower = 더 천천히 말하다"},
    {"id": 1236, "level": "helper", "korean": "제 영어가 서툴러서 죄송해요.", "english": "Sorry, my English isn't very good.", "hint": "isn't very good = 그리 좋지 않다"},
    {"id": 1237, "level": "helper", "korean": "제가 제대로 이해했는지 확인할게요.", "english": "Let me make sure I understood correctly.", "hint": "make sure = 확실히 하다"},
    {"id": 1238, "level": "helper", "korean": "다른 도움이 필요하시면 말씀하세요.", "english": "Let me know if you need anything else.", "hint": "Let me know if ~ / anything else = 다른 것"},
    {"id": 1239, "level": "helper", "korean": "즐거운 여행 되세요!", "english": "Enjoy your trip!", "hint": "Enjoy your + 명사"},
    {"id": 1240, "level": "helper", "korean": "조심히 가세요!", "english": "Take care!", "hint": "Take care! (헤어질 때 인사)"},
    # ═══════════ 비즈니스 표현 — 실무 필수 표현 ═══════════
    {"id": 1241, "level": "business", "korean": "다음 주에 프로젝트에 대해 짧게 얘기 나눠요.", "english": "Let's touch base next week about the project.", "hint": "touch base = 잠깐 연락해 상황을 확인하다"},
    {"id": 1242, "level": "business", "korean": "좋은 지적이네요 — 그건 따로 이야기하죠.", "english": "That's a great point — let's take this offline.", "hint": "take this offline = (회의 중) 나중에 따로 논의하다"},
    {"id": 1243, "level": "business", "korean": "데이터를 확인하고 나서 다시 연락드릴게요.", "english": "I'll circle back to you once I have the data.", "hint": "circle back = 나중에 다시 이야기하다"},
    {"id": 1244, "level": "business", "korean": "우리 모두 같은 이해를 하고 있는지 확인하고 싶어요.", "english": "I just want to make sure we're all on the same page.", "hint": "on the same page = 인식이 일치하다"},
    {"id": 1245, "level": "business", "korean": "이 전략은 우리 매출에 실질적인 변화를 만들 수 있어요.", "english": "This strategy could really move the needle on our sales.", "hint": "move the needle = 의미 있는 진전을 만들다"},
    {"id": 1246, "level": "business", "korean": "예산에 대해 대략적인 수치를 알려주실 수 있나요?", "english": "Can you give me a ballpark figure for the budget?", "hint": "ballpark figure = 어림잡은 대략적 수치"},
    {"id": 1247, "level": "business", "korean": "이건 두 회사 모두에게 유리한 상황인 것 같아요.", "english": "I think this is a win-win situation for both companies.", "hint": "win-win situation = 양측 모두 이득인 상황"},
    {"id": 1248, "level": "business", "korean": "성공적인 협상에는 항상 서로 양보가 필요해요.", "english": "Successful negotiations always involve some give and take.", "hint": "give and take = 서로 주고받는 양보"},
    {"id": 1249, "level": "business", "korean": "가능한 한 빨리 계약서를 검토해 주세요.", "english": "Please review the contract at your earliest convenience.", "hint": "at your earliest convenience = 가능한 한 빨리 (정중한 표현)"},
    {"id": 1250, "level": "business", "korean": "경쟁사와 비교해 귀사의 차별화된 가치는 무엇인가요?", "english": "What's your value proposition compared to competitors?", "hint": "value proposition = 차별화된 가치 제안"},
    {"id": 1251, "level": "business", "korean": "논의한 대로 수정된 제안서를 첨부합니다.", "english": "As per our discussion, I'm attaching the revised proposal.", "hint": "as per our discussion = 우리가 논의한 대로"},
    {"id": 1252, "level": "business", "korean": "요청하신 보고서를 첨부하오니 확인 부탁드립니다.", "english": "Please find attached the report you requested.", "hint": "please find attached = 첨부 파일을 확인해주세요 (이메일 공식 표현)"},
    {"id": 1253, "level": "business", "korean": "지난주에 보낸 이메일에 대해 확인차 연락드렸습니다.", "english": "I wanted to follow up on my email from last week.", "hint": "I wanted to follow up on ~ = ~에 대해 확인차 연락드립니다"},
    {"id": 1254, "level": "business", "korean": "앞으로는 매주 월요일에 보고서를 보내주세요.", "english": "Going forward, please send reports every Monday.", "hint": "going forward = 앞으로는, 향후에는"},
    {"id": 1255, "level": "business", "korean": "이 건에 마케팅팀도 포함시켜 줄 수 있나요?", "english": "Can you loop in the marketing team on this?", "hint": "loop someone in = ~를 논의에 포함시키다"},
    {"id": 1256, "level": "business", "korean": "간단히 말하자면, 비용을 20% 줄여야 합니다.", "english": "To put it simply, we need to cut costs by 20%.", "hint": "to put it simply = 간단히 말하자면"},
    {"id": 1257, "level": "business", "korean": "결론은, 자원이 더 필요하다는 겁니다.", "english": "The bottom line is, we need more resources.", "hint": "the bottom line is = 결론은, 핵심은"},
    {"id": 1258, "level": "business", "korean": "오늘의 핵심 요점은 꾸준함이 중요하다는 것입니다.", "english": "The key takeaway from today is that consistency matters.", "hint": "takeaway = 핵심 요점, 기억해야 할 포인트"},
    {"id": 1259, "level": "business", "korean": "3분기 수치를 더 자세히 살펴보겠습니다.", "english": "Let me drill down into the Q3 numbers.", "hint": "drill down into = 더 깊이 파고들어 분석하다"},
    {"id": 1260, "level": "business", "korean": "이 프로젝트를 맡을 여유가 있으신가요?", "english": "Do you have the bandwidth to take on this project?", "hint": "bandwidth = 처리할 여유 (시간·역량)"},
    {"id": 1261, "level": "business", "korean": "기존 고객층을 적극 활용해야 합니다.", "english": "We should leverage our existing customer base.", "hint": "leverage = (자원을) 전략적으로 활용하다"},
    {"id": 1262, "level": "business", "korean": "미리 알려드리는데, 클라이언트 미팅이 3시로 옮겨졌어요.", "english": "Just a heads up — the client meeting is moved to 3pm.", "hint": "heads up = 미리 알림, 사전 통보"},
    {"id": 1263, "level": "business", "korean": "팀에서 무리한 일정에 반대 의견을 냈어요.", "english": "The team pushed back on the aggressive timeline.", "hint": "push back on ~ = ~에 반대 의견을 제기하다"},
    {"id": 1264, "level": "business", "korean": "아이디어만이 아니라 실행 가능한 계획이 필요합니다.", "english": "We need actionable steps, not just ideas.", "hint": "actionable = 바로 실행에 옮길 수 있는"},
]


LEVELS = [
    {"id": "elem_mid",  "title": "초등 중학년",     "emoji": "🌱", "desc": "3~4학년 · 기초 문장 만들기"},
    {"id": "elem_high", "title": "초등 고학년",     "emoji": "🌿", "desc": "5~6학년 · 과거·미래·비교"},
    {"id": "middle",    "title": "중학교",          "emoji": "📘", "desc": "접속사·완료시제·의견 표현"},
    {"id": "high",      "title": "고등학교",        "emoji": "🎓", "desc": "가정법·관계사·추상 표현"},
    {"id": "daily",     "title": "일상생활",        "emoji": "🏠", "desc": "실생활에서 자주 쓰는 말"},
    {"id": "helper",    "title": "외국인 도와주기", "emoji": "🤝", "desc": "길 안내·주문 도움·관광 안내"},
    {"id": "business",  "title": "비즈니스 표현",   "emoji": "💼", "desc": "회의·이메일·협상 실무 표현"},
]
