"""오픽 90일 커리큘럼 — 초보자 → IM3~IH 목표
Phase 1 (Day 1-28): 기초 문장 + 서베이 주제 (현재시제 묘사/습관)
Phase 2 (Day 29-56): 과거 경험 + 비교/변화 + 돌발주제 기초
Phase 3 (Day 57-90): 롤플레이 + 의견 표현 + 콤보 실전 + 모의고사

매일: 오픽 실전 질문 1개 + 단어 5개 + 핵심 표현 2개 + 스피킹 미션
"""

OPIC_CURRICULUM = [
    # ═══════════ Phase 1: Week 1 — 자기소개와 우리 집 ═══════════
    {"day": 1, "week": 1, "phase": 1, "topic": "자기소개 — 이름과 직업", "type": "서베이",
     "question": "Let's start the interview now. Tell me a little about yourself.",
     "mission": "이름, 직업(또는 학생), 사는 곳을 포함해 30초 동안 끊기지 않고 자기소개하기",
     "vocab": [
         {"word": "introduce", "meaning": "소개하다", "example": "Let me introduce myself."},
         {"word": "currently", "meaning": "현재, 지금", "example": "I'm currently working at a company."},
         {"word": "in charge of", "meaning": "~을 담당하는", "example": "I'm in charge of marketing."},
         {"word": "personality", "meaning": "성격", "example": "I have an outgoing personality."},
         {"word": "passionate", "meaning": "열정적인", "example": "I'm passionate about my work."},
     ],
     "expressions": [
         {"phrase": "I work as ...", "meaning": "저는 ~로 일해요"},
         {"phrase": "In my free time, I usually ...", "meaning": "여가 시간에 저는 보통 ~해요"},
     ]},
    {"day": 2, "week": 1, "phase": 1, "topic": "성격과 취향 말하기", "type": "서베이",
     "question": "How would you describe your personality? What kind of person are you?",
     "mission": "내 성격을 형용사 3개 이상 사용해 예시와 함께 설명하기",
     "vocab": [
         {"word": "outgoing", "meaning": "외향적인", "example": "I'm quite outgoing."},
         {"word": "easygoing", "meaning": "느긋한, 태평한", "example": "My friends say I'm easygoing."},
         {"word": "organized", "meaning": "계획적인, 정리된", "example": "I'm a very organized person."},
         {"word": "tend to", "meaning": "~하는 경향이 있다", "example": "I tend to be shy at first."},
         {"word": "get along with", "meaning": "~와 잘 지내다", "example": "I get along with everyone."},
     ],
     "expressions": [
         {"phrase": "People say that I'm ...", "meaning": "사람들이 저더러 ~하대요"},
         {"phrase": "I would say I'm more of a ...", "meaning": "저는 ~에 가까운 사람이에요"},
     ]},
    {"day": 3, "week": 1, "phase": 1, "topic": "우리 집 묘사", "type": "서베이",
     "question": "I would like to know where you live. Can you describe your house or apartment?",
     "mission": "우리 집의 구조(방 개수, 거실 등)와 가장 좋아하는 특징을 묘사하기",
     "vocab": [
         {"word": "apartment complex", "meaning": "아파트 단지", "example": "I live in an apartment complex."},
         {"word": "spacious", "meaning": "넓은", "example": "The living room is spacious."},
         {"word": "cozy", "meaning": "아늑한", "example": "My room is small but cozy."},
         {"word": "view", "meaning": "전망", "example": "It has a great view of the city."},
         {"word": "convenient", "meaning": "편리한", "example": "The location is really convenient."},
     ],
     "expressions": [
         {"phrase": "I live in a two-bedroom apartment.", "meaning": "방 2개짜리 아파트에 살아요"},
         {"phrase": "What I like most about my place is ...", "meaning": "우리 집에서 제일 좋은 건 ~예요"},
     ]},
    {"day": 4, "week": 1, "phase": 1, "topic": "내가 좋아하는 공간", "type": "서베이",
     "question": "What is your favorite room in your home? Why do you like it?",
     "mission": "집에서 가장 좋아하는 공간과 거기서 주로 하는 일 2가지 말하기",
     "vocab": [
         {"word": "comfortable", "meaning": "편안한", "example": "My bed is so comfortable."},
         {"word": "relax", "meaning": "휴식하다", "example": "I relax on the couch after work."},
         {"word": "decorate", "meaning": "꾸미다", "example": "I decorated my room with photos."},
         {"word": "furniture", "meaning": "가구", "example": "I don't have much furniture."},
         {"word": "atmosphere", "meaning": "분위기", "example": "The atmosphere is very calm."},
     ],
     "expressions": [
         {"phrase": "I spend most of my time in ...", "meaning": "저는 대부분의 시간을 ~에서 보내요"},
         {"phrase": "It's the perfect place to unwind.", "meaning": "긴장을 풀기에 완벽한 곳이에요"},
     ]},
    {"day": 5, "week": 1, "phase": 1, "topic": "우리 동네 묘사", "type": "서베이",
     "question": "Tell me about your neighborhood. What does it look like?",
     "mission": "동네에 있는 시설 3가지와 동네의 분위기를 묘사하기",
     "vocab": [
         {"word": "neighborhood", "meaning": "동네, 이웃", "example": "My neighborhood is quiet."},
         {"word": "within walking distance", "meaning": "걸어갈 수 있는 거리에", "example": "The subway is within walking distance."},
         {"word": "crowded", "meaning": "붐비는", "example": "It gets crowded on weekends."},
         {"word": "facility", "meaning": "시설", "example": "There are many facilities nearby."},
         {"word": "residential area", "meaning": "주거 지역", "example": "It's a residential area."},
     ],
     "expressions": [
         {"phrase": "There is a park right next to my place.", "meaning": "집 바로 옆에 공원이 있어요"},
         {"phrase": "It takes about 10 minutes to get to ...", "meaning": "~까지 10분 정도 걸려요"},
     ]},
    {"day": 6, "week": 1, "phase": 1, "topic": "가족 소개", "type": "서베이",
     "question": "Tell me about your family. Who do you live with?",
     "mission": "함께 사는 가족(또는 혼자 사는 이유)과 가족 구성원 특징 말하기",
     "vocab": [
         {"word": "sibling", "meaning": "형제자매", "example": "I have two siblings."},
         {"word": "the eldest", "meaning": "첫째, 맏이", "example": "I'm the eldest in my family."},
         {"word": "live alone", "meaning": "혼자 살다", "example": "I've lived alone for 3 years."},
         {"word": "close-knit", "meaning": "(가족이) 화목한, 유대가 깊은", "example": "We are a close-knit family."},
         {"word": "resemble", "meaning": "닮다", "example": "I resemble my mother."},
     ],
     "expressions": [
         {"phrase": "There are four people in my family.", "meaning": "우리 가족은 네 명이에요"},
         {"phrase": "We get together once a month.", "meaning": "우리는 한 달에 한 번 모여요"},
     ]},
    {"day": 7, "week": 1, "phase": 1, "topic": "Week 1 복습 — 자기소개 풀버전", "type": "복습",
     "question": "Tell me about yourself — your personality, where you live, and your family.",
     "mission": "이번 주 배운 표현으로 1분 자기소개 완성하기 (성격+집+동네+가족)",
     "vocab": [
         {"word": "overall", "meaning": "전반적으로", "example": "Overall, I'm happy with my life."},
         {"word": "to sum up", "meaning": "요약하자면", "example": "To sum up, I love my neighborhood."},
         {"word": "as I mentioned", "meaning": "말씀드렸듯이", "example": "As I mentioned, I live alone."},
         {"word": "typical", "meaning": "전형적인, 보통의", "example": "I'm a typical office worker."},
         {"word": "satisfied with", "meaning": "~에 만족하는", "example": "I'm satisfied with my place."},
     ],
     "expressions": [
         {"phrase": "Let me tell you about ...", "meaning": "~에 대해 말씀드릴게요"},
         {"phrase": "That's pretty much it about me.", "meaning": "저에 대한 건 대충 이 정도예요"},
     ]},

    # ═══════════ Week 2 — 일상 루틴 (현재시제 습관) ═══════════
    {"day": 8, "week": 2, "phase": 1, "topic": "아침 루틴", "type": "서베이",
     "question": "Tell me about your typical morning. What do you usually do after you wake up?",
     "mission": "아침에 일어나서 집을 나설 때까지의 루틴을 순서대로 말하기 (first, then, after that 사용)",
     "vocab": [
         {"word": "wake up", "meaning": "잠에서 깨다", "example": "I wake up at 7 every day."},
         {"word": "get ready", "meaning": "준비하다", "example": "It takes 30 minutes to get ready."},
         {"word": "grab a bite", "meaning": "간단히 먹다", "example": "I grab a bite before work."},
         {"word": "rush", "meaning": "서두르다", "example": "I always rush in the morning."},
         {"word": "routine", "meaning": "루틴, 일과", "example": "My morning routine is simple."},
     ],
     "expressions": [
         {"phrase": "First thing in the morning, I ...", "meaning": "아침에 제일 먼저 ~해요"},
         {"phrase": "After that, I usually ...", "meaning": "그 다음엔 보통 ~해요"},
     ]},
    {"day": 9, "week": 2, "phase": 1, "topic": "출퇴근/통학", "type": "서베이",
     "question": "How do you get to work or school? Tell me about your commute.",
     "mission": "출퇴근 수단, 걸리는 시간, 이동 중에 하는 일 말하기",
     "vocab": [
         {"word": "commute", "meaning": "통근(하다)", "example": "My commute takes an hour."},
         {"word": "public transportation", "meaning": "대중교통", "example": "I use public transportation."},
         {"word": "transfer", "meaning": "환승하다", "example": "I transfer at Seoul Station."},
         {"word": "rush hour", "meaning": "출퇴근 혼잡 시간", "example": "Rush hour is terrible."},
         {"word": "packed", "meaning": "꽉 찬, 만원인", "example": "The subway is packed in the morning."},
     ],
     "expressions": [
         {"phrase": "It takes about an hour door to door.", "meaning": "집에서 회사까지 한 시간쯤 걸려요"},
         {"phrase": "On my way to work, I listen to ...", "meaning": "출근길에 ~을 들어요"},
     ]},
    {"day": 10, "week": 2, "phase": 1, "topic": "직장/학교에서의 하루", "type": "서베이",
     "question": "What do you usually do at work or school? Describe your typical day there.",
     "mission": "하루 업무(수업)의 흐름과 점심시간에 하는 일 말하기",
     "vocab": [
         {"word": "task", "meaning": "업무, 과제", "example": "I check my tasks first."},
         {"word": "attend a meeting", "meaning": "회의에 참석하다", "example": "I attend meetings every morning."},
         {"word": "colleague", "meaning": "동료", "example": "I have lunch with my colleagues."},
         {"word": "deadline", "meaning": "마감기한", "example": "I have a deadline this week."},
         {"word": "take a break", "meaning": "휴식을 취하다", "example": "I take a break at 3 pm."},
     ],
     "expressions": [
         {"phrase": "My day starts with checking emails.", "meaning": "제 하루는 이메일 확인으로 시작해요"},
         {"phrase": "I'm usually swamped with work.", "meaning": "저는 보통 일이 산더미예요"},
     ]},
    {"day": 11, "week": 2, "phase": 1, "topic": "저녁 루틴", "type": "서베이",
     "question": "What do you usually do in the evening after work or school?",
     "mission": "퇴근 후부터 잠들기 전까지의 루틴 말하기",
     "vocab": [
         {"word": "get off work", "meaning": "퇴근하다", "example": "I get off work at 6."},
         {"word": "wind down", "meaning": "긴장을 풀다", "example": "I wind down with some TV."},
         {"word": "stay up late", "meaning": "늦게까지 깨어 있다", "example": "I sometimes stay up late."},
         {"word": "fall asleep", "meaning": "잠들다", "example": "I fall asleep around midnight."},
         {"word": "browse", "meaning": "(인터넷을) 둘러보다", "example": "I browse the internet in bed."},
     ],
     "expressions": [
         {"phrase": "As soon as I get home, I ...", "meaning": "집에 오자마자 ~해요"},
         {"phrase": "Before I go to bed, I usually ...", "meaning": "자기 전에 보통 ~해요"},
     ]},
    {"day": 12, "week": 2, "phase": 1, "topic": "주말 루틴", "type": "서베이",
     "question": "How do you usually spend your weekends?",
     "mission": "토요일과 일요일에 각각 주로 하는 일 말하기",
     "vocab": [
         {"word": "sleep in", "meaning": "늦잠 자다", "example": "I sleep in on Saturdays."},
         {"word": "catch up on", "meaning": "밀린 것을 하다", "example": "I catch up on sleep."},
         {"word": "run errands", "meaning": "볼일을 보다", "example": "I run errands on Sundays."},
         {"word": "hang out", "meaning": "어울려 놀다", "example": "I hang out with friends."},
         {"word": "recharge", "meaning": "재충전하다", "example": "Weekends help me recharge."},
     ],
     "expressions": [
         {"phrase": "On weekends, I like to take it slow.", "meaning": "주말엔 느긋하게 보내는 걸 좋아해요"},
         {"phrase": "If the weather is nice, I go out.", "meaning": "날씨가 좋으면 밖에 나가요"},
     ]},
    {"day": 13, "week": 2, "phase": 1, "topic": "집안일", "type": "서베이",
     "question": "What household chores do you usually do? How often do you do them?",
     "mission": "자주 하는 집안일 3가지와 빈도(once a week 등) 말하기",
     "vocab": [
         {"word": "chore", "meaning": "집안일", "example": "I do chores on weekends."},
         {"word": "do the laundry", "meaning": "빨래하다", "example": "I do the laundry twice a week."},
         {"word": "vacuum", "meaning": "청소기를 돌리다", "example": "I vacuum every other day."},
         {"word": "take out the trash", "meaning": "쓰레기를 버리다", "example": "I take out the trash daily."},
         {"word": "tidy up", "meaning": "정리하다", "example": "I tidy up my desk every night."},
     ],
     "expressions": [
         {"phrase": "I do the dishes right after meals.", "meaning": "식사 후 바로 설거지를 해요"},
         {"phrase": "Honestly, I hate doing chores, but ...", "meaning": "솔직히 집안일은 싫지만..."},
     ]},
    {"day": 14, "week": 2, "phase": 1, "topic": "Week 2 복습 — 나의 하루 풀버전", "type": "복습",
     "question": "Describe a typical weekday for you, from morning to night.",
     "mission": "아침~밤까지 하루 전체를 시간 순서 연결어를 사용해 90초 말하기",
     "vocab": [
         {"word": "typically", "meaning": "일반적으로", "example": "Typically, I wake up at 7."},
         {"word": "afterwards", "meaning": "그 후에", "example": "Afterwards, I take a shower."},
         {"word": "meanwhile", "meaning": "그 동안에", "example": "Meanwhile, I check my phone."},
         {"word": "right after", "meaning": "직후에", "example": "Right after lunch, I take a walk."},
         {"word": "by the time", "meaning": "~할 때쯤", "example": "By the time I get home, it's 7."},
     ],
     "expressions": [
         {"phrase": "My day is pretty much the same every day.", "meaning": "제 하루는 매일 거의 똑같아요"},
         {"phrase": "It depends on the day, but usually ...", "meaning": "그날그날 다르지만 보통은..."},
     ]},

    # ═══════════ Week 3 — 취미/여가 1 (서베이 빈출) ═══════════
    {"day": 15, "week": 3, "phase": 1, "topic": "영화 보기", "type": "서베이",
     "question": "You indicated that you like watching movies. What kind of movies do you like?",
     "mission": "좋아하는 영화 장르 2가지와 그 이유, 얼마나 자주 보는지 말하기",
     "vocab": [
         {"word": "genre", "meaning": "장르", "example": "My favorite genre is comedy."},
         {"word": "plot", "meaning": "줄거리", "example": "The plot was amazing."},
         {"word": "touching", "meaning": "감동적인", "example": "It was a touching story."},
         {"word": "thrilling", "meaning": "스릴 넘치는", "example": "Action movies are thrilling."},
         {"word": "be into", "meaning": "~에 빠져 있다", "example": "I'm really into sci-fi movies."},
     ],
     "expressions": [
         {"phrase": "I'm a big fan of ...", "meaning": "저는 ~의 열렬한 팬이에요"},
         {"phrase": "It helps me take my mind off things.", "meaning": "잡생각을 잊게 해줘요"},
     ]},
    {"day": 16, "week": 3, "phase": 1, "topic": "음악 감상", "type": "서베이",
     "question": "What kind of music do you listen to? When do you usually listen to music?",
     "mission": "좋아하는 음악 장르, 듣는 상황(출근길, 운동 등), 좋아하는 가수 말하기",
     "vocab": [
         {"word": "lyrics", "meaning": "가사", "example": "I love the lyrics of this song."},
         {"word": "melody", "meaning": "멜로디", "example": "The melody is so catchy."},
         {"word": "upbeat", "meaning": "경쾌한", "example": "I listen to upbeat songs at the gym."},
         {"word": "calming", "meaning": "차분하게 하는", "example": "Piano music is calming."},
         {"word": "playlist", "meaning": "재생목록", "example": "I made a workout playlist."},
     ],
     "expressions": [
         {"phrase": "Music is a big part of my life.", "meaning": "음악은 제 삶의 큰 부분이에요"},
         {"phrase": "It depends on my mood.", "meaning": "제 기분에 따라 달라요"},
     ]},
    {"day": 17, "week": 3, "phase": 1, "topic": "공원 가기", "type": "서베이",
     "question": "You said you go to parks. Describe your favorite park. What does it look like?",
     "mission": "자주 가는 공원의 모습(시설, 사람들)과 거기서 하는 일 묘사하기",
     "vocab": [
         {"word": "trail", "meaning": "산책로", "example": "There's a nice walking trail."},
         {"word": "bench", "meaning": "벤치", "example": "I sit on a bench and relax."},
         {"word": "fountain", "meaning": "분수", "example": "There's a big fountain in the middle."},
         {"word": "get some fresh air", "meaning": "바람을 쐬다", "example": "I go there to get some fresh air."},
         {"word": "jog", "meaning": "조깅하다", "example": "Many people jog in the morning."},
     ],
     "expressions": [
         {"phrase": "It's a great place to clear my head.", "meaning": "머리를 식히기 좋은 곳이에요"},
         {"phrase": "The park is always full of people.", "meaning": "공원은 항상 사람들로 가득해요"},
     ]},
    {"day": 18, "week": 3, "phase": 1, "topic": "카페 가기", "type": "서베이",
     "question": "Tell me about a cafe you often go to. What is it like, and what do you do there?",
     "mission": "단골 카페의 분위기와 주로 시키는 메뉴, 거기서 하는 일 말하기",
     "vocab": [
         {"word": "regular", "meaning": "단골(손님)", "example": "I'm a regular at that cafe."},
         {"word": "interior", "meaning": "인테리어", "example": "The interior is modern."},
         {"word": "freshly brewed", "meaning": "갓 내린", "example": "I love freshly brewed coffee."},
         {"word": "chat", "meaning": "수다 떨다", "example": "I chat with friends there."},
         {"word": "work on", "meaning": "~을 작업하다", "example": "I work on my laptop at cafes."},
     ],
     "expressions": [
         {"phrase": "I go there at least twice a week.", "meaning": "적어도 일주일에 두 번은 가요"},
         {"phrase": "The vibe there is really nice.", "meaning": "거기 분위기가 정말 좋아요"},
     ]},
    {"day": 19, "week": 3, "phase": 1, "topic": "쇼핑", "type": "서베이",
     "question": "Do you like shopping? Where do you usually shop, and what do you buy?",
     "mission": "주로 쇼핑하는 장소(온라인/오프라인)와 사는 물건, 쇼핑 스타일 말하기",
     "vocab": [
         {"word": "window shopping", "meaning": "아이쇼핑", "example": "I enjoy window shopping."},
         {"word": "on sale", "meaning": "할인 중인", "example": "I only buy things on sale."},
         {"word": "impulse buying", "meaning": "충동구매", "example": "I try to avoid impulse buying."},
         {"word": "compare prices", "meaning": "가격을 비교하다", "example": "I compare prices online."},
         {"word": "affordable", "meaning": "(가격이) 적당한", "example": "The prices are affordable."},
     ],
     "expressions": [
         {"phrase": "I mostly shop online these days.", "meaning": "요즘은 주로 온라인으로 쇼핑해요"},
         {"phrase": "I can't resist a good deal.", "meaning": "좋은 할인은 그냥 못 지나쳐요"},
     ]},
    {"day": 20, "week": 3, "phase": 1, "topic": "인터넷/SNS", "type": "서베이",
     "question": "What do you usually do on the internet? Tell me about the websites or apps you use.",
     "mission": "자주 쓰는 앱/사이트 3가지와 각각 무엇을 하는지 말하기",
     "vocab": [
         {"word": "scroll through", "meaning": "(화면을) 스크롤하다", "example": "I scroll through Instagram."},
         {"word": "post", "meaning": "게시하다, 게시물", "example": "I rarely post photos."},
         {"word": "subscribe to", "meaning": "구독하다", "example": "I subscribe to several channels."},
         {"word": "content", "meaning": "콘텐츠", "example": "I watch cooking content."},
         {"word": "kill time", "meaning": "시간을 때우다", "example": "I watch videos to kill time."},
     ],
     "expressions": [
         {"phrase": "I spend way too much time on my phone.", "meaning": "핸드폰에 시간을 너무 많이 써요"},
         {"phrase": "It's a great way to stay updated.", "meaning": "최신 소식을 접하기 좋은 방법이에요"},
     ]},
    {"day": 21, "week": 3, "phase": 1, "topic": "Week 3 복습 — 취미 소개 종합", "type": "복습",
     "question": "Tell me about what you like to do in your free time and why you enjoy it.",
     "mission": "취미 2가지를 골라 언제/어디서/왜 좋아하는지 90초 말하기",
     "vocab": [
         {"word": "pastime", "meaning": "취미, 소일거리", "example": "My favorite pastime is reading."},
         {"word": "relieve stress", "meaning": "스트레스를 풀다", "example": "It helps me relieve stress."},
         {"word": "occasionally", "meaning": "가끔", "example": "I occasionally go to concerts."},
         {"word": "whenever", "meaning": "~할 때마다", "example": "Whenever I'm free, I watch movies."},
         {"word": "absorbed in", "meaning": "~에 몰두한", "example": "I get absorbed in good books."},
     ],
     "expressions": [
         {"phrase": "It's my go-to way to relax.", "meaning": "그게 제가 쉬는 단골 방법이에요"},
         {"phrase": "Time flies when I'm doing it.", "meaning": "그걸 할 땐 시간이 순삭이에요"},
     ]},

    # ═══════════ Week 4 — 취미/여가 2 + 운동/여행 ═══════════
    {"day": 22, "week": 4, "phase": 1, "topic": "걷기/조깅", "type": "서베이",
     "question": "You mentioned you enjoy walking. Where do you usually walk, and how often?",
     "mission": "걷는 장소, 빈도, 걷기의 좋은 점 2가지 말하기",
     "vocab": [
         {"word": "take a walk", "meaning": "산책하다", "example": "I take a walk after dinner."},
         {"word": "stroll", "meaning": "한가롭게 걷다", "example": "I stroll along the river."},
         {"word": "refreshing", "meaning": "상쾌한", "example": "The morning air is refreshing."},
         {"word": "stay in shape", "meaning": "몸매(건강)를 유지하다", "example": "Walking helps me stay in shape."},
         {"word": "scenery", "meaning": "풍경", "example": "The scenery along the path is beautiful."},
     ],
     "expressions": [
         {"phrase": "I try to walk at least 30 minutes a day.", "meaning": "하루에 최소 30분은 걸으려고 해요"},
         {"phrase": "It clears my mind.", "meaning": "머리가 맑아져요"},
     ]},
    {"day": 23, "week": 4, "phase": 1, "topic": "운동/헬스장", "type": "서베이",
     "question": "Tell me about the exercise you do. What is your workout routine like?",
     "mission": "하는 운동 종류, 빈도, 운동 루틴 순서대로 말하기",
     "vocab": [
         {"word": "work out", "meaning": "운동하다", "example": "I work out three times a week."},
         {"word": "gym", "meaning": "헬스장", "example": "I go to the gym near my house."},
         {"word": "stretch", "meaning": "스트레칭하다", "example": "I always stretch first."},
         {"word": "muscle", "meaning": "근육", "example": "I want to build muscle."},
         {"word": "sweat", "meaning": "땀 흘리다", "example": "I sweat a lot when I run."},
     ],
     "expressions": [
         {"phrase": "I start with a warm-up.", "meaning": "워밍업으로 시작해요"},
         {"phrase": "Working out gives me energy.", "meaning": "운동하면 에너지가 생겨요"},
     ]},
    {"day": 24, "week": 4, "phase": 1, "topic": "요리", "type": "서베이",
     "question": "Do you cook at home? Tell me about a dish you often make.",
     "mission": "자주 만드는 요리 하나를 골라 만드는 과정을 순서대로 설명하기",
     "vocab": [
         {"word": "ingredient", "meaning": "재료", "example": "I buy fresh ingredients."},
         {"word": "recipe", "meaning": "레시피", "example": "I found this recipe online."},
         {"word": "boil", "meaning": "끓이다", "example": "First, boil the water."},
         {"word": "fry", "meaning": "볶다, 튀기다", "example": "Then fry the vegetables."},
         {"word": "taste", "meaning": "맛(보다)", "example": "It tastes better than takeout."},
     ],
     "expressions": [
         {"phrase": "It's really simple to make.", "meaning": "만들기 정말 간단해요"},
         {"phrase": "I cook for myself most days.", "meaning": "저는 거의 매일 직접 요리해요"},
     ]},
    {"day": 25, "week": 4, "phase": 1, "topic": "국내 여행", "type": "서베이",
     "question": "You indicated that you like to travel domestically. Where do you like to go?",
     "mission": "좋아하는 국내 여행지와 거기서 하는 일, 가는 방법 말하기",
     "vocab": [
         {"word": "domestic", "meaning": "국내의", "example": "I prefer domestic trips."},
         {"word": "getaway", "meaning": "짧은 휴가", "example": "I need a weekend getaway."},
         {"word": "tourist attraction", "meaning": "관광 명소", "example": "Busan has many tourist attractions."},
         {"word": "local food", "meaning": "현지 음식", "example": "I always try local food."},
         {"word": "scenic", "meaning": "경치 좋은", "example": "The drive there is scenic."},
     ],
     "expressions": [
         {"phrase": "I usually travel by KTX.", "meaning": "저는 보통 KTX로 여행해요"},
         {"phrase": "It's only a two-hour drive away.", "meaning": "차로 두 시간밖에 안 걸려요"},
     ]},
    {"day": 26, "week": 4, "phase": 1, "topic": "해외 여행", "type": "서베이",
     "question": "Tell me about traveling abroad. What do you usually do when you travel to other countries?",
     "mission": "해외여행 갈 때 준비하는 것과 여행지에서 주로 하는 활동 말하기",
     "vocab": [
         {"word": "abroad", "meaning": "해외로", "example": "I travel abroad once a year."},
         {"word": "itinerary", "meaning": "여행 일정", "example": "I plan my itinerary in advance."},
         {"word": "sightseeing", "meaning": "관광", "example": "We went sightseeing all day."},
         {"word": "book", "meaning": "예약하다", "example": "I book flights early."},
         {"word": "culture", "meaning": "문화", "example": "I love experiencing new cultures."},
     ],
     "expressions": [
         {"phrase": "I like to immerse myself in the local culture.", "meaning": "현지 문화에 푹 빠져보는 걸 좋아해요"},
         {"phrase": "Traveling broadens my perspective.", "meaning": "여행은 시야를 넓혀줘요"},
     ]},
    {"day": 27, "week": 4, "phase": 1, "topic": "외식", "type": "서베이",
     "question": "How often do you eat out? Tell me about your favorite restaurant.",
     "mission": "외식 빈도, 좋아하는 식당의 메뉴와 분위기 묘사하기",
     "vocab": [
         {"word": "eat out", "meaning": "외식하다", "example": "I eat out twice a week."},
         {"word": "signature dish", "meaning": "대표 메뉴", "example": "Their signature dish is pasta."},
         {"word": "portion", "meaning": "양, 1인분", "example": "The portions are generous."},
         {"word": "reasonable", "meaning": "(가격이) 합리적인", "example": "The prices are reasonable."},
         {"word": "atmosphere", "meaning": "분위기", "example": "The atmosphere is cozy."},
     ],
     "expressions": [
         {"phrase": "This place never disappoints.", "meaning": "이 집은 실망시키는 법이 없어요"},
         {"phrase": "It's always packed on weekends.", "meaning": "주말엔 항상 만석이에요"},
     ]},
    {"day": 28, "week": 4, "phase": 1, "topic": "Phase 1 마무리 점검", "type": "복습",
     "question": "Tell me about your favorite hobby in detail — when you started, how often you do it, and why you love it.",
     "mission": "Phase 1 종합: 취미 하나를 배경+빈도+이유+느낌 구조로 2분 말하기",
     "vocab": [
         {"word": "look forward to", "meaning": "~을 기대하다", "example": "I look forward to weekends."},
         {"word": "definitely", "meaning": "확실히", "example": "It's definitely worth it."},
         {"word": "in particular", "meaning": "특히", "example": "I love jazz in particular."},
         {"word": "these days", "meaning": "요즘", "example": "These days, I'm into yoga."},
         {"word": "no matter how", "meaning": "아무리 ~해도", "example": "No matter how busy I am, I exercise."},
     ],
     "expressions": [
         {"phrase": "I can't imagine my life without it.", "meaning": "그것 없는 제 삶은 상상이 안 돼요"},
         {"phrase": "That's why I keep doing it.", "meaning": "그래서 계속하는 거예요"},
     ]},
    # ═══════════ Phase 2: Week 5 — 과거 경험 말하기 ═══════════
    {"day": 29, "week": 5, "phase": 2, "topic": "어제 있었던 일 (과거시제 시작)", "type": "과거경험",
     "question": "Tell me about what you did yesterday, from morning to night.",
     "mission": "어제 하루를 과거시제로만 말하기 (woke up, went, had...)",
     "vocab": [
         {"word": "woke up", "meaning": "일어났다 (wake의 과거)", "example": "I woke up late yesterday."},
         {"word": "grabbed", "meaning": "급히 먹었다/집었다", "example": "I grabbed a quick breakfast."},
         {"word": "headed to", "meaning": "~로 향했다", "example": "I headed to work at 8."},
         {"word": "ended up", "meaning": "결국 ~하게 됐다", "example": "I ended up working late."},
         {"word": "exhausted", "meaning": "완전히 지친", "example": "I was exhausted by evening."},
     ],
     "expressions": [
         {"phrase": "Yesterday was a pretty typical day.", "meaning": "어제는 꽤 평범한 하루였어요"},
         {"phrase": "By the end of the day, I was worn out.", "meaning": "하루가 끝날 무렵엔 녹초가 됐어요"},
     ]},
    {"day": 30, "week": 5, "phase": 2, "topic": "지난 주말", "type": "과거경험",
     "question": "What did you do last weekend? Tell me everything you did.",
     "mission": "지난 주말 활동을 시간 순서대로, 감정 표현 1개 이상 넣어 말하기",
     "vocab": [
         {"word": "spent", "meaning": "(시간을) 보냈다", "example": "I spent Saturday with my family."},
         {"word": "went out", "meaning": "외출했다", "example": "I went out for dinner."},
         {"word": "stayed in", "meaning": "집에 있었다", "example": "I stayed in on Sunday."},
         {"word": "caught up with", "meaning": "밀린 근황을 나눴다", "example": "I caught up with an old friend."},
         {"word": "relaxing", "meaning": "여유로운, 편안한", "example": "It was a relaxing weekend."},
     ],
     "expressions": [
         {"phrase": "It was exactly what I needed.", "meaning": "딱 제게 필요했던 거였어요"},
         {"phrase": "Before I knew it, the weekend was over.", "meaning": "어느새 주말이 끝나 있었어요"},
     ]},
    {"day": 31, "week": 5, "phase": 2, "topic": "최근에 본 영화", "type": "과거경험",
     "question": "Tell me about a movie you watched recently. What was it about, and how did you like it?",
     "mission": "최근 본 영화의 줄거리 요약 + 내 감상 말하기 (과거시제)",
     "vocab": [
         {"word": "recently", "meaning": "최근에", "example": "I watched a great movie recently."},
         {"word": "be about", "meaning": "~에 관한 것이다", "example": "It was about a lost dog."},
         {"word": "main character", "meaning": "주인공", "example": "The main character was brave."},
         {"word": "impressive", "meaning": "인상적인", "example": "The acting was impressive."},
         {"word": "highly recommend", "meaning": "강력 추천하다", "example": "I highly recommend it."},
     ],
     "expressions": [
         {"phrase": "It was based on a true story.", "meaning": "실화를 바탕으로 한 거였어요"},
         {"phrase": "I was on the edge of my seat.", "meaning": "손에 땀을 쥐고 봤어요"},
     ]},
    {"day": 32, "week": 5, "phase": 2, "topic": "기억에 남는 여행", "type": "과거경험",
     "question": "Tell me about a memorable trip you took. Where did you go, and what happened?",
     "mission": "여행 배경(언제/어디/누구와) + 한 일 + 가장 기억에 남는 순간 말하기",
     "vocab": [
         {"word": "memorable", "meaning": "기억에 남는", "example": "It was a memorable trip."},
         {"word": "a few years ago", "meaning": "몇 년 전에", "example": "I went there a few years ago."},
         {"word": "breathtaking", "meaning": "숨막히게 멋진", "example": "The view was breathtaking."},
         {"word": "explore", "meaning": "탐험하다, 둘러보다", "example": "We explored the old town."},
         {"word": "unforgettable", "meaning": "잊을 수 없는", "example": "It was an unforgettable experience."},
     ],
     "expressions": [
         {"phrase": "What made it special was ...", "meaning": "그걸 특별하게 만든 건 ~였어요"},
         {"phrase": "I still remember it like it was yesterday.", "meaning": "아직도 어제 일처럼 기억나요"},
     ]},
    {"day": 33, "week": 5, "phase": 2, "topic": "어린 시절 추억", "type": "과거경험",
     "question": "Tell me about a childhood memory that you remember well.",
     "mission": "어린 시절 기억 하나를 배경 설명 + 사건 + 느낌 구조로 말하기",
     "vocab": [
         {"word": "childhood", "meaning": "어린 시절", "example": "I had a happy childhood."},
         {"word": "used to", "meaning": "예전에 ~하곤 했다", "example": "I used to play outside a lot."},
         {"word": "growing up", "meaning": "자라면서", "example": "Growing up, I loved comics."},
         {"word": "vividly", "meaning": "생생하게", "example": "I remember it vividly."},
         {"word": "innocent", "meaning": "순수한, 천진한", "example": "Those were innocent times."},
     ],
     "expressions": [
         {"phrase": "When I was little, I used to ...", "meaning": "어렸을 때 저는 ~하곤 했어요"},
         {"phrase": "Looking back, those were the good old days.", "meaning": "돌이켜보면 그때가 좋은 시절이었죠"},
     ]},
    {"day": 34, "week": 5, "phase": 2, "topic": "학창 시절", "type": "과거경험",
     "question": "Tell me about your school days. What were you like as a student?",
     "mission": "학창 시절의 나 + 좋아했던 과목/활동 + 기억나는 에피소드 말하기",
     "vocab": [
         {"word": "back in school", "meaning": "학교 다닐 때", "example": "Back in school, I was quiet."},
         {"word": "subject", "meaning": "과목", "example": "My favorite subject was history."},
         {"word": "club activity", "meaning": "동아리 활동", "example": "I did club activities after class."},
         {"word": "get in trouble", "meaning": "혼나다, 문제가 생기다", "example": "We got in trouble for talking."},
         {"word": "classmate", "meaning": "반 친구", "example": "I'm still close with my classmates."},
     ],
     "expressions": [
         {"phrase": "I was more of a quiet student.", "meaning": "저는 조용한 학생에 가까웠어요"},
         {"phrase": "One thing I'll never forget is ...", "meaning": "절대 못 잊을 한 가지는 ~예요"},
     ]},
    {"day": 35, "week": 5, "phase": 2, "topic": "Week 5 복습 — 경험 말하기 종합", "type": "복습",
     "question": "Tell me about the most enjoyable experience you had recently.",
     "mission": "최근 즐거웠던 경험을 배경→사건→결과→느낌 4단계 구조로 90초 말하기",
     "vocab": [
         {"word": "the other day", "meaning": "며칠 전에", "example": "The other day, I met a friend."},
         {"word": "turn out", "meaning": "결국 ~로 판명되다", "example": "It turned out great."},
         {"word": "luckily", "meaning": "운 좋게도", "example": "Luckily, the weather was perfect."},
         {"word": "at first", "meaning": "처음에는", "example": "At first, I was nervous."},
         {"word": "in the end", "meaning": "결국에는", "example": "In the end, it was worth it."},
     ],
     "expressions": [
         {"phrase": "Let me tell you what happened.", "meaning": "무슨 일이 있었는지 말씀드릴게요"},
         {"phrase": "It was one of the best days I've had.", "meaning": "제 인생 최고의 날 중 하나였어요"},
     ]},

    # ═══════════ Week 6 — 비교와 변화 (IM 핵심) ═══════════
    {"day": 36, "week": 6, "phase": 2, "topic": "과거와 현재의 나", "type": "비교",
     "question": "How have you changed over the years? Compare yourself now to when you were younger.",
     "mission": "과거의 나 vs 지금의 나를 2가지 측면에서 비교하기 (used to vs now)",
     "vocab": [
         {"word": "compared to", "meaning": "~와 비교하면", "example": "Compared to before, I'm calmer."},
         {"word": "whereas", "meaning": "반면에", "example": "I was shy, whereas now I'm outgoing."},
         {"word": "mature", "meaning": "성숙한", "example": "I've become more mature."},
         {"word": "confident", "meaning": "자신감 있는", "example": "I'm more confident now."},
         {"word": "gradually", "meaning": "점차", "example": "I gradually changed."},
     ],
     "expressions": [
         {"phrase": "I used to be ..., but now I'm ...", "meaning": "예전엔 ~했지만 지금은 ~해요"},
         {"phrase": "The biggest change is that ...", "meaning": "가장 큰 변화는 ~라는 거예요"},
     ]},
    {"day": 37, "week": 6, "phase": 2, "topic": "우리 동네의 변화", "type": "비교",
     "question": "How has your neighborhood changed over the years?",
     "mission": "동네의 과거 모습과 현재를 비교하고 변화에 대한 내 생각 말하기",
     "vocab": [
         {"word": "used to be", "meaning": "예전에는 ~였다", "example": "There used to be a small market."},
         {"word": "torn down", "meaning": "철거된", "example": "The old building was torn down."},
         {"word": "high-rise", "meaning": "고층 건물", "example": "High-rise apartments went up."},
         {"word": "development", "meaning": "개발", "example": "There's been a lot of development."},
         {"word": "dramatically", "meaning": "극적으로", "example": "It has changed dramatically."},
     ],
     "expressions": [
         {"phrase": "Back then, it was much quieter.", "meaning": "그때는 훨씬 조용했어요"},
         {"phrase": "These days, it's completely different.", "meaning": "요즘은 완전히 달라졌어요"},
     ]},
    {"day": 38, "week": 6, "phase": 2, "topic": "기술의 변화 (핸드폰)", "type": "비교",
     "question": "How have cell phones changed since you were young? Compare phones in the past and now.",
     "mission": "옛날 핸드폰 vs 요즘 스마트폰을 기능 중심으로 비교하기",
     "vocab": [
         {"word": "device", "meaning": "기기", "example": "Phones are powerful devices now."},
         {"word": "feature", "meaning": "기능", "example": "New phones have many features."},
         {"word": "flip phone", "meaning": "폴더폰", "example": "I had a flip phone in school."},
         {"word": "rely on", "meaning": "~에 의존하다", "example": "We rely on our phones for everything."},
         {"word": "advance", "meaning": "발전(하다)", "example": "Technology has advanced so fast."},
     ],
     "expressions": [
         {"phrase": "Back in the day, phones were just for calls.", "meaning": "옛날엔 폰은 전화용일 뿐이었죠"},
         {"phrase": "Nowadays, we do everything on our phones.", "meaning": "요즘은 폰으로 다 해요"},
     ]},
    {"day": 39, "week": 6, "phase": 2, "topic": "과거와 현재의 음악", "type": "비교",
     "question": "How is the music people listen to today different from the music in the past?",
     "mission": "과거 음악과 요즘 음악을 듣는 방식/스타일 측면에서 비교하기",
     "vocab": [
         {"word": "streaming", "meaning": "스트리밍", "example": "Everyone uses streaming services now."},
         {"word": "physical album", "meaning": "실물 앨범", "example": "People used to buy physical albums."},
         {"word": "trend", "meaning": "유행", "example": "Music trends change fast."},
         {"word": "access", "meaning": "접근(하다)", "example": "We can access any song instantly."},
         {"word": "generation", "meaning": "세대", "example": "Each generation has its own music."},
     ],
     "expressions": [
         {"phrase": "In the past, people had to buy CDs.", "meaning": "옛날엔 CD를 사야 했어요"},
         {"phrase": "Now, everything is just one tap away.", "meaning": "이제는 탭 한 번이면 다 돼요"},
     ]},
    {"day": 40, "week": 6, "phase": 2, "topic": "예전 집 vs 지금 집", "type": "비교",
     "question": "Compare your current home with a place you lived in before. How are they different?",
     "mission": "예전 집과 지금 집을 크기/위치/분위기로 비교하고 어디가 더 좋은지 말하기",
     "vocab": [
         {"word": "previous", "meaning": "이전의", "example": "My previous house was smaller."},
         {"word": "move in", "meaning": "이사 오다", "example": "I moved in two years ago."},
         {"word": "location", "meaning": "위치", "example": "The location is much better now."},
         {"word": "noisy", "meaning": "시끄러운", "example": "My old place was noisy."},
         {"word": "overall", "meaning": "전반적으로", "example": "Overall, I prefer my current place."},
     ],
     "expressions": [
         {"phrase": "My old place was ..., while my current place is ...", "meaning": "예전 집은 ~였고, 지금 집은 ~예요"},
         {"phrase": "It's a huge upgrade.", "meaning": "엄청난 업그레이드죠"},
     ]},
    {"day": 41, "week": 6, "phase": 2, "topic": "패션의 변화", "type": "비교",
     "question": "How has fashion changed over the years in your country?",
     "mission": "과거 유행과 요즘 패션 트렌드를 비교하고 내 스타일 변화도 말하기",
     "vocab": [
         {"word": "fashionable", "meaning": "유행하는", "example": "That style was fashionable then."},
         {"word": "outfit", "meaning": "옷차림", "example": "I like simple outfits."},
         {"word": "come back in style", "meaning": "다시 유행하다", "example": "Retro looks came back in style."},
         {"word": "casual", "meaning": "캐주얼한", "example": "People dress more casual now."},
         {"word": "individuality", "meaning": "개성", "example": "Fashion shows individuality these days."},
     ],
     "expressions": [
         {"phrase": "Trends come and go.", "meaning": "유행은 돌고 돌아요"},
         {"phrase": "People care more about comfort now.", "meaning": "요즘 사람들은 편안함을 더 중시해요"},
     ]},
    {"day": 42, "week": 6, "phase": 2, "topic": "Week 6 복습 — 비교 표현 종합", "type": "복습",
     "question": "Tell me about how your life today is different from your life five years ago.",
     "mission": "5년 전 vs 지금의 삶을 3가지 측면(일/취미/생각)에서 비교해 2분 말하기",
     "vocab": [
         {"word": "significantly", "meaning": "상당히", "example": "My life changed significantly."},
         {"word": "priority", "meaning": "우선순위", "example": "My priorities have changed."},
         {"word": "appreciate", "meaning": "감사하다, 소중히 여기다", "example": "I appreciate small things now."},
         {"word": "balance", "meaning": "균형", "example": "I have a better work-life balance."},
         {"word": "perspective", "meaning": "관점", "example": "My perspective has shifted."},
     ],
     "expressions": [
         {"phrase": "Five years ago, I never would have imagined ...", "meaning": "5년 전엔 ~은 상상도 못 했어요"},
         {"phrase": "If anything, I'm happier now.", "meaning": "오히려 지금이 더 행복해요"},
     ]},

    # ═══════════ Week 7 — 미래 계획 + 돌발주제 기초 ═══════════
    {"day": 43, "week": 7, "phase": 2, "topic": "이번 주말 계획", "type": "미래계획",
     "question": "What are your plans for this weekend?",
     "mission": "주말 계획을 be going to / planning to 사용해 말하기",
     "vocab": [
         {"word": "be going to", "meaning": "~할 예정이다", "example": "I'm going to meet friends."},
         {"word": "plan to", "meaning": "~할 계획이다", "example": "I plan to clean my house."},
         {"word": "probably", "meaning": "아마도", "example": "I'll probably stay home Sunday."},
         {"word": "if everything goes well", "meaning": "일이 잘 풀리면", "example": "If everything goes well, we'll go hiking."},
         {"word": "look forward to", "meaning": "기대하다", "example": "I'm looking forward to it."},
     ],
     "expressions": [
         {"phrase": "I'm thinking of trying that new restaurant.", "meaning": "그 새 식당에 가볼까 생각 중이에요"},
         {"phrase": "Nothing is set in stone yet.", "meaning": "아직 확정된 건 없어요"},
     ]},
    {"day": 44, "week": 7, "phase": 2, "topic": "휴가 계획", "type": "미래계획",
     "question": "Do you have any vacation plans? Where would you like to go?",
     "mission": "가고 싶은 휴가지와 거기서 하고 싶은 것 3가지 말하기",
     "vocab": [
         {"word": "take time off", "meaning": "휴가를 내다", "example": "I'll take time off in August."},
         {"word": "destination", "meaning": "목적지", "example": "My dream destination is Hawaii."},
         {"word": "can't wait to", "meaning": "빨리 ~하고 싶다", "example": "I can't wait to go."},
         {"word": "try out", "meaning": "시도해 보다", "example": "I want to try out surfing."},
         {"word": "recharge", "meaning": "재충전하다", "example": "I need to recharge."},
     ],
     "expressions": [
         {"phrase": "If I get the chance, I'd love to ...", "meaning": "기회가 되면 꼭 ~하고 싶어요"},
         {"phrase": "It's been on my bucket list for years.", "meaning": "몇 년째 버킷리스트에 있어요"},
     ]},
    {"day": 45, "week": 7, "phase": 2, "topic": "새해 목표/자기계발", "type": "미래계획",
     "question": "What goals do you have for yourself? What would you like to achieve?",
     "mission": "올해 목표 2가지와 그것을 이루기 위한 구체적 계획 말하기",
     "vocab": [
         {"word": "goal", "meaning": "목표", "example": "My goal is to speak English fluently."},
         {"word": "achieve", "meaning": "달성하다", "example": "I want to achieve it this year."},
         {"word": "improve", "meaning": "향상시키다", "example": "I'm trying to improve my skills."},
         {"word": "consistent", "meaning": "꾸준한", "example": "Being consistent is the key."},
         {"word": "step by step", "meaning": "차근차근", "example": "I'm taking it step by step."},
     ],
     "expressions": [
         {"phrase": "I've set a goal to ...", "meaning": "~하겠다는 목표를 세웠어요"},
         {"phrase": "Slow and steady wins the race.", "meaning": "천천히 꾸준히 하는 게 이기는 거죠"},
     ]},
    {"day": 46, "week": 7, "phase": 2, "topic": "돌발: 날씨/계절", "type": "돌발",
     "question": "Tell me about the seasons in your country. Which season do you like the most?",
     "mission": "우리나라 사계절 특징 + 좋아하는 계절과 이유 말하기",
     "vocab": [
         {"word": "distinct", "meaning": "뚜렷한", "example": "Korea has four distinct seasons."},
         {"word": "humid", "meaning": "습한", "example": "Summers are hot and humid."},
         {"word": "freezing", "meaning": "몹시 추운", "example": "Winters are freezing."},
         {"word": "mild", "meaning": "온화한", "example": "Spring weather is mild."},
         {"word": "foliage", "meaning": "단풍", "example": "The fall foliage is beautiful."},
     ],
     "expressions": [
         {"phrase": "My favorite season is fall, hands down.", "meaning": "제가 제일 좋아하는 계절은 단연 가을이에요"},
         {"phrase": "The weather is perfect for outdoor activities.", "meaning": "야외 활동하기 딱 좋은 날씨예요"},
     ]},
    {"day": 47, "week": 7, "phase": 2, "topic": "돌발: 교통수단", "type": "돌발",
     "question": "Tell me about the transportation system in your country. How do people get around?",
     "mission": "우리나라 대중교통의 종류와 장점, 내가 주로 쓰는 수단 말하기",
     "vocab": [
         {"word": "efficient", "meaning": "효율적인", "example": "The subway system is efficient."},
         {"word": "fare", "meaning": "요금", "example": "The fare is quite cheap."},
         {"word": "route", "meaning": "노선", "example": "There are many bus routes."},
         {"word": "punctual", "meaning": "시간을 지키는", "example": "Trains are usually punctual."},
         {"word": "traffic jam", "meaning": "교통 체증", "example": "Traffic jams are common downtown."},
     ],
     "expressions": [
         {"phrase": "Public transportation is really well-developed here.", "meaning": "여긴 대중교통이 정말 잘 되어 있어요"},
         {"phrase": "You can get almost anywhere by subway.", "meaning": "지하철로 거의 어디든 갈 수 있어요"},
     ]},
    {"day": 48, "week": 7, "phase": 2, "topic": "돌발: 재활용/환경", "type": "돌발",
     "question": "Tell me about recycling in your country. How do people recycle?",
     "mission": "우리나라 재활용 방식(분리수거)과 내가 실천하는 것 말하기",
     "vocab": [
         {"word": "recycle", "meaning": "재활용하다", "example": "We recycle almost everything."},
         {"word": "separate", "meaning": "분리하다", "example": "We separate trash by type."},
         {"word": "plastic waste", "meaning": "플라스틱 쓰레기", "example": "Plastic waste is a big issue."},
         {"word": "designated", "meaning": "지정된", "example": "There are designated bins."},
         {"word": "eco-friendly", "meaning": "친환경적인", "example": "I try to be eco-friendly."},
     ],
     "expressions": [
         {"phrase": "Recycling is mandatory in Korea.", "meaning": "한국에서 분리수거는 의무예요"},
         {"phrase": "It's a small thing, but it makes a difference.", "meaning": "작은 일이지만 변화를 만들죠"},
     ]},
    {"day": 49, "week": 7, "phase": 2, "topic": "Week 7 복습 — 미래+돌발 종합", "type": "복습",
     "question": "Describe your plans for your next vacation and how the weather might affect them.",
     "mission": "휴가 계획 + 날씨 변수까지 엮어서 90초 말하기 (미래시제+조건문)",
     "vocab": [
         {"word": "depending on", "meaning": "~에 따라", "example": "Depending on the weather, we may change plans."},
         {"word": "backup plan", "meaning": "대비책", "example": "I always have a backup plan."},
         {"word": "forecast", "meaning": "일기예보", "example": "The forecast says rain."},
         {"word": "indoor", "meaning": "실내의", "example": "We'll do indoor activities instead."},
         {"word": "flexible", "meaning": "유연한", "example": "I like to keep my plans flexible."},
     ],
     "expressions": [
         {"phrase": "If it rains, we'll just ...", "meaning": "비가 오면 그냥 ~할 거예요"},
         {"phrase": "Either way, it'll be fun.", "meaning": "어느 쪽이든 재미있을 거예요"},
     ]},

    # ═══════════ Week 8 — 돌발주제 확장 ═══════════
    {"day": 50, "week": 8, "phase": 2, "topic": "돌발: 은행", "type": "돌발",
     "question": "Tell me about the banks in your country. What do people usually do there?",
     "mission": "은행에서 하는 일과 요즘 모바일뱅킹 이용 방식 말하기",
     "vocab": [
         {"word": "account", "meaning": "계좌", "example": "I opened a bank account."},
         {"word": "withdraw", "meaning": "출금하다", "example": "I withdraw cash from ATMs."},
         {"word": "deposit", "meaning": "입금(하다)", "example": "I deposit money every month."},
         {"word": "transfer money", "meaning": "송금하다", "example": "I transfer money using an app."},
         {"word": "banking app", "meaning": "뱅킹 앱", "example": "Banking apps are so convenient."},
     ],
     "expressions": [
         {"phrase": "I rarely visit banks in person these days.", "meaning": "요즘은 은행에 직접 갈 일이 거의 없어요"},
         {"phrase": "Everything can be done on my phone.", "meaning": "모든 게 핸드폰으로 가능해요"},
     ]},
    {"day": 51, "week": 8, "phase": 2, "topic": "돌발: 병원/건강", "type": "돌발",
     "question": "Tell me about the last time you went to a hospital or clinic. What happened?",
     "mission": "최근 병원 방문 경험을 과거시제로 말하기 (증상→진료→결과)",
     "vocab": [
         {"word": "symptom", "meaning": "증상", "example": "I had cold symptoms."},
         {"word": "see a doctor", "meaning": "진료를 받다", "example": "I went to see a doctor."},
         {"word": "prescription", "meaning": "처방전", "example": "The doctor gave me a prescription."},
         {"word": "get better", "meaning": "나아지다", "example": "I got better in a few days."},
         {"word": "checkup", "meaning": "건강검진", "example": "I get a checkup every year."},
     ],
     "expressions": [
         {"phrase": "I came down with a bad cold.", "meaning": "독한 감기에 걸렸어요"},
         {"phrase": "Thankfully, it was nothing serious.", "meaning": "다행히 심각한 건 아니었어요"},
     ]},
    {"day": 52, "week": 8, "phase": 2, "topic": "돌발: 호텔", "type": "돌발",
     "question": "Tell me about hotels in your country. What are they like?",
     "mission": "우리나라 숙박시설 종류와 내가 묵었던 호텔 경험 말하기",
     "vocab": [
         {"word": "accommodation", "meaning": "숙박시설", "example": "There are many types of accommodation."},
         {"word": "check in", "meaning": "체크인하다", "example": "We checked in at 3 pm."},
         {"word": "amenities", "meaning": "편의시설", "example": "The hotel has great amenities."},
         {"word": "front desk", "meaning": "프런트", "example": "I asked the front desk for help."},
         {"word": "cost an arm and a leg", "meaning": "매우 비싸다", "example": "Nice hotels cost an arm and a leg."},
     ],
     "expressions": [
         {"phrase": "The room had an amazing view.", "meaning": "방에서 보이는 전망이 끝내줬어요"},
         {"phrase": "It was worth every penny.", "meaning": "돈이 하나도 안 아까웠어요"},
     ]},
    {"day": 53, "week": 8, "phase": 2, "topic": "돌발: 도서관", "type": "돌발",
     "question": "Tell me about the libraries in your area. What do people do there?",
     "mission": "동네 도서관의 모습과 사람들이 하는 활동, 내 이용 경험 말하기",
     "vocab": [
         {"word": "borrow", "meaning": "빌리다", "example": "I borrow books every month."},
         {"word": "quiet", "meaning": "조용한", "example": "The library is always quiet."},
         {"word": "study room", "meaning": "열람실", "example": "Students use the study rooms."},
         {"word": "shelf", "meaning": "책장, 선반", "example": "The shelves are full of books."},
         {"word": "concentrate", "meaning": "집중하다", "example": "I can concentrate well there."},
     ],
     "expressions": [
         {"phrase": "It's a great place to focus.", "meaning": "집중하기 좋은 곳이에요"},
         {"phrase": "You can borrow up to five books at a time.", "meaning": "한 번에 다섯 권까지 빌릴 수 있어요"},
     ]},
    {"day": 54, "week": 8, "phase": 2, "topic": "돌발: 명절/휴일", "type": "돌발",
     "question": "Tell me about a major holiday in your country. How do people celebrate it?",
     "mission": "설날 또는 추석에 하는 일과 우리 가족의 명절 모습 말하기",
     "vocab": [
         {"word": "national holiday", "meaning": "국경일, 명절", "example": "Chuseok is a national holiday."},
         {"word": "celebrate", "meaning": "기념하다", "example": "We celebrate with family."},
         {"word": "tradition", "meaning": "전통", "example": "It's an old tradition."},
         {"word": "gather", "meaning": "모이다", "example": "Families gather together."},
         {"word": "traditional food", "meaning": "전통 음식", "example": "We eat traditional food like tteokguk."},
     ],
     "expressions": [
         {"phrase": "It's similar to Thanksgiving in the US.", "meaning": "미국의 추수감사절과 비슷해요"},
         {"phrase": "The whole family gets together.", "meaning": "온 가족이 다 모여요"},
     ]},
    {"day": 55, "week": 8, "phase": 2, "topic": "돌발: 약속", "type": "돌발",
     "question": "How do you usually make appointments or plans with friends?",
     "mission": "친구와 약속 잡는 방식(연락 수단, 장소 정하기)과 최근 약속 경험 말하기",
     "vocab": [
         {"word": "make plans", "meaning": "약속을 잡다", "example": "We made plans for Saturday."},
         {"word": "group chat", "meaning": "단체 채팅방", "example": "We decide in our group chat."},
         {"word": "available", "meaning": "시간이 되는", "example": "I'm available after 6."},
         {"word": "confirm", "meaning": "확정하다", "example": "I confirmed the time with her."},
         {"word": "last minute", "meaning": "막판에", "example": "He canceled at the last minute."},
     ],
     "expressions": [
         {"phrase": "We usually decide everything over KakaoTalk.", "meaning": "우린 보통 카톡으로 다 정해요"},
         {"phrase": "Something came up, so we rescheduled.", "meaning": "일이 생겨서 일정을 다시 잡았어요"},
     ]},
    {"day": 56, "week": 8, "phase": 2, "topic": "Phase 2 마무리 점검", "type": "복습",
     "question": "Tell me about a memorable holiday you spent with your family. What did you do, and why was it special?",
     "mission": "Phase 2 종합: 명절 경험을 과거시제 + 비교 + 감정 표현 섞어 2분 말하기",
     "vocab": [
         {"word": "get-together", "meaning": "모임", "example": "We had a big family get-together."},
         {"word": "reminisce", "meaning": "추억을 이야기하다", "example": "We reminisced about old times."},
         {"word": "feast", "meaning": "잔치, 진수성찬", "example": "We had a huge feast."},
         {"word": "meaningful", "meaning": "의미 있는", "example": "It was a meaningful day."},
         {"word": "cherish", "meaning": "소중히 여기다", "example": "I cherish those memories."},
     ],
     "expressions": [
         {"phrase": "It reminded me of how important family is.", "meaning": "가족이 얼마나 소중한지 다시 느꼈어요"},
         {"phrase": "We laughed until our stomachs hurt.", "meaning": "배가 아플 때까지 웃었어요"},
     ]},
    # ═══════════ Phase 3: Week 9 — 롤플레이 기초 (11-12번 유형) ═══════════
    {"day": 57, "week": 9, "phase": 3, "topic": "롤플레이: 영화표 문의", "type": "롤플레이",
     "question": "I'd like to give you a situation. You want to see a movie with a friend. Call the movie theater and ask three or four questions about the movie and showtimes.",
     "mission": "영화관에 전화해서 상영 시간, 좌석, 가격 등 질문 3-4개 하기",
     "vocab": [
         {"word": "showtime", "meaning": "상영 시간", "example": "What are the showtimes today?"},
         {"word": "available seat", "meaning": "남은 좌석", "example": "Are there any available seats?"},
         {"word": "in advance", "meaning": "미리", "example": "Can I book tickets in advance?"},
         {"word": "screening", "meaning": "상영", "example": "Is there a late-night screening?"},
         {"word": "discount", "meaning": "할인", "example": "Do you offer any discounts?"},
     ],
     "expressions": [
         {"phrase": "Hi, I'm calling to ask about ...", "meaning": "안녕하세요, ~에 대해 문의드리려고 전화했어요"},
         {"phrase": "Could you tell me what time the movie starts?", "meaning": "영화가 몇 시에 시작하는지 알려주시겠어요?"},
     ]},
    {"day": 58, "week": 9, "phase": 3, "topic": "롤플레이: 여행사 문의", "type": "롤플레이",
     "question": "You are planning a trip. Call a travel agency and ask three or four questions about a tour package.",
     "mission": "여행사에 전화해서 패키지 일정, 가격, 포함 사항 질문하기",
     "vocab": [
         {"word": "tour package", "meaning": "패키지 여행", "example": "I'm interested in your tour package."},
         {"word": "include", "meaning": "포함하다", "example": "Does the price include meals?"},
         {"word": "departure", "meaning": "출발", "example": "When is the departure date?"},
         {"word": "guide", "meaning": "가이드", "example": "Is there an English-speaking guide?"},
         {"word": "cancellation policy", "meaning": "취소 규정", "example": "What's your cancellation policy?"},
     ],
     "expressions": [
         {"phrase": "I'd like to get some information about ...", "meaning": "~에 대한 정보를 좀 얻고 싶어요"},
         {"phrase": "One more thing — how much does it cost?", "meaning": "하나 더요 — 비용이 얼마인가요?"},
     ]},
    {"day": 59, "week": 9, "phase": 3, "topic": "롤플레이: 식당 예약", "type": "롤플레이",
     "question": "You want to have dinner at a restaurant with your friends. Call the restaurant and make a reservation, asking a few questions.",
     "mission": "식당에 전화해 인원/시간 예약하고 주차, 메뉴 등 추가 질문하기",
     "vocab": [
         {"word": "reservation", "meaning": "예약", "example": "I'd like to make a reservation."},
         {"word": "party of four", "meaning": "4인 일행", "example": "A table for a party of four, please."},
         {"word": "private room", "meaning": "룸, 개별 공간", "example": "Do you have a private room?"},
         {"word": "parking", "meaning": "주차", "example": "Is parking available?"},
         {"word": "vegetarian option", "meaning": "채식 메뉴", "example": "Do you have vegetarian options?"},
     ],
     "expressions": [
         {"phrase": "I'd like to book a table for four at 7.", "meaning": "7시에 4명 테이블 예약하고 싶어요"},
         {"phrase": "Would it be possible to sit by the window?", "meaning": "창가 자리에 앉을 수 있을까요?"},
     ]},
    {"day": 60, "week": 9, "phase": 3, "topic": "롤플레이: 친구에게 제안하기", "type": "롤플레이",
     "question": "You want to go to a concert with your friend. Call your friend, explain the situation, and suggest going together.",
     "mission": "친구에게 전화해서 콘서트 정보 알려주고 같이 가자고 제안하기",
     "vocab": [
         {"word": "suggest", "meaning": "제안하다", "example": "I suggest we go together."},
         {"word": "come out", "meaning": "(티켓 등이) 나오다", "example": "Tickets just came out."},
         {"word": "how about", "meaning": "~는 어때?", "example": "How about this Saturday?"},
         {"word": "pick up", "meaning": "데리러 가다", "example": "I can pick you up at 6."},
         {"word": "split", "meaning": "나누다", "example": "Let's split the ticket cost."},
     ],
     "expressions": [
         {"phrase": "Guess what? Our favorite band is coming to town!", "meaning": "있잖아! 우리가 좋아하는 밴드가 온대!"},
         {"phrase": "Are you in?", "meaning": "같이 갈래? (낄래?)"},
     ]},
    {"day": 61, "week": 9, "phase": 3, "topic": "롤플레이: 상품 구매 문의", "type": "롤플레이",
     "question": "You want to buy a new phone. Go to the store and ask the salesperson three or four questions about the phone.",
     "mission": "매장 직원에게 제품 기능, 가격, 할부, 보증 질문하기",
     "vocab": [
         {"word": "warranty", "meaning": "보증", "example": "How long is the warranty?"},
         {"word": "installment", "meaning": "할부", "example": "Can I pay in installments?"},
         {"word": "storage", "meaning": "저장 용량", "example": "How much storage does it have?"},
         {"word": "trade in", "meaning": "보상 판매하다", "example": "Can I trade in my old phone?"},
         {"word": "in stock", "meaning": "재고가 있는", "example": "Is this model in stock?"},
     ],
     "expressions": [
         {"phrase": "I'm looking for a new phone. Could you recommend one?", "meaning": "새 폰을 찾고 있는데 추천해 주시겠어요?"},
         {"phrase": "What's the difference between this one and that one?", "meaning": "이거랑 저거는 뭐가 다른가요?"},
     ]},
    {"day": 62, "week": 9, "phase": 3, "topic": "롤플레이: 헬스장 등록 문의", "type": "롤플레이",
     "question": "You want to join a gym. Call the gym and ask three or four questions about membership.",
     "mission": "헬스장에 전화해서 회원권 종류, 가격, 운영시간, 시설 질문하기",
     "vocab": [
         {"word": "membership", "meaning": "회원권", "example": "How much is a monthly membership?"},
         {"word": "operating hours", "meaning": "운영 시간", "example": "What are your operating hours?"},
         {"word": "personal training", "meaning": "PT, 개인 트레이닝", "example": "Do you offer personal training?"},
         {"word": "locker", "meaning": "사물함", "example": "Are lockers included?"},
         {"word": "sign up", "meaning": "등록하다", "example": "I'd like to sign up."},
     ],
     "expressions": [
         {"phrase": "Is there a discount for a yearly membership?", "meaning": "연간 회원권은 할인이 있나요?"},
         {"phrase": "Can I take a look around first?", "meaning": "먼저 둘러봐도 될까요?"},
     ]},
    {"day": 63, "week": 9, "phase": 3, "topic": "Week 9 복습 — 질문하기 종합", "type": "복습",
     "question": "You want to take an English class. Call the language school and ask several questions about the classes.",
     "mission": "이번 주 배운 질문 패턴으로 학원에 문의 전화하기 (질문 5개)",
     "vocab": [
         {"word": "tuition", "meaning": "수강료", "example": "How much is the tuition?"},
         {"word": "level test", "meaning": "레벨 테스트", "example": "Is there a level test?"},
         {"word": "schedule", "meaning": "시간표", "example": "What's the class schedule?"},
         {"word": "trial class", "meaning": "체험 수업", "example": "Can I take a trial class?"},
         {"word": "enroll", "meaning": "등록하다", "example": "When can I enroll?"},
     ],
     "expressions": [
         {"phrase": "I have a few questions about your classes.", "meaning": "수업에 대해 몇 가지 질문이 있어요"},
         {"phrase": "That sounds great. I'll think about it and call back.", "meaning": "좋네요. 생각해 보고 다시 전화드릴게요"},
     ]},

    # ═══════════ Week 10 — 문제 해결 롤플레이 (13번 유형) ═══════════
    {"day": 64, "week": 10, "phase": 3, "topic": "롤플레이: 티켓 문제 해결", "type": "롤플레이",
     "question": "I'm sorry, but there is a problem. You bought concert tickets, but you just found out you can't go. Call your friend, explain the situation, and offer two or three alternatives.",
     "mission": "콘서트에 못 가게 된 상황 설명 + 대안 2-3개 제시하기",
     "vocab": [
         {"word": "unfortunately", "meaning": "안타깝게도", "example": "Unfortunately, I can't make it."},
         {"word": "come up", "meaning": "(일이) 생기다", "example": "Something urgent came up."},
         {"word": "alternative", "meaning": "대안", "example": "Let me offer some alternatives."},
         {"word": "instead", "meaning": "대신에", "example": "How about going next week instead?"},
         {"word": "make it up to", "meaning": "(잘못을) 만회하다", "example": "I'll make it up to you."},
     ],
     "expressions": [
         {"phrase": "I'm really sorry, but I can't make it.", "meaning": "정말 미안한데 못 갈 것 같아"},
         {"phrase": "Here's what we can do — either A or B.", "meaning": "이렇게 하자 — A 아니면 B"},
     ]},
    {"day": 65, "week": 10, "phase": 3, "topic": "롤플레이: 불량품 환불", "type": "롤플레이",
     "question": "You bought a product, but it doesn't work. Call the store, explain the problem, and suggest solutions.",
     "mission": "산 물건의 문제점 설명 + 환불/교환 요구하기",
     "vocab": [
         {"word": "defective", "meaning": "결함이 있는", "example": "The product is defective."},
         {"word": "refund", "meaning": "환불", "example": "I'd like a full refund."},
         {"word": "exchange", "meaning": "교환(하다)", "example": "Can I exchange it for a new one?"},
         {"word": "receipt", "meaning": "영수증", "example": "I still have the receipt."},
         {"word": "work properly", "meaning": "제대로 작동하다", "example": "It doesn't work properly."},
     ],
     "expressions": [
         {"phrase": "I purchased this yesterday, but it's not working.", "meaning": "어제 샀는데 작동이 안 돼요"},
         {"phrase": "I'd like either a refund or an exchange.", "meaning": "환불이나 교환을 원해요"},
     ]},
    {"day": 66, "week": 10, "phase": 3, "topic": "롤플레이: 약속 변경", "type": "롤플레이",
     "question": "You have an appointment with your doctor, but something came up. Call the clinic, explain your situation, and reschedule.",
     "mission": "병원 예약 변경 전화하기 (사정 설명 + 새 시간 제안 2개)",
     "vocab": [
         {"word": "reschedule", "meaning": "일정을 변경하다", "example": "I need to reschedule my appointment."},
         {"word": "conflict", "meaning": "(일정) 겹침", "example": "I have a schedule conflict."},
         {"word": "earliest", "meaning": "가장 빠른", "example": "What's the earliest available time?"},
         {"word": "work for", "meaning": "(시간이) 괜찮다", "example": "Does Friday work for you?"},
         {"word": "apologize", "meaning": "사과하다", "example": "I apologize for the short notice."},
     ],
     "expressions": [
         {"phrase": "I'm afraid I have to reschedule.", "meaning": "죄송하지만 일정을 변경해야 할 것 같아요"},
         {"phrase": "Would Thursday afternoon be possible?", "meaning": "목요일 오후 가능할까요?"},
     ]},
    {"day": 67, "week": 10, "phase": 3, "topic": "롤플레이: 렌터카 고장", "type": "롤플레이",
     "question": "You rented a car, but it broke down on the road. Call the rental company, explain the situation, and ask for solutions.",
     "mission": "렌터카 고장 상황 설명 + 해결책 요구하기 (견인, 교체 차량)",
     "vocab": [
         {"word": "break down", "meaning": "고장 나다", "example": "The car broke down on the highway."},
         {"word": "tow", "meaning": "견인하다", "example": "Can you send a tow truck?"},
         {"word": "replacement", "meaning": "교체(품)", "example": "I need a replacement car."},
         {"word": "stranded", "meaning": "발이 묶인", "example": "I'm stranded on the road."},
         {"word": "compensate", "meaning": "보상하다", "example": "Will you compensate me for this?"},
     ],
     "expressions": [
         {"phrase": "The engine suddenly stopped working.", "meaning": "엔진이 갑자기 멈췄어요"},
         {"phrase": "How soon can someone get here?", "meaning": "얼마나 빨리 사람이 올 수 있나요?"},
     ]},
    {"day": 68, "week": 10, "phase": 3, "topic": "관련 경험 말하기 (13번 후속)", "type": "과거경험",
     "question": "That's the end of the situation. Have you ever had a similar experience where something you bought had a problem? Tell me what happened.",
     "mission": "실제로 겪은 비슷한 문제 경험을 배경→문제→해결→교훈 구조로 말하기",
     "vocab": [
         {"word": "similar", "meaning": "비슷한", "example": "I had a similar experience."},
         {"word": "customer service", "meaning": "고객 센터", "example": "I called customer service."},
         {"word": "resolve", "meaning": "해결하다", "example": "The issue was resolved quickly."},
         {"word": "frustrated", "meaning": "짜증 난, 답답한", "example": "I was so frustrated."},
         {"word": "lesson", "meaning": "교훈", "example": "I learned a lesson from it."},
     ],
     "expressions": [
         {"phrase": "Actually, something similar happened to me last year.", "meaning": "사실 작년에 비슷한 일이 있었어요"},
         {"phrase": "Since then, I always check reviews first.", "meaning": "그 후로는 항상 리뷰부터 확인해요"},
     ]},
    {"day": 69, "week": 10, "phase": 3, "topic": "롤플레이+경험 콤보 연습", "type": "롤플레이",
     "question": "Your friend borrowed your laptop and broke it. Call your friend and discuss how to solve this. Then tell me about a time when you lent something and had a problem.",
     "mission": "롤플레이(문제 논의)와 실제 경험 말하기를 연달아 연습하기",
     "vocab": [
         {"word": "lend", "meaning": "빌려주다", "example": "I lent him my laptop."},
         {"word": "accidentally", "meaning": "실수로", "example": "He accidentally dropped it."},
         {"word": "repair cost", "meaning": "수리비", "example": "Let's talk about the repair cost."},
         {"word": "fair", "meaning": "공정한", "example": "That sounds fair to me."},
         {"word": "no big deal", "meaning": "별일 아닌", "example": "Don't worry, it's no big deal."},
     ],
     "expressions": [
         {"phrase": "Accidents happen — let's figure this out together.", "meaning": "그럴 수도 있지 — 같이 해결해 보자"},
         {"phrase": "How about we split the repair cost?", "meaning": "수리비를 반씩 내는 게 어때?"},
     ]},
    {"day": 70, "week": 10, "phase": 3, "topic": "Week 10 복습 — 문제 해결 종합", "type": "복습",
     "question": "You ordered food delivery, but the wrong food arrived. Call the restaurant, explain, and solve the problem. Then tell me about a real delivery problem you've had.",
     "mission": "배달 문제 롤플레이 + 실제 경험까지 콤보로 2분 말하기",
     "vocab": [
         {"word": "order", "meaning": "주문(하다)", "example": "I ordered fried chicken."},
         {"word": "wrong item", "meaning": "잘못된 물건", "example": "I received the wrong item."},
         {"word": "missing", "meaning": "빠진, 누락된", "example": "One item is missing."},
         {"word": "redeliver", "meaning": "다시 배달하다", "example": "Can you redeliver the right one?"},
         {"word": "store credit", "meaning": "적립금, 포인트", "example": "They offered me store credit."},
     ],
     "expressions": [
         {"phrase": "I think there's been a mix-up with my order.", "meaning": "제 주문이 뒤바뀐 것 같아요"},
         {"phrase": "I'd appreciate it if you could fix this quickly.", "meaning": "빨리 해결해 주시면 감사하겠어요"},
     ]},

    # ═══════════ Week 11 — 의견 표현 (IH 도약) ═══════════
    {"day": 71, "week": 11, "phase": 3, "topic": "의견: 인터넷의 장단점", "type": "의견",
     "question": "Some people say the internet has made our lives better, while others disagree. What do you think?",
     "mission": "인터넷의 장점 2개 + 단점 1개 + 내 결론 말하기",
     "vocab": [
         {"word": "advantage", "meaning": "장점", "example": "The biggest advantage is convenience."},
         {"word": "disadvantage", "meaning": "단점", "example": "There are some disadvantages too."},
         {"word": "instantly", "meaning": "즉시", "example": "We can find information instantly."},
         {"word": "addictive", "meaning": "중독성 있는", "example": "Social media can be addictive."},
         {"word": "on balance", "meaning": "종합적으로 보면", "example": "On balance, it's a positive thing."},
     ],
     "expressions": [
         {"phrase": "In my opinion, the pros outweigh the cons.", "meaning": "제 생각엔 장점이 단점보다 커요"},
         {"phrase": "That being said, we should use it wisely.", "meaning": "그렇긴 해도 현명하게 써야죠"},
     ]},
    {"day": 72, "week": 11, "phase": 3, "topic": "의견: 재택근무", "type": "의견",
     "question": "What do you think about working from home? Is it better than working in an office?",
     "mission": "재택근무 vs 사무실 근무 비교 + 내 선호와 이유 말하기",
     "vocab": [
         {"word": "work from home", "meaning": "재택근무하다", "example": "I work from home twice a week."},
         {"word": "productivity", "meaning": "생산성", "example": "My productivity is higher at home."},
         {"word": "distraction", "meaning": "방해 요소", "example": "There are fewer distractions."},
         {"word": "face-to-face", "meaning": "대면의", "example": "Face-to-face meetings are important."},
         {"word": "commute time", "meaning": "통근 시간", "example": "I save two hours of commute time."},
     ],
     "expressions": [
         {"phrase": "Personally, I prefer a hybrid style.", "meaning": "개인적으로 저는 하이브리드 방식을 선호해요"},
         {"phrase": "It really depends on the type of work.", "meaning": "일의 종류에 따라 다르죠"},
     ]},
    {"day": 73, "week": 11, "phase": 3, "topic": "의견: 건강 관리", "type": "의견",
     "question": "Why do you think people are so interested in health these days? What do people do to stay healthy?",
     "mission": "요즘 사람들의 건강 관심 이유 + 건강 관리 방법 + 내 생각 말하기",
     "vocab": [
         {"word": "health-conscious", "meaning": "건강을 신경 쓰는", "example": "People are more health-conscious now."},
         {"word": "well-being", "meaning": "웰빙, 행복", "example": "Mental well-being matters too."},
         {"word": "balanced diet", "meaning": "균형 잡힌 식단", "example": "A balanced diet is essential."},
         {"word": "regularly", "meaning": "규칙적으로", "example": "Exercising regularly is important."},
         {"word": "prevention", "meaning": "예방", "example": "Prevention is better than cure."},
     ],
     "expressions": [
         {"phrase": "I think it's because people live longer now.", "meaning": "사람들이 더 오래 살게 돼서 그런 것 같아요"},
         {"phrase": "Health is the foundation of everything.", "meaning": "건강이 모든 것의 기본이죠"},
     ]},
    {"day": 74, "week": 11, "phase": 3, "topic": "이슈: 환경 문제", "type": "의견",
     "question": "What environmental problems is your country facing? What should be done about them?",
     "mission": "우리나라 환경 문제 1-2개 + 해결 방안 + 개인이 할 수 있는 일 말하기",
     "vocab": [
         {"word": "air pollution", "meaning": "대기 오염", "example": "Air pollution is a serious issue."},
         {"word": "fine dust", "meaning": "미세먼지", "example": "Fine dust levels are high in spring."},
         {"word": "government", "meaning": "정부", "example": "The government should act."},
         {"word": "reduce", "meaning": "줄이다", "example": "We need to reduce plastic use."},
         {"word": "awareness", "meaning": "인식", "example": "Public awareness is growing."},
     ],
     "expressions": [
         {"phrase": "It's a problem we can't ignore anymore.", "meaning": "더 이상 무시할 수 없는 문제예요"},
         {"phrase": "Every small effort counts.", "meaning": "작은 노력 하나하나가 중요해요"},
     ]},
    {"day": 75, "week": 11, "phase": 3, "topic": "이슈: 기술과 삶", "type": "의견",
     "question": "How has technology changed the way people live? Give me some specific examples.",
     "mission": "기술이 바꾼 삶의 모습 2-3가지를 구체적 예시와 함께 말하기",
     "vocab": [
         {"word": "revolutionize", "meaning": "혁신하다", "example": "Smartphones revolutionized our lives."},
         {"word": "artificial intelligence", "meaning": "인공지능", "example": "AI is everywhere now."},
         {"word": "convenience", "meaning": "편리함", "example": "Technology brings convenience."},
         {"word": "depend on", "meaning": "의존하다", "example": "We depend on technology too much."},
         {"word": "double-edged sword", "meaning": "양날의 검", "example": "Technology is a double-edged sword."},
     ],
     "expressions": [
         {"phrase": "Take food delivery apps, for example.", "meaning": "배달 앱을 예로 들어볼게요"},
         {"phrase": "It's hard to imagine life without it.", "meaning": "그것 없는 삶은 상상하기 어려워요"},
     ]},
    {"day": 76, "week": 11, "phase": 3, "topic": "내 의견 방어하기", "type": "의견",
     "question": "You said you prefer traveling alone. Why is that? Convince me that traveling alone is better.",
     "mission": "내 의견을 근거 3개로 방어하기 (First, Second, Most importantly)",
     "vocab": [
         {"word": "convince", "meaning": "설득하다", "example": "Let me convince you."},
         {"word": "freedom", "meaning": "자유", "example": "You have total freedom."},
         {"word": "at your own pace", "meaning": "자기 페이스대로", "example": "You can travel at your own pace."},
         {"word": "compromise", "meaning": "타협하다", "example": "You don't have to compromise."},
         {"word": "self-discovery", "meaning": "자아 발견", "example": "It's a journey of self-discovery."},
     ],
     "expressions": [
         {"phrase": "First of all, ... Second, ... And most importantly, ...", "meaning": "첫째로..., 둘째로..., 그리고 가장 중요한 건..."},
         {"phrase": "That's exactly why I believe ...", "meaning": "바로 그래서 저는 ~라고 믿어요"},
     ]},
    {"day": 77, "week": 11, "phase": 3, "topic": "Week 11 복습 — 의견 종합", "type": "복습",
     "question": "Some people think social media does more harm than good. Do you agree or disagree? Support your opinion.",
     "mission": "SNS 찬반 의견을 입장→근거 2개→반론 인정→결론 구조로 2분 말하기",
     "vocab": [
         {"word": "do more harm than good", "meaning": "득보다 실이 많다", "example": "Some say it does more harm than good."},
         {"word": "agree with", "meaning": "~에 동의하다", "example": "I partially agree with that."},
         {"word": "connect", "meaning": "연결하다", "example": "It connects people worldwide."},
         {"word": "misinformation", "meaning": "잘못된 정보", "example": "Misinformation spreads fast."},
         {"word": "moderation", "meaning": "절제", "example": "The key is moderation."},
     ],
     "expressions": [
         {"phrase": "I see both sides, but I lean towards ...", "meaning": "양쪽 다 이해하지만 저는 ~쪽이에요"},
         {"phrase": "At the end of the day, it's about how you use it.", "meaning": "결국은 어떻게 쓰느냐의 문제죠"},
     ]},

    # ═══════════ Week 12 — 콤보 실전 연습 ═══════════
    {"day": 78, "week": 12, "phase": 3, "topic": "콤보: 집 3연속", "type": "콤보",
     "question": "Describe your home. Then tell me about your daily routine at home. Finally, tell me about a memorable event that happened at your home.",
     "mission": "묘사→루틴→경험 3연속 콤보를 각 40초씩 이어 말하기",
     "vocab": [
         {"word": "as for", "meaning": "~에 관해서는", "example": "As for my routine, it's simple."},
         {"word": "speaking of", "meaning": "~ 얘기가 나와서 말인데", "example": "Speaking of my home, something funny happened."},
         {"word": "one time", "meaning": "한번은", "example": "One time, I locked myself out."},
         {"word": "host", "meaning": "(손님을) 초대하다", "example": "I hosted a party last year."},
         {"word": "cozy up", "meaning": "아늑하게 쉬다", "example": "I cozy up on the couch every night."},
     ],
     "expressions": [
         {"phrase": "Now, let me move on to my routine.", "meaning": "이제 제 루틴 얘기로 넘어갈게요"},
         {"phrase": "That reminds me of something that happened last year.", "meaning": "그러고 보니 작년 일이 생각나네요"},
     ]},
    {"day": 79, "week": 12, "phase": 3, "topic": "콤보: 영화 3연속", "type": "콤보",
     "question": "What kind of movies do you like? Tell me about the last movie you watched. How have movies changed compared to the past?",
     "mission": "취향→최근 경험→과거 비교 3연속 콤보 이어 말하기",
     "vocab": [
         {"word": "when it comes to", "meaning": "~에 관한 한", "example": "When it comes to movies, I love thrillers."},
         {"word": "blockbuster", "meaning": "블록버스터", "example": "I watched the new blockbuster."},
         {"word": "special effects", "meaning": "특수 효과", "example": "The special effects were amazing."},
         {"word": "back then", "meaning": "그 당시에는", "example": "Back then, effects were simple."},
         {"word": "evolve", "meaning": "진화하다", "example": "Movies have evolved a lot."},
     ],
     "expressions": [
         {"phrase": "The last movie I saw was ..., and honestly, ...", "meaning": "마지막으로 본 영화는 ~인데, 솔직히..."},
         {"phrase": "Compared to older movies, today's films are ...", "meaning": "옛날 영화에 비하면 요즘 영화는..."},
     ]},
    {"day": 80, "week": 12, "phase": 3, "topic": "콤보: 여행 3연속", "type": "콤보",
     "question": "Where do you like to travel? Describe your most memorable trip. What problems can people have while traveling?",
     "mission": "취향→기억에 남는 여행→여행 문제점 3연속 콤보 이어 말하기",
     "vocab": [
         {"word": "wander", "meaning": "돌아다니다", "example": "I love wandering around new cities."},
         {"word": "highlight", "meaning": "하이라이트, 백미", "example": "The highlight was the sunset."},
         {"word": "lost luggage", "meaning": "수하물 분실", "example": "Lost luggage is a common problem."},
         {"word": "language barrier", "meaning": "언어 장벽", "example": "The language barrier was tough."},
         {"word": "delayed", "meaning": "지연된", "example": "My flight was delayed 5 hours."},
     ],
     "expressions": [
         {"phrase": "Of all the places I've been, ... stands out.", "meaning": "가본 곳 중에 ~이 가장 기억에 남아요"},
         {"phrase": "Things don't always go as planned when traveling.", "meaning": "여행에선 계획대로 안 될 때가 많죠"},
     ]},
    {"day": 81, "week": 12, "phase": 3, "topic": "롤플레이 콤보 실전", "type": "콤보",
     "question": "You want to buy concert tickets, but the website isn't working. Call the ticket office and solve the problem. Then tell me about a time you had trouble buying something online.",
     "mission": "롤플레이(문제 해결)→관련 경험 콤보 이어 말하기",
     "vocab": [
         {"word": "error message", "meaning": "오류 메시지", "example": "I keep getting an error message."},
         {"word": "payment", "meaning": "결제", "example": "The payment won't go through."},
         {"word": "sold out", "meaning": "매진된", "example": "The tickets were sold out."},
         {"word": "alternative way", "meaning": "다른 방법", "example": "Is there an alternative way to buy?"},
         {"word": "technical issue", "meaning": "기술적 문제", "example": "It was a technical issue."},
     ],
     "expressions": [
         {"phrase": "I've been trying for an hour, but it keeps failing.", "meaning": "한 시간째 시도 중인데 계속 실패해요"},
         {"phrase": "Is there anything you can do on your end?", "meaning": "그쪽에서 해줄 수 있는 게 있나요?"},
     ]},
    {"day": 82, "week": 12, "phase": 3, "topic": "돌발 콤보 실전", "type": "콤보",
     "question": "Tell me about the weather in your country. What's your favorite season? Tell me about a time when weather ruined your plans.",
     "mission": "돌발(날씨) 묘사→선호→경험 3연속 콤보 이어 말하기",
     "vocab": [
         {"word": "ruin", "meaning": "망치다", "example": "The rain ruined our picnic."},
         {"word": "pour", "meaning": "(비가) 쏟아지다", "example": "It suddenly started pouring."},
         {"word": "soaked", "meaning": "흠뻑 젖은", "example": "We got completely soaked."},
         {"word": "call off", "meaning": "취소하다", "example": "We had to call off the trip."},
         {"word": "make the best of", "meaning": "최선을 다해 즐기다", "example": "We made the best of it anyway."},
     ],
     "expressions": [
         {"phrase": "Out of nowhere, it started raining.", "meaning": "난데없이 비가 오기 시작했어요"},
         {"phrase": "We ended up having fun indoors instead.", "meaning": "결국 실내에서 즐겁게 놀았어요"},
     ]},
    {"day": 83, "week": 12, "phase": 3, "topic": "고득점 전략: 디테일 살리기", "type": "전략",
     "question": "Tell me about your favorite cafe again — but this time, make me feel like I'm there. Use all five senses.",
     "mission": "오감(시각/청각/후각/미각/촉각) 표현을 넣어 카페 묘사 업그레이드하기",
     "vocab": [
         {"word": "aroma", "meaning": "향기", "example": "The aroma of fresh coffee fills the air."},
         {"word": "chatter", "meaning": "재잘거림, 담소", "example": "I hear the soft chatter of people."},
         {"word": "dim", "meaning": "은은한, 어둑한", "example": "The lighting is dim and warm."},
         {"word": "velvety", "meaning": "부드러운, 벨벳 같은", "example": "The latte tastes velvety."},
         {"word": "soak in", "meaning": "만끽하다", "example": "I soak in the atmosphere."},
     ],
     "expressions": [
         {"phrase": "The moment I walk in, I'm greeted by ...", "meaning": "들어서는 순간 ~이 저를 반겨요"},
         {"phrase": "It's those little details that make it special.", "meaning": "그런 작은 디테일이 특별함을 만들어요"},
     ]},
    {"day": 84, "week": 12, "phase": 3, "topic": "Week 12 복습 — 콤보 마스터", "type": "복습",
     "question": "Tell me about your hobby, a recent experience with it, and how this hobby has changed over the years.",
     "mission": "자유 주제로 3콤보(현재→경험→변화) 완주하기, 각 파트 40초 이상",
     "vocab": [
         {"word": "transition", "meaning": "전환(하다)", "example": "Let me transition to my recent experience."},
         {"word": "detail", "meaning": "세부 사항", "example": "Let me add some details."},
         {"word": "specifically", "meaning": "구체적으로", "example": "Specifically, I love morning runs."},
         {"word": "notably", "meaning": "특히, 눈에 띄게", "example": "Notably, equipment has improved."},
         {"word": "wrap up", "meaning": "마무리하다", "example": "To wrap up, it's my favorite hobby."},
     ],
     "expressions": [
         {"phrase": "Moving on to my recent experience ...", "meaning": "최근 경험으로 넘어가면..."},
         {"phrase": "Over the years, things have changed quite a bit.", "meaning": "세월이 흐르면서 많은 게 변했어요"},
     ]},

    # ═══════════ Week 13 — 파이널 모의고사 ═══════════
    {"day": 85, "week": 13, "phase": 3, "topic": "모의고사 1: 자기소개 + 서베이", "type": "모의고사",
     "question": "Let's start the interview now. Tell me about yourself. Then, describe your favorite place in your neighborhood and what you do there.",
     "mission": "실전처럼! 자기소개 1분 + 서베이 주제 1분, 멈추지 않고 말하기",
     "vocab": [
         {"word": "fluently", "meaning": "유창하게", "example": "I want to speak fluently."},
         {"word": "hesitate", "meaning": "머뭇거리다", "example": "Don't hesitate — keep talking."},
         {"word": "filler", "meaning": "필러 (음, 그러니까)", "example": "Use fillers like 'well' naturally."},
         {"word": "elaborate", "meaning": "자세히 말하다", "example": "Let me elaborate on that."},
         {"word": "confidence", "meaning": "자신감", "example": "Speak with confidence."},
     ],
     "expressions": [
         {"phrase": "Well, let me think about that for a second.", "meaning": "음, 잠깐 생각 좀 해볼게요"},
         {"phrase": "What I mean is ...", "meaning": "제 말은..."},
     ]},
    {"day": 86, "week": 13, "phase": 3, "topic": "모의고사 2: 과거 경험 + 비교", "type": "모의고사",
     "question": "Tell me about the most memorable trip you've ever taken. Then compare how you travel now with how you traveled in the past.",
     "mission": "실전처럼! 경험 스토리텔링 + 과거/현재 비교, 총 2분 이상 말하기",
     "vocab": [
         {"word": "storytelling", "meaning": "스토리텔링", "example": "Good storytelling has a flow."},
         {"word": "budget travel", "meaning": "저예산 여행", "example": "I did budget travel in my 20s."},
         {"word": "comfort", "meaning": "편안함", "example": "Now I prioritize comfort."},
         {"word": "spontaneous", "meaning": "즉흥적인", "example": "I used to be more spontaneous."},
         {"word": "thorough", "meaning": "꼼꼼한", "example": "Now I do thorough planning."},
     ],
     "expressions": [
         {"phrase": "It all started when ...", "meaning": "모든 건 ~할 때 시작됐어요"},
         {"phrase": "These days, I'd rather ... than ...", "meaning": "요즘엔 ~보다는 ~하는 편이에요"},
     ]},
    {"day": 87, "week": 13, "phase": 3, "topic": "모의고사 3: 롤플레이 풀세트", "type": "모의고사",
     "question": "You want to take a trip with your friend. Call a hotel and ask questions about rooms. But there's a problem — the hotel is fully booked. Suggest alternatives to your friend. Then tell me about a real problem you had while booking accommodation.",
     "mission": "실전처럼! 롤플레이 11+12+13번 유형 풀세트 완주하기",
     "vocab": [
         {"word": "fully booked", "meaning": "예약이 꽉 찬", "example": "The hotel is fully booked."},
         {"word": "vacancy", "meaning": "빈방", "example": "Do you have any vacancies?"},
         {"word": "nearby", "meaning": "근처의", "example": "Is there another hotel nearby?"},
         {"word": "option", "meaning": "선택지", "example": "We have two options."},
         {"word": "work out", "meaning": "잘 해결되다", "example": "It all worked out in the end."},
     ],
     "expressions": [
         {"phrase": "In that case, could you recommend somewhere else?", "meaning": "그렇다면 다른 곳을 추천해 주시겠어요?"},
         {"phrase": "Plan B it is, then!", "meaning": "그럼 플랜 B로 가자!"},
     ]},
    {"day": 88, "week": 13, "phase": 3, "topic": "모의고사 4: 돌발 풀세트", "type": "모의고사",
     "question": "Tell me about the internet usage in your country. How do people use the internet? What are some concerns about internet use these days?",
     "mission": "실전처럼! 돌발주제 3연속 질문에 각 1분씩 답하기",
     "vocab": [
         {"word": "usage", "meaning": "사용(량)", "example": "Internet usage is very high in Korea."},
         {"word": "concern", "meaning": "우려", "example": "Privacy is a big concern."},
         {"word": "personal information", "meaning": "개인정보", "example": "Protect your personal information."},
         {"word": "screen time", "meaning": "스크린 타임", "example": "Kids have too much screen time."},
         {"word": "digital detox", "meaning": "디지털 디톡스", "example": "I sometimes need a digital detox."},
     ],
     "expressions": [
         {"phrase": "Korea is known for its fast internet.", "meaning": "한국은 빠른 인터넷으로 유명하죠"},
         {"phrase": "There's a growing concern about ...", "meaning": "~에 대한 우려가 커지고 있어요"},
     ]},
    {"day": 89, "week": 13, "phase": 3, "topic": "모의고사 5: 종합 실전", "type": "모의고사",
     "question": "Describe your daily routine. Tell me about a day when your routine was completely different. What do you think makes a good daily routine?",
     "mission": "실전처럼! 묘사+경험+의견 종합 콤보를 3분 동안 완주하기",
     "vocab": [
         {"word": "out of the ordinary", "meaning": "평소와 다른", "example": "That day was out of the ordinary."},
         {"word": "disrupt", "meaning": "방해하다, 흐트러뜨리다", "example": "The blackout disrupted my routine."},
         {"word": "adapt", "meaning": "적응하다", "example": "I had to adapt quickly."},
         {"word": "structure", "meaning": "구조, 체계", "example": "A good routine needs structure."},
         {"word": "sustainable", "meaning": "지속 가능한", "example": "It should be sustainable."},
     ],
     "expressions": [
         {"phrase": "Everything went differently that day.", "meaning": "그날은 모든 게 평소와 달랐어요"},
         {"phrase": "In my view, consistency beats intensity.", "meaning": "제 생각엔 꾸준함이 강도를 이겨요"},
     ]},
    {"day": 90, "week": 13, "phase": 3, "topic": "졸업! 종합 점검 & 셀프 인터뷰", "type": "모의고사",
     "question": "This is your final interview. Tell me about yourself, your hobbies, a memorable experience, and your goals for the future. Show me everything you've learned!",
     "mission": "90일의 마무리! 자기소개→취미→경험→미래 계획을 4분 풀 인터뷰로 완주하기",
     "vocab": [
         {"word": "milestone", "meaning": "이정표, 중요한 단계", "example": "Today is a big milestone."},
         {"word": "progress", "meaning": "발전", "example": "I've made real progress."},
         {"word": "accomplish", "meaning": "성취하다", "example": "I accomplished my goal."},
         {"word": "journey", "meaning": "여정", "example": "It's been an amazing journey."},
         {"word": "keep it up", "meaning": "계속 유지하다", "example": "I'll keep it up from now on."},
     ],
     "expressions": [
         {"phrase": "Looking back on the past three months, ...", "meaning": "지난 3개월을 돌아보면..."},
         {"phrase": "This is just the beginning.", "meaning": "이건 시작일 뿐이에요"},
     ]},
]

TOTAL_DAYS = len(OPIC_CURRICULUM)  # 90

PHASE_INFO = {
    1: {"name": "기초 다지기", "range": "Day 1-28", "goal": "현재시제로 나/집/일상/취미를 막힘없이 묘사 (IL→IM1)"},
    2: {"name": "시제 확장", "range": "Day 29-56", "goal": "과거 경험 스토리텔링 + 비교/변화 + 돌발주제 대응 (IM1→IM3)"},
    3: {"name": "실전 완성", "range": "Day 57-90", "goal": "롤플레이 + 의견 논리 전개 + 콤보 완주 (IM3→IH)"},
}

