"""스피킹 드릴 문장 데이터베이스 — 500문장
PDF(300) + 추가(200) = 500
"""

SPEAKING_SENTENCES = [
    # ═══════════════════════════════════════════════════════
    # Part 1. 영어 스피킹 회화 만능 핵심 표현 (1~100)
    # ═══════════════════════════════════════════════════════

    # 1-1. 인사 및 대화 시작 (1~15)
    {"id": 1,  "korean": "어떻게 지내?",              "english": "How's it going?",               "category": "인사/대화시작", "difficulty": 1},
    {"id": 2,  "korean": "그동안 뭐 하고 지냈어?",     "english": "What have you been up to?",     "category": "인사/대화시작", "difficulty": 2},
    {"id": 3,  "korean": "오랜만이야.",                "english": "Long time no see.",             "category": "인사/대화시작", "difficulty": 1},
    {"id": 4,  "korean": "만나서 반가워.",              "english": "It's good to see you.",         "category": "인사/대화시작", "difficulty": 1},
    {"id": 5,  "korean": "주말 잘 보냈어?",            "english": "How was your weekend?",         "category": "인사/대화시작", "difficulty": 1},
    {"id": 6,  "korean": "무슨 생각 해?",              "english": "What's on your mind?",          "category": "인사/대화시작", "difficulty": 1},
    {"id": 7,  "korean": "오늘 저녁에 시간 돼?",       "english": "Are you free this evening?",    "category": "인사/대화시작", "difficulty": 1},
    {"id": 8,  "korean": "혹시 알고 계신가요?",        "english": "Do you happen to know?",        "category": "인사/대화시작", "difficulty": 2},
    {"id": 9,  "korean": "있잖아! (놀라운 소식 있어)", "english": "Guess what?",                   "category": "인사/대화시작", "difficulty": 1},
    {"id": 10, "korean": "혹시 ~인지 궁금해서요.",     "english": "I was wondering if...",         "category": "인사/대화시작", "difficulty": 2},
    {"id": 11, "korean": "부탁 하나만 들어줄 수 있어?","english": "Can I ask you a favor?",        "category": "인사/대화시작", "difficulty": 1},
    {"id": 12, "korean": "진짜 오랜만이다.",            "english": "It's been a while.",            "category": "인사/대화시작", "difficulty": 1},
    {"id": 13, "korean": "여기 분위기 어때? 마음에 들어?","english": "How do you like it here?",   "category": "인사/대화시작", "difficulty": 2},
    {"id": 14, "korean": "여기 어쩐 일이야?",          "english": "What brings you here?",         "category": "인사/대화시작", "difficulty": 1},
    {"id": 15, "korean": "나중에 또 봐.",              "english": "Catch you later.",              "category": "인사/대화시작", "difficulty": 1},

    # 1-2. 공감, 리액션 및 맞장구 (16~35)
    {"id": 16, "korean": "말 되네. 이해하겠어.",       "english": "That makes sense.",             "category": "공감/리액션", "difficulty": 1},
    {"id": 17, "korean": "무슨 말인지 알겠어.",        "english": "I see your point.",             "category": "공감/리액션", "difficulty": 1},
    {"id": 18, "korean": "그러니까 말이야! 정확해!",   "english": "Exactly!",                      "category": "공감/리액션", "difficulty": 1},
    {"id": 19, "korean": "전적으로 동감이야.",         "english": "I couldn't agree more.",        "category": "공감/리액션", "difficulty": 2},
    {"id": 20, "korean": "어쩐지 그렇더라.",           "english": "No wonder.",                    "category": "공감/리액션", "difficulty": 1},
    {"id": 21, "korean": "내 그럴 줄 알았어.",         "english": "That figures.",                 "category": "공감/리액션", "difficulty": 2},
    {"id": 22, "korean": "인정. 말이 되네.",           "english": "Fair enough.",                  "category": "공감/리액션", "difficulty": 1},
    {"id": 23, "korean": "잘됐다!",                    "english": "Good for you!",                 "category": "공감/리액션", "difficulty": 1},
    {"id": 24, "korean": "진심으로 잘됐다.",           "english": "I'm so happy for you.",         "category": "공감/리액션", "difficulty": 1},
    {"id": 25, "korean": "다행이다.",                  "english": "That's a relief.",              "category": "공감/리액션", "difficulty": 1},
    {"id": 26, "korean": "정말 아쉽다. 안타깝다.",     "english": "What a shame.",                 "category": "공감/리액션", "difficulty": 1},
    {"id": 27, "korean": "그거 별로다. 안됐네.",       "english": "That sucks.",                   "category": "공감/리액션", "difficulty": 1},
    {"id": 28, "korean": "속상해하지 마. 신경 쓰지 마.","english": "Don't sweat it.",              "category": "공감/리액션", "difficulty": 1},
    {"id": 29, "korean": "힘내!",                      "english": "Cheer up!",                     "category": "공감/리액션", "difficulty": 1},
    {"id": 30, "korean": "서운하게 생각하지 마.",       "english": "No hard feelings.",             "category": "공감/리액션", "difficulty": 2},
    {"id": 31, "korean": "내 말이! 그러니까 말이야.",  "english": "Tell me about it.",             "category": "공감/리액션", "difficulty": 1},
    {"id": 32, "korean": "당연하지. 그렇겠네.",        "english": "I bet.",                        "category": "공감/리액션", "difficulty": 1},
    {"id": 33, "korean": "동감이야.",                  "english": "You can say that again.",       "category": "공감/리액션", "difficulty": 2},
    {"id": 34, "korean": "어쩌겠어, 받아들여야지.",    "english": "It is what it is.",             "category": "공감/리액션", "difficulty": 2},
    {"id": 35, "korean": "마음대로 해.",               "english": "Suit yourself.",                "category": "공감/리액션", "difficulty": 1},

    # 1-3. 내 생각, 의견 표현하기 (36~55)
    {"id": 36, "korean": "내 생각에는 말이야,",         "english": "In my opinion,",               "category": "의견표현", "difficulty": 1},
    {"id": 37, "korean": "내가 알기로는 말이지,",       "english": "As far as I know,",            "category": "의견표현", "difficulty": 2},
    {"id": 38, "korean": "내가 틀렸을 수도 있지만,",    "english": "Correct me if I'm wrong,",     "category": "의견표현", "difficulty": 2},
    {"id": 39, "korean": "솔직히 말해서,",              "english": "To be honest with you,",       "category": "의견표현", "difficulty": 1},
    {"id": 40, "korean": "개인적으로 나는 ~라고 생각해.","english": "Personally, I think...",      "category": "의견표현", "difficulty": 1},
    {"id": 41, "korean": "내가 보기에는 ~인 것 같아.",  "english": "It seems to me that...",       "category": "의견표현", "difficulty": 2},
    {"id": 42, "korean": "나는 ~쪽으로 마음이 기우네.", "english": "I'm leaning towards...",       "category": "의견표현", "difficulty": 3},
    {"id": 43, "korean": "왠지 ~라는 느낌이 들어.",     "english": "I have a feeling that...",     "category": "의견표현", "difficulty": 2},
    {"id": 44, "korean": "말이 나와서 말인데,",          "english": "Speaking of which,",           "category": "의견표현", "difficulty": 2},
    {"id": 45, "korean": "생각해보니 그렇네.",           "english": "Come to think of it,",         "category": "의견표현", "difficulty": 2},
    {"id": 46, "korean": "그러니까 생각났는데.",         "english": "That reminds me.",             "category": "의견표현", "difficulty": 1},
    {"id": 47, "korean": "그건 잘 모르겠어.",            "english": "I'm not sure about that.",     "category": "의견표현", "difficulty": 1},
    {"id": 48, "korean": "상황에 따라 달라.",            "english": "It depends.",                  "category": "의견표현", "difficulty": 1},
    {"id": 49, "korean": "생각해 볼게.",                 "english": "I'll think about it.",         "category": "의견표현", "difficulty": 1},
    {"id": 50, "korean": "마음 바뀌었어.",               "english": "I changed my mind.",           "category": "의견표현", "difficulty": 1},
    {"id": 51, "korean": "너도 알다시피,",               "english": "As you know,",                 "category": "의견표현", "difficulty": 1},
    {"id": 52, "korean": "난 상관없어.",                 "english": "I don't mind.",                "category": "의견표현", "difficulty": 1},
    {"id": 53, "korean": "네가 정해.",                   "english": "It's up to you.",              "category": "의견표현", "difficulty": 1},
    {"id": 54, "korean": "선택의 여지가 없어.",          "english": "I have no choice.",            "category": "의견표현", "difficulty": 2},
    {"id": 55, "korean": "정말 기대돼.",                 "english": "I'm looking forward to it.",   "category": "의견표현", "difficulty": 1},

    # 1-4. 되묻기 및 의사소통 확인 (56~70)
    {"id": 56, "korean": "그게 무슨 뜻이야?",           "english": "What do you mean by that?",    "category": "의사소통", "difficulty": 1},
    {"id": 57, "korean": "다시 한번 말씀해 주시겠어요?","english": "Could you repeat that?",       "category": "의사소통", "difficulty": 1},
    {"id": 58, "korean": "알아들었어?",                  "english": "Did you get that?",            "category": "의사소통", "difficulty": 1},
    {"id": 59, "korean": "내 말 이해하고 있어?",         "english": "Are you with me?",             "category": "의사소통", "difficulty": 1},
    {"id": 60, "korean": "하려는 말이 뭔데?",            "english": "What are you trying to say?",  "category": "의사소통", "difficulty": 1},
    {"id": 61, "korean": "내가 제대로 이해한 건지 확인해 볼게.","english": "Let me get this straight.", "category": "의사소통", "difficulty": 2},
    {"id": 62, "korean": "결론만 말하자면,",             "english": "Long story short,",            "category": "의사소통", "difficulty": 2},
    {"id": 63, "korean": "다시 말해서,",                 "english": "In other words,",              "category": "의사소통", "difficulty": 1},
    {"id": 64, "korean": "내 말 무슨 뜻인지 알지?",      "english": "You know what I mean?",        "category": "의사소통", "difficulty": 1},
    {"id": 65, "korean": "죄송해요, 못 들었어요.",       "english": "Sorry, I didn't catch that.",  "category": "의사소통", "difficulty": 1},
    {"id": 66, "korean": "조금만 크게 말씀해 주실래요?", "english": "Could you speak up a bit?",    "category": "의사소통", "difficulty": 2},
    {"id": 67, "korean": "철자가 어떻게 되나요?",        "english": "How do you spell that?",       "category": "의사소통", "difficulty": 1},
    {"id": 68, "korean": "그 단어가 뭐였더라?",          "english": "What's the word for it?",      "category": "의사소통", "difficulty": 1},
    {"id": 69, "korean": "아니야, 신경 쓰지 마.",        "english": "Never mind.",                  "category": "의사소통", "difficulty": 1},
    {"id": 70, "korean": "내가 했던 말 취소할게.",       "english": "Forget I said that.",          "category": "의사소통", "difficulty": 2},

    # 1-5. 감정 및 상태 표현 (71~85)
    {"id": 71, "korean": "나 완전 지쳤어.",              "english": "I'm exhausted.",               "category": "감정/상태", "difficulty": 1},
    {"id": 72, "korean": "요새 정신없이 바빠.",          "english": "I'm super busy lately.",       "category": "감정/상태", "difficulty": 1},
    {"id": 73, "korean": "나 기분 좋아.",                "english": "I'm in a good mood.",          "category": "감정/상태", "difficulty": 1},
    {"id": 74, "korean": "스트레스 너무 받아.",          "english": "I'm stressed out.",            "category": "감정/상태", "difficulty": 1},
    {"id": 75, "korean": "마음이 놓여. 다행이다.",        "english": "I'm so relieved.",             "category": "감정/상태", "difficulty": 1},
    {"id": 76, "korean": "네가 정말 자랑스러워.",        "english": "I'm so proud of you.",         "category": "감정/상태", "difficulty": 1},
    {"id": 77, "korean": "기분이 너무 엉망이야.",        "english": "I feel terrible.",             "category": "감정/상태", "difficulty": 1},
    {"id": 78, "korean": "배불러.",                      "english": "I'm full.",                    "category": "감정/상태", "difficulty": 1},
    {"id": 79, "korean": "배고파 죽겠어.",               "english": "I'm starving.",                "category": "감정/상태", "difficulty": 1},
    {"id": 80, "korean": "저 ~를 찾고 있어요.",          "english": "I'm looking for...",           "category": "감정/상태", "difficulty": 1},
    {"id": 81, "korean": "지금 가는 중이야.",            "english": "I'm on my way.",               "category": "감정/상태", "difficulty": 1},
    {"id": 82, "korean": "나 좀 늦어질 것 같아.",        "english": "I'm running late.",            "category": "감정/상태", "difficulty": 1},
    {"id": 83, "korean": "어쩔 수 없잖아.",              "english": "I can't help it.",             "category": "감정/상태", "difficulty": 1},
    {"id": 84, "korean": "눈물 날 것 같아.",             "english": "I feel like crying.",          "category": "감정/상태", "difficulty": 2},
    {"id": 85, "korean": "지루해 죽겠어.",               "english": "I'm bored to death.",          "category": "감정/상태", "difficulty": 2},

    # 1-6. 일상 만능 숙어 표현 (86~100)
    {"id": 86,  "korean": "식은 죽 먹기지.",             "english": "It's a piece of cake.",        "category": "숙어표현", "difficulty": 2},
    {"id": 87,  "korean": "무리하지 마. 편하게 마음먹어.","english": "Take it easy.",               "category": "숙어표현", "difficulty": 1},
    {"id": 88,  "korean": "계속 연락하고 지내자.",       "english": "Keep in touch.",               "category": "숙어표현", "difficulty": 1},
    {"id": 89,  "korean": "오늘은 이만 하자.",           "english": "Call it a day.",               "category": "숙어표현", "difficulty": 2},
    {"id": 90,  "korean": "하루 동안 신중하게 생각해 봐.","english": "Sleep on it.",                "category": "숙어표현", "difficulty": 2},
    {"id": 91,  "korean": "행운을 빌어! (공연, 시험 전)","english": "Break a leg!",                 "category": "숙어표현", "difficulty": 2},
    {"id": 92,  "korean": "지금까지는 괜찮아.",          "english": "So far, so good.",             "category": "숙어표현", "difficulty": 1},
    {"id": 93,  "korean": "행운을 빌어줘.",              "english": "Keep your fingers crossed.",   "category": "숙어표현", "difficulty": 2},
    {"id": 94,  "korean": "나 놀리지 마. 농담하지 마.",  "english": "Don't pull my leg.",           "category": "숙어표현", "difficulty": 2},
    {"id": 95,  "korean": "깜빡 잊어버렸어.",            "english": "It slipped my mind.",          "category": "숙어표현", "difficulty": 2},
    {"id": 96,  "korean": "갑자기, 난데없이,",           "english": "Out of the blue,",             "category": "숙어표현", "difficulty": 2},
    {"id": 97,  "korean": "아주 가끔, 드물게.",          "english": "Once in a blue moon.",         "category": "숙어표현", "difficulty": 3},
    {"id": 98,  "korean": "그거 엄청 비싸.",             "english": "It costs an arm and a leg.",   "category": "숙어표현", "difficulty": 3},
    {"id": 99,  "korean": "출발하자! 길을 나서자.",      "english": "Hit the road.",                "category": "숙어표현", "difficulty": 2},
    {"id": 100, "korean": "그때 가서 상황 보고 정하자.", "english": "Play it by ear.",              "category": "숙어표현", "difficulty": 3},

    # ═══════════════════════════════════════════════════════
    # Part 2. 일상생활 상황별 문장 (101~200)
    # ═══════════════════════════════════════════════════════

    # 2-1. 집, 아침 루틴, 집안일 (101~115)
    {"id": 101, "korean": "오늘 아침에 늦잠 잤어.",      "english": "I overslept this morning.",    "category": "집/일상", "difficulty": 1},
    {"id": 102, "korean": "불 껐어?",                    "english": "Did you turn off the lights?", "category": "집/일상", "difficulty": 1},
    {"id": 103, "korean": "나 빨래해야 해.",             "english": "I need to do the laundry.",    "category": "집/일상", "difficulty": 1},
    {"id": 104, "korean": "쓰레기 좀 버려줄래?",         "english": "Can you take out the trash?",  "category": "집/일상", "difficulty": 1},
    {"id": 105, "korean": "싱크대가 막혔어.",            "english": "The sink is clogged.",         "category": "집/일상", "difficulty": 2},
    {"id": 106, "korean": "방 청소해야 해.",             "english": "I have to clean my room.",     "category": "집/일상", "difficulty": 1},
    {"id": 107, "korean": "우리 우유가 다 떨어져 가.",   "english": "We're running out of milk.",   "category": "집/일상", "difficulty": 2},
    {"id": 108, "korean": "편하게 있어.",                "english": "Make yourself at home.",       "category": "집/일상", "difficulty": 1},
    {"id": 109, "korean": "장 보러 가야 해.",            "english": "I need to go grocery shopping.","category": "집/일상", "difficulty": 1},
    {"id": 110, "korean": "7시에 나 좀 깨워줄래?",       "english": "Can you wake me up at 7?",     "category": "집/일상", "difficulty": 1},
    {"id": 111, "korean": "알람이 안 울렸어.",           "english": "The alarm didn't go off.",     "category": "집/일상", "difficulty": 2},
    {"id": 112, "korean": "열쇠 어디 뒀어?",             "english": "Where did you put the keys?",  "category": "집/일상", "difficulty": 1},
    {"id": 113, "korean": "설거지해야 해.",              "english": "I have to do the dishes.",     "category": "집/일상", "difficulty": 1},
    {"id": 114, "korean": "와이파이가 안 돼.",           "english": "The Wi-Fi is not working.",    "category": "집/일상", "difficulty": 1},
    {"id": 115, "korean": "샤워하러 갈게.",              "english": "I'm going to take a shower.",  "category": "집/일상", "difficulty": 1},

    # 2-2. 카페 및 식당에서 (116~135)
    {"id": 116, "korean": "드시고 가시나요, 포장이신가요?","english": "For here or to go?",         "category": "카페/식당", "difficulty": 1},
    {"id": 117, "korean": "아이스 아메리카노 한 잔 주세요.","english": "Can I get an iced americano, please?","category": "카페/식당", "difficulty": 1},
    {"id": 118, "korean": "리필 좀 해주실 수 있나요?",   "english": "Can I have a refill, please?", "category": "카페/식당", "difficulty": 2},
    {"id": 119, "korean": "두 명 자리 있나요?",          "english": "Do you have a table for two?", "category": "카페/식당", "difficulty": 1},
    {"id": 120, "korean": "메뉴판 좀 볼 수 있을까요?",   "english": "Can we see the menu, please?", "category": "카페/식당", "difficulty": 1},
    {"id": 121, "korean": "주문하시겠어요?",             "english": "Are you ready to order?",      "category": "카페/식당", "difficulty": 1},
    {"id": 122, "korean": "여기 뭐가 맛있어요? 추천해 주세요.","english": "What do you recommend here?","category": "카페/식당", "difficulty": 1},
    {"id": 123, "korean": "저도 같은 걸로 할게요.",      "english": "I'll have the same thing.",    "category": "카페/식당", "difficulty": 1},
    {"id": 124, "korean": "양파는 빼주세요.",            "english": "Please hold the onions.",      "category": "카페/식당", "difficulty": 2},
    {"id": 125, "korean": "드레싱은 따로 주세요.",       "english": "Can we get the dressing on the side?","category": "카페/식당", "difficulty": 2},
    {"id": 126, "korean": "이거 제가 주문한 게 아니에요.","english": "This isn't what I ordered.",  "category": "카페/식당", "difficulty": 2},
    {"id": 127, "korean": "이거 매워요?",                "english": "Is it spicy?",                 "category": "카페/식당", "difficulty": 1},
    {"id": 128, "korean": "계산서 좀 주세요.",           "english": "Check, please.",               "category": "카페/식당", "difficulty": 1},
    {"id": 129, "korean": "더치페이하자. 나눠 내자.",    "english": "Let's split the bill.",        "category": "카페/식당", "difficulty": 2},
    {"id": 130, "korean": "오늘 밤은 내가 쏠게.",        "english": "It's on me tonight.",          "category": "카페/식당", "difficulty": 2},
    {"id": 131, "korean": "잔돈은 가지세요.",            "english": "Keep the change.",             "category": "카페/식당", "difficulty": 1},
    {"id": 132, "korean": "남은 음식 좀 싸 주시겠어요?", "english": "Can I get a doggy bag?",       "category": "카페/식당", "difficulty": 2},
    {"id": 133, "korean": "신용카드 받나요?",            "english": "Do you take credit cards?",    "category": "카페/식당", "difficulty": 1},
    {"id": 134, "korean": "다 맛있었어요.",              "english": "Everything was delicious.",    "category": "카페/식당", "difficulty": 1},
    {"id": 135, "korean": "저희 오래 기다렸어요.",       "english": "We've been waiting for a long time.","category": "카페/식당", "difficulty": 2},

    # 2-3. 쇼핑 및 길 찾기 (136~155)
    {"id": 136, "korean": "그냥 둘러보는 중이에요.",     "english": "I'm just looking around.",     "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 137, "korean": "탈의실이 어디에 있나요?",     "english": "Where is the fitting room?",   "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 138, "korean": "이거 다른 사이즈도 있나요?",  "english": "Does this come in another size?","category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 139, "korean": "이것 한번 입어봐도 될까요?",  "english": "Can I try this on?",           "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 140, "korean": "조금 꽉 끼네요.",             "english": "It's a bit too tight.",        "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 141, "korean": "이거 파란색으로도 있나요?",   "english": "Do you have this in blue?",    "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 142, "korean": "이거 할인 중인가요?",         "english": "Is this on sale?",             "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 143, "korean": "이거 환불받을 수 있을까요?",  "english": "Can I get a refund for this?", "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 144, "korean": "이거 M 사이즈로 교환하고 싶어요.","english": "I'd like to exchange this for a medium.","category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 145, "korean": "지하철역 가려면 어디로 가야 하나요?","english": "Excuse me, how do I get to the subway station?","category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 146, "korean": "걸어갈 만한 거리인가요?",     "english": "Is it within walking distance?","category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 147, "korean": "금방 찾으실 거예요.",         "english": "You can't miss it.",           "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 148, "korean": "가장 가까운 화장실이 어디예요?","english": "Where is the nearest restroom?","category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 149, "korean": "다음 모퉁이에서 좌회전하세요.","english": "Turn left at the next corner.", "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 150, "korean": "거기 가려면 얼마나 걸려요?",  "english": "How long does it take to get there?","category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 151, "korean": "시내로 가는 버스는 어떤 건가요?","english": "Which bus goes to downtown?","category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 152, "korean": "저 길을 잃은 것 같아요.",     "english": "I think I'm lost.",            "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 153, "korean": "지도에서 보여주실 수 있나요?","english": "Can you show me on the map?",   "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 154, "korean": "바로 길 건너편에 있어요.",    "english": "It's right across the street.", "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 155, "korean": "근처에 편의점 있나요?",       "english": "Is there a convenience store nearby?","category": "쇼핑/길찾기", "difficulty": 1},

    # 2-4. 약속 잡기, 친구들과 만남 (156~175)
    {"id": 156, "korean": "오늘 저녁에 계획 있어?",      "english": "What are your plans for tonight?","category": "약속/만남", "difficulty": 1},
    {"id": 157, "korean": "언제 한번 놀자.",             "english": "Let's hang out sometime.",     "category": "약속/만남", "difficulty": 1},
    {"id": 158, "korean": "우리 몇 시에 만날까?",        "english": "What time should we meet?",    "category": "약속/만남", "difficulty": 1},
    {"id": 159, "korean": "어디서 만나고 싶어?",         "english": "Where do you want to meet?",   "category": "약속/만남", "difficulty": 1},
    {"id": 160, "korean": "갑자기 무슨 일이 좀 생겼어.", "english": "Something came up suddenly.",  "category": "약속/만남", "difficulty": 2},
    {"id": 161, "korean": "우리 만남 일정 좀 조정할 수 있을까?","english": "Can we reschedule our meeting?","category": "약속/만남", "difficulty": 2},
    {"id": 162, "korean": "다음 기회로 미뤄도 될까?",    "english": "Can I take a rain check?",     "category": "약속/만남", "difficulty": 3},
    {"id": 163, "korean": "나 오늘 하루 종일 시간 비어.", "english": "I'm free all day.",            "category": "약속/만남", "difficulty": 1},
    {"id": 164, "korean": "기다리게 해서 미안해.",       "english": "Sorry for keeping you waiting.","category": "약속/만남", "difficulty": 2},
    {"id": 165, "korean": "나 거의 다 왔어.",            "english": "I'm almost there.",            "category": "약속/만남", "difficulty": 1},
    {"id": 166, "korean": "오늘 뭐 하고 싶어?",          "english": "What do you want to do today?","category": "약속/만남", "difficulty": 1},
    {"id": 167, "korean": "술 한잔하러 가는 거 어때?",   "english": "How about grabbing a drink?",  "category": "약속/만남", "difficulty": 2},
    {"id": 168, "korean": "도착하면 문자 해.",           "english": "Text me when you arrive.",     "category": "약속/만남", "difficulty": 1},
    {"id": 169, "korean": "오늘 정말 즐거웠어.",         "english": "I had a great time today.",    "category": "약속/만남", "difficulty": 1},
    {"id": 170, "korean": "조심히 들어가.",              "english": "Get home safe.",               "category": "약속/만남", "difficulty": 1},
    {"id": 171, "korean": "아직 사무실이야?",            "english": "Are you still at the office?", "category": "약속/만남", "difficulty": 1},
    {"id": 172, "korean": "오후 6시까지는 갈 수 있어.",  "english": "I can make it by 6 PM.",       "category": "약속/만남", "difficulty": 2},
    {"id": 173, "korean": "늦지 마.",                    "english": "Don't be late.",               "category": "약속/만남", "difficulty": 1},
    {"id": 174, "korean": "그 사람 안 나타났어.",         "english": "He didn't show up.",           "category": "약속/만남", "difficulty": 2},
    {"id": 175, "korean": "우리 계속 연락하자.",         "english": "Let's stay in touch.",         "category": "약속/만남", "difficulty": 1},

    # 2-5. 여가 생활 및 취미, 건강 (176~200)
    {"id": 176, "korean": "쉴 때 보통 뭐 해?",           "english": "What do you do in your free time?","category": "취미/건강", "difficulty": 1},
    {"id": 177, "korean": "요새 넷플릭스 보는 거에 빠졌어.","english": "I'm into watching Netflix lately.","category": "취미/건강", "difficulty": 2},
    {"id": 178, "korean": "일주일에 세 번 헬스장 가.",    "english": "I go to the gym three times a week.","category": "취미/건강", "difficulty": 2},
    {"id": 179, "korean": "그 영화 봤어?",               "english": "Have you seen that movie?",    "category": "취미/건강", "difficulty": 1},
    {"id": 180, "korean": "난 해외여행 가는 걸 좋아해.", "english": "I love traveling abroad.",     "category": "취미/건강", "difficulty": 1},
    {"id": 181, "korean": "일본 여행 계획 중이야.",      "english": "I'm planning a trip to Japan.", "category": "취미/건강", "difficulty": 2},
    {"id": 182, "korean": "나 감기 걸린 것 같아.",       "english": "I think I caught a cold.",     "category": "취미/건강", "difficulty": 2},
    {"id": 183, "korean": "머리가 지끈지끈 아파.",       "english": "My head is throbbing.",        "category": "취미/건강", "difficulty": 3},
    {"id": 184, "korean": "목이 부었어. 따가워.",         "english": "I have a sore throat.",        "category": "취미/건강", "difficulty": 2},
    {"id": 185, "korean": "너 안색이 안 좋아 보여.",     "english": "You look pale.",               "category": "취미/건강", "difficulty": 2},
    {"id": 186, "korean": "나 휴식이 좀 필요해.",        "english": "I need to get some rest.",     "category": "취미/건강", "difficulty": 1},
    {"id": 187, "korean": "약 좀 먹어 봐.",              "english": "Take some medicine.",          "category": "취미/건강", "difficulty": 1},
    {"id": 188, "korean": "좀 괜찮아졌어?",              "english": "Are you feeling any better?",  "category": "취미/건강", "difficulty": 1},
    {"id": 189, "korean": "병원 예약이 있어.",           "english": "I have a doctor's appointment.","category": "취미/건강", "difficulty": 2},
    {"id": 190, "korean": "나 살 빼려고 노력 중이야.",   "english": "I'm trying to lose weight.",   "category": "취미/건강", "difficulty": 2},
    {"id": 191, "korean": "나 다이어트 중이야.",         "english": "I'm on a diet.",               "category": "취미/건강", "difficulty": 1},
    {"id": 192, "korean": "취미로 하는 운동 있어?",      "english": "Do you play any sports?",      "category": "취미/건강", "difficulty": 1},
    {"id": 193, "korean": "음악 듣는 거 좋아해.",        "english": "I like to listen to music.",   "category": "취미/건강", "difficulty": 1},
    {"id": 194, "korean": "나 이 밴드 엄청 팬이야.",     "english": "I'm a big fan of this band.",  "category": "취미/건강", "difficulty": 2},
    {"id": 195, "korean": "그게 스트레스 푸는 데 도움 돼.","english": "It helps me de-stress.",     "category": "취미/건강", "difficulty": 2},
    {"id": 196, "korean": "어젯밤에 완전 꿀잠 잤어.",    "english": "I slept like a log last night.","category": "취미/건강", "difficulty": 3},
    {"id": 197, "korean": "나 어젯밤에 밤새웠어.",       "english": "I stayed up all night.",       "category": "취미/건강", "difficulty": 2},
    {"id": 198, "korean": "온몸이 쑤셔.",                "english": "My body aches all over.",      "category": "취미/건강", "difficulty": 2},
    {"id": 199, "korean": "넘어지지 않게 조심해.",       "english": "Be careful not to slip.",      "category": "취미/건강", "difficulty": 2},
    {"id": 200, "korean": "여행 잘 다녀와!",             "english": "Have a safe trip!",            "category": "취미/건강", "difficulty": 1},

    # ═══════════════════════════════════════════════════════
    # Part 3. 비즈니스 업무 표현 (201~300)
    # ═══════════════════════════════════════════════════════

    # 3-1. 이메일 및 커뮤니케이션 시작 (201~215)
    {"id": 201, "korean": "안녕하세요, 잘 지내시길 바랍니다.",    "english": "I hope this email finds you well.",      "category": "비즈니스이메일", "difficulty": 2},
    {"id": 202, "korean": "~에 대해 문의드리고자 이메일을 보냅니다.","english": "I am writing to inquire about...",  "category": "비즈니스이메일", "difficulty": 3},
    {"id": 203, "korean": "빠른 답변 주셔서 감사합니다.",          "english": "Thank you for your prompt reply.",      "category": "비즈니스이메일", "difficulty": 2},
    {"id": 204, "korean": "조금 전 통화하셨던 내용과 관련하여,",   "english": "With reference to our phone call earlier,","category": "비즈니스이메일", "difficulty": 3},
    {"id": 205, "korean": "~에 대한 후속 조치를 위해 연락드렸습니다.","english": "I am reaching out to follow up on...", "category": "비즈니스이메일", "difficulty": 3},
    {"id": 206, "korean": "요청하신 서류를 첨부합니다.",           "english": "Attached is the requested document.",    "category": "비즈니스이메일", "difficulty": 2},
    {"id": 207, "korean": "첨부 파일을 검토해 주시기 바랍니다.",   "english": "Please review the attached file.",      "category": "비즈니스이메일", "difficulty": 2},
    {"id": 208, "korean": "이 사안에 대해 피드백을 주시면 감사하겠습니다.","english": "I would appreciate your feedback on this matter.","category": "비즈니스이메일", "difficulty": 3},
    {"id": 209, "korean": "질문이 있으시면 언제든 알려주세요.",    "english": "Please let me know if you have any questions.","category": "비즈니스이메일", "difficulty": 2},
    {"id": 210, "korean": "조만간 답장 받기를 기대합니다.",        "english": "I look forward to hearing from you soon.","category": "비즈니스이메일", "difficulty": 3},
    {"id": 211, "korean": "협조해 주셔서 감사합니다.",             "english": "Thank you for your cooperation.",        "category": "비즈니스이메일", "difficulty": 2},
    {"id": 212, "korean": "저희 합의에 따라,",                     "english": "As per our agreement,",                 "category": "비즈니스이메일", "difficulty": 2},
    {"id": 213, "korean": "~에 대해 짧게 리마인드 드립니다.",      "english": "Just a quick reminder that...",         "category": "비즈니스이메일", "difficulty": 2},
    {"id": 214, "korean": "한 가지 명확히 짚고 넘어가고 싶습니다.","english": "I would like to clarify one point.",    "category": "비즈니스이메일", "difficulty": 3},
    {"id": 215, "korean": "감사합니다. (이메일 맺음말)",            "english": "Best regards,",                         "category": "비즈니스이메일", "difficulty": 1},

    # 3-2. 회의 소집 및 진행 (216~235)
    {"id": 216, "korean": "다음 주 화요일로 회의 일정을 잡읍시다.", "english": "Let's schedule a meeting for next Tuesday.","category": "비즈니스회의", "difficulty": 2},
    {"id": 217, "korean": "이 시간이 모두에게 괜찮으신가요?",      "english": "Does this time work for everyone?",      "category": "비즈니스회의", "difficulty": 2},
    {"id": 218, "korean": "오늘 회의에 참석해 주신 모든 분을 환영합니다.","english": "I'd like to welcome everyone to today's meeting.","category": "비즈니스회의", "difficulty": 3},
    {"id": 219, "korean": "이제 본론으로 들어갑시다.",             "english": "Let's get down to business.",            "category": "비즈니스회의", "difficulty": 2},
    {"id": 220, "korean": "오늘 우리의 주요 목표는 ~하는 것입니다.","english": "Our main objective today is to...",     "category": "비즈니스회의", "difficulty": 3},
    {"id": 221, "korean": "안건의 첫 번째 순서는 ~입니다.",         "english": "First on the agenda is...",             "category": "비즈니스회의", "difficulty": 2},
    {"id": 222, "korean": "다음 안건으로 넘어가죠.",               "english": "Let's move on to the next item.",        "category": "비즈니스회의", "difficulty": 2},
    {"id": 223, "korean": "어느 분이 먼저 시작하시겠습니까?",      "english": "Who would like to start?",              "category": "비즈니스회의", "difficulty": 2},
    {"id": 224, "korean": "제안서를 차근차근 설명해 주시겠어요?",  "english": "Could you please walk us through the proposal?","category": "비즈니스회의", "difficulty": 3},
    {"id": 225, "korean": "의견을 하나 내고 싶습니다.",            "english": "I'd like to pitch an idea.",             "category": "비즈니스회의", "difficulty": 2},
    {"id": 226, "korean": "이에 대해 어떻게 생각하십니까?",        "english": "What are your thoughts on this?",        "category": "비즈니스회의", "difficulty": 2},
    {"id": 227, "korean": "다른 제안 사항이 더 있으신가요?",       "english": "Are there any other suggestions?",       "category": "비즈니스회의", "difficulty": 2},
    {"id": 228, "korean": "지금 논점이 벗어나고 있습니다.",        "english": "We are getting off track.",             "category": "비즈니스회의", "difficulty": 3},
    {"id": 229, "korean": "지금까지 논의된 내용을 요약하자면,",    "english": "To sum up what we've discussed so far,",  "category": "비즈니스회의", "difficulty": 3},
    {"id": 230, "korean": "회의는 여기서 마무리 짓도록 하겠습니다.","english": "Let's wrap up the meeting here.",        "category": "비즈니스회의", "difficulty": 3},
    {"id": 231, "korean": "수치들을 다시 한번 검토해 볼 수 있을까요?","english": "Can we go over the numbers again?",    "category": "비즈니스회의", "difficulty": 3},
    {"id": 232, "korean": "브레인스토밍 세션을 가질 필요가 있습니다.","english": "We need to hold a brainstorming session.","category": "비즈니스회의", "difficulty": 3},
    {"id": 233, "korean": "오늘 회의록은 누가 작성하나요?",        "english": "Who is taking the minutes today?",       "category": "비즈니스회의", "difficulty": 2},
    {"id": 234, "korean": "이 안건에 대해 표결을 해봅시다.",       "english": "Let's vote on this matter.",             "category": "비즈니스회의", "difficulty": 2},
    {"id": 235, "korean": "회의를 마치겠습니다.",                  "english": "The meeting is adjourned.",              "category": "비즈니스회의", "difficulty": 3},

    # 3-3. 업무 조율, 일정 및 마감 기한 (236~255)
    {"id": 236, "korean": "이 프로젝트 마감 기한이 언제인가요?",   "english": "When is the deadline for this project?", "category": "업무/일정", "difficulty": 2},
    {"id": 237, "korean": "마감 기한을 맞춰야 합니다.",            "english": "We need to meet the deadline.",          "category": "업무/일정", "difficulty": 2},
    {"id": 238, "korean": "시간이 촉박합니다.",                    "english": "We are running out of time.",            "category": "업무/일정", "difficulty": 2},
    {"id": 239, "korean": "마감일을 뒤로 좀 미룰 수 있을까요?",   "english": "Can we push back the deadline?",         "category": "업무/일정", "difficulty": 3},
    {"id": 240, "korean": "지금 그 업무 진행 중입니다.",           "english": "I'm currently working on it.",           "category": "업무/일정", "difficulty": 1},
    {"id": 241, "korean": "이 업무 담당자가 누구인가요?",          "english": "Who is in charge of this task?",         "category": "업무/일정", "difficulty": 2},
    {"id": 242, "korean": "저는 마케팅 캠페인을 담당하고 있습니다.","english": "I am responsible for the marketing campaign.","category": "업무/일정", "difficulty": 3},
    {"id": 243, "korean": "금요일에 다시 상황 공유해요.",          "english": "Let's touch base on Friday.",            "category": "업무/일정", "difficulty": 2},
    {"id": 244, "korean": "진행 상황을 계속 공유해 주세요.",       "english": "Please keep me updated on the progress.", "category": "업무/일정", "difficulty": 3},
    {"id": 245, "korean": "진행 상황을 계속 알려드릴게요.",        "english": "I will keep you in the loop.",           "category": "업무/일정", "difficulty": 3},
    {"id": 246, "korean": "프로세스 속도를 좀 높여야 해요.",       "english": "We need to speed up the process.",       "category": "업무/일정", "difficulty": 3},
    {"id": 247, "korean": "이 프로젝트가 최우선 과제입니다.",      "english": "This project is our top priority.",       "category": "업무/일정", "difficulty": 2},
    {"id": 248, "korean": "모든 것이 순조롭게 진행되고 있습니다.", "english": "Everything is on track.",               "category": "업무/일정", "difficulty": 2},
    {"id": 249, "korean": "일정이 계획보다 뒤처지고 있습니다.",    "english": "We are falling behind schedule.",        "category": "업무/일정", "difficulty": 3},
    {"id": 250, "korean": "이 업무를 맡아주실 수 있나요?",         "english": "Could you take on this task?",           "category": "업무/일정", "difficulty": 2},
    {"id": 251, "korean": "이 과제는 팀원들에게 위임하겠습니다.", "english": "I'll delegate this assignment to the team.","category": "업무/일정", "difficulty": 3},
    {"id": 252, "korean": "예산 승인을 먼저 받아야 합니다.",       "english": "We need to approve the budget first.",    "category": "업무/일정", "difficulty": 3},
    {"id": 253, "korean": "이 보고서에 결재가 필요합니다.",        "english": "I need your sign-off on this report.",   "category": "업무/일정", "difficulty": 3},
    {"id": 254, "korean": "대략적인 수치를 알려주실 수 있나요?",   "english": "Can you give me a ballpark figure?",     "category": "업무/일정", "difficulty": 3},
    {"id": 255, "korean": "세부 사항들을 재확인해 봅시다.",        "english": "Let's double-check the details.",        "category": "업무/일정", "difficulty": 2},

    # 3-4. 비즈니스 협상, 제안 및 동의 (256~275)
    {"id": 256, "korean": "제안을 하나 하고 싶습니다.",            "english": "We'd like to make a proposal.",          "category": "협상/제안", "difficulty": 2},
    {"id": 257, "korean": "귀사의 최저선은 무엇입니까?",           "english": "What is your bottom line?",              "category": "협상/제안", "difficulty": 3},
    {"id": 258, "korean": "대량 주문 시 할인을 제공해 드릴 수 있습니다.","english": "We can offer you a discount for bulk orders.","category": "협상/제안", "difficulty": 3},
    {"id": 259, "korean": "양사 모두 이득이 되는 해결책을 찾아야 합니다.","english": "We need to find a win-win solution.","category": "협상/제안", "difficulty": 3},
    {"id": 260, "korean": "그 조건은 저희가 수용 가능합니다.",     "english": "That is acceptable to us.",              "category": "협상/제안", "difficulty": 2},
    {"id": 261, "korean": "죄송하지만 이 조건들은 받아들이기 어렵습니다.","english": "I'm afraid we cannot accept these terms.","category": "협상/제안", "difficulty": 3},
    {"id": 262, "korean": "이 부분에 대해서는 서로 타협점을 찾읍시다.","english": "Let's compromise on this point.",     "category": "협상/제안", "difficulty": 3},
    {"id": 263, "korean": "가격 협상을 하고 싶습니다.",            "english": "We'd like to negotiate the price.",      "category": "협상/제안", "difficulty": 2},
    {"id": 264, "korean": "중간 지점에서 합의를 볼까요?",          "english": "Can we meet halfway?",                   "category": "협상/제안", "difficulty": 3},
    {"id": 265, "korean": "계약 성립입니다. 합의되었습니다.",      "english": "We have a deal.",                        "category": "협상/제안", "difficulty": 1},
    {"id": 266, "korean": "원칙적으로는 제안에 동의합니다.",       "english": "I agree with your proposal in principle.","category": "협상/제안", "difficulty": 3},
    {"id": 267, "korean": "아직 협상의 여지가 남아 있습니다.",     "english": "There is still room for negotiation.",   "category": "협상/제안", "difficulty": 3},
    {"id": 268, "korean": "내일까지 계약서에 서명해야 합니다.",    "english": "We need to sign the contract by tomorrow.","category": "협상/제안", "difficulty": 3},
    {"id": 269, "korean": "계약 조건을 검토해 봅시다.",            "english": "Let's review the terms and conditions.", "category": "협상/제안", "difficulty": 3},
    {"id": 270, "korean": "이 조항은 협상 불가능합니다.",          "english": "This is a non-negotiable term.",          "category": "협상/제안", "difficulty": 3},
    {"id": 271, "korean": "우리 회사에 돌아오는 이익은 무엇인가요?","english": "What are the benefits for our company?", "category": "협상/제안", "difficulty": 3},
    {"id": 272, "korean": "우리는 같은 비전을 공유하고 있습니다.", "english": "We share the same vision.",              "category": "협상/제안", "difficulty": 2},
    {"id": 273, "korean": "합의안을 최종 확정 지읍시다.",          "english": "Let's finalize the agreement.",          "category": "협상/제안", "difficulty": 3},
    {"id": 274, "korean": "저희는 이것을 추진할 준비가 되었습니다.","english": "We are ready to move forward with this.","category": "협상/제안", "difficulty": 3},
    {"id": 275, "korean": "저희와 거래해 주셔서 감사합니다.",      "english": "Thank you for doing business with us.",   "category": "협상/제안", "difficulty": 2},

    # 3-5. 문제 해결 및 피드백 (276~300)
    {"id": 276, "korean": "기술적인 문제가 발생했습니다.",         "english": "We have encountered a technical issue.",  "category": "문제해결", "difficulty": 2},
    {"id": 277, "korean": "이 문제를 어떻게 처리해야 할까요?",    "english": "How should we handle this problem?",     "category": "문제해결", "difficulty": 2},
    {"id": 278, "korean": "이 사안을 즉시 조사해 봐야 합니다.",   "english": "We need to look into this matter immediately.","category": "문제해결", "difficulty": 3},
    {"id": 279, "korean": "제가 지금 바로 처리하겠습니다.",        "english": "I'll take care of it right away.",        "category": "문제해결", "difficulty": 2},
    {"id": 280, "korean": "플랜 B가 필요합니다.",                  "english": "We need a backup plan.",                 "category": "문제해결", "difficulty": 2},
    {"id": 281, "korean": "이 오류의 근본 원인이 무엇인가요?",    "english": "What is the root cause of this error?",  "category": "문제해결", "difficulty": 3},
    {"id": 282, "korean": "임시 해결책을 찾아봅시다.",             "english": "Let's figure out a workaround.",         "category": "문제해결", "difficulty": 3},
    {"id": 283, "korean": "불편을 끼쳐드려 진심으로 사과드립니다.","english": "Please accept our apologies for the inconvenience.","category": "문제해결", "difficulty": 3},
    {"id": 284, "korean": "가능한 한 빨리 해결하겠습니다.",        "english": "We will resolve this as soon as possible.","category": "문제해결", "difficulty": 3},
    {"id": 285, "korean": "이런 일이 재발하지 않도록 막아야 합니다.","english": "We need to prevent this from happening again.","category": "문제해결", "difficulty": 3},
    {"id": 286, "korean": "발표 정말 훌륭했어요!",                 "english": "Great job on the presentation!",          "category": "문제해결", "difficulty": 1},
    {"id": 287, "korean": "노고에 감사드립니다.",                  "english": "I appreciate your hard work.",           "category": "문제해결", "difficulty": 2},
    {"id": 288, "korean": "발전적인 피드백을 몇 가지 드리겠습니다.","english": "Here is some constructive feedback.",    "category": "문제해결", "difficulty": 3},
    {"id": 289, "korean": "우리는 성과를 더 향상해야 합니다.",     "english": "We need to improve our performance.",    "category": "문제해결", "difficulty": 2},
    {"id": 290, "korean": "더 큰 그림을 봅시다.",                  "english": "Let's look at the big picture.",         "category": "문제해결", "difficulty": 2},
    {"id": 291, "korean": "이것은 극비 사안입니다.",               "english": "This is a highly confidential matter.",  "category": "문제해결", "difficulty": 3},
    {"id": 292, "korean": "비용을 절감해야 합니다.",               "english": "We need to cut down on costs.",          "category": "문제해결", "difficulty": 2},
    {"id": 293, "korean": "이 프로토타입을 먼저 테스트해 봅시다.", "english": "Let's test this prototype first.",        "category": "문제해결", "difficulty": 2},
    {"id": 294, "korean": "사용자 피드백을 수집해야 합니다.",      "english": "We need to gather user feedback.",        "category": "문제해결", "difficulty": 2},
    {"id": 295, "korean": "프로젝트가 대성공이었습니다.",          "english": "The project was a huge success.",         "category": "문제해결", "difficulty": 2},
    {"id": 296, "korean": "시장 트렌드를 분석해 봅시다.",          "english": "Let's analyze the market trends.",        "category": "문제해결", "difficulty": 3},
    {"id": 297, "korean": "경쟁 우위를 확보해야 합니다.",          "english": "We need to gain a competitive advantage.","category": "문제해결", "difficulty": 3},
    {"id": 298, "korean": "그것은 제 업무 범위를 벗어난 일입니다.","english": "That is beyond my scope of work.",        "category": "문제해결", "difficulty": 3},
    {"id": 299, "korean": "현황 보고서 좀 주시겠어요?",            "english": "Can you give me a status report?",        "category": "문제해결", "difficulty": 2},
    {"id": 300, "korean": "가치 있는 의견을 주셔서 감사합니다.",   "english": "Thank you for your valuable input.",      "category": "문제해결", "difficulty": 2},

    # ═══════════════════════════════════════════════════════
    # 추가 200문장 (301~500)
    # ═══════════════════════════════════════════════════════

    # 전화/연락/기술 (301~320)
    {"id": 301, "korean": "지금 통화 가능해요?",              "english": "Are you available to talk now?",       "category": "전화/연락", "difficulty": 1},
    {"id": 302, "korean": "연결이 잘 안 돼요.",               "english": "The connection is bad.",               "category": "전화/연락", "difficulty": 1},
    {"id": 303, "korean": "잠깐만요, 메모 좀 할게요.",        "english": "Hold on, let me take a note.",         "category": "전화/연락", "difficulty": 2},
    {"id": 304, "korean": "메시지 남겨드릴까요?",             "english": "Would you like to leave a message?",   "category": "전화/연락", "difficulty": 2},
    {"id": 305, "korean": "다시 전화 드려도 될까요?",         "english": "Can I call you back?",                 "category": "전화/연락", "difficulty": 1},
    {"id": 306, "korean": "지금 통화 중이에요.",              "english": "I'm on another call right now.",       "category": "전화/연락", "difficulty": 1},
    {"id": 307, "korean": "문자 남겨 주세요.",                "english": "Please send me a text.",               "category": "전화/연락", "difficulty": 1},
    {"id": 308, "korean": "핸드폰 배터리가 다 됐어.",          "english": "My phone is dead.",                    "category": "전화/연락", "difficulty": 1},
    {"id": 309, "korean": "스피커폰으로 해도 될까요?",         "english": "Can I put you on speaker?",            "category": "전화/연락", "difficulty": 2},
    {"id": 310, "korean": "이따가 다시 전화할게요.",           "english": "I'll call you back later.",            "category": "전화/연락", "difficulty": 1},
    {"id": 311, "korean": "인터넷이 너무 느려.",               "english": "The internet is so slow.",             "category": "전화/연락", "difficulty": 1},
    {"id": 312, "korean": "와이파이 비밀번호가 뭐야?",         "english": "What's the Wi-Fi password?",           "category": "전화/연락", "difficulty": 1},
    {"id": 313, "korean": "충전기 좀 빌려줄 수 있어?",         "english": "Can I borrow your charger?",           "category": "전화/연락", "difficulty": 1},
    {"id": 314, "korean": "화상 통화 해도 돼?",               "english": "Can we do a video call?",              "category": "전화/연락", "difficulty": 1},
    {"id": 315, "korean": "음소거 좀 해줘.",                   "english": "Please mute yourself.",                "category": "전화/연락", "difficulty": 1},
    {"id": 316, "korean": "화면 공유 해줄 수 있어요?",         "english": "Can you share your screen?",           "category": "전화/연락", "difficulty": 2},
    {"id": 317, "korean": "카메라가 작동이 안 돼요.",          "english": "My camera isn't working.",             "category": "전화/연락", "difficulty": 1},
    {"id": 318, "korean": "소리가 잘 안 들려요.",              "english": "I can't hear you well.",               "category": "전화/연락", "difficulty": 1},
    {"id": 319, "korean": "링크 좀 보내줄 수 있어?",           "english": "Can you send me the link?",            "category": "전화/연락", "difficulty": 1},
    {"id": 320, "korean": "파일을 공유해 줄 수 있어요?",       "english": "Can you share the file with me?",      "category": "전화/연락", "difficulty": 1},

    # 날씨/환경 (321~340)
    {"id": 321, "korean": "오늘 날씨 정말 좋다.",              "english": "The weather is really nice today.",    "category": "날씨/환경", "difficulty": 1},
    {"id": 322, "korean": "비가 올 것 같아.",                  "english": "It looks like it's going to rain.",    "category": "날씨/환경", "difficulty": 2},
    {"id": 323, "korean": "우산 챙겼어?",                      "english": "Did you bring an umbrella?",           "category": "날씨/환경", "difficulty": 1},
    {"id": 324, "korean": "오늘 엄청 춥네.",                   "english": "It's really cold today.",              "category": "날씨/환경", "difficulty": 1},
    {"id": 325, "korean": "점점 더워지고 있어.",               "english": "It's getting hotter.",                 "category": "날씨/환경", "difficulty": 1},
    {"id": 326, "korean": "바람이 너무 세게 불어.",            "english": "The wind is blowing really hard.",     "category": "날씨/환경", "difficulty": 2},
    {"id": 327, "korean": "눈이 오고 있어!",                   "english": "It's snowing!",                        "category": "날씨/환경", "difficulty": 1},
    {"id": 328, "korean": "태풍이 온다고 해.",                 "english": "They say a typhoon is coming.",        "category": "날씨/환경", "difficulty": 2},
    {"id": 329, "korean": "자외선 차단제 바르는 거 잊지 마.",  "english": "Don't forget to put on sunscreen.",    "category": "날씨/환경", "difficulty": 2},
    {"id": 330, "korean": "날씨가 많이 흐려.",                 "english": "The sky is very cloudy.",              "category": "날씨/환경", "difficulty": 1},
    {"id": 331, "korean": "안개가 꼈어.",                      "english": "It's foggy.",                          "category": "날씨/환경", "difficulty": 1},
    {"id": 332, "korean": "요즘 환경오염이 심각해.",           "english": "Environmental pollution is serious these days.","category": "날씨/환경", "difficulty": 2},
    {"id": 333, "korean": "재활용 꼭 해야 해.",                "english": "We need to make sure to recycle.",     "category": "날씨/환경", "difficulty": 2},
    {"id": 334, "korean": "오늘 미세먼지 수치가 어때?",        "english": "What's the fine dust level today?",    "category": "날씨/환경", "difficulty": 2},
    {"id": 335, "korean": "기후 변화가 점점 심해지고 있어.",   "english": "Climate change is getting worse.",     "category": "날씨/환경", "difficulty": 2},
    {"id": 336, "korean": "이번 겨울은 유독 춥네.",            "english": "This winter is particularly cold.",    "category": "날씨/환경", "difficulty": 2},
    {"id": 337, "korean": "일기예보가 맞지 않았어.",           "english": "The weather forecast was wrong.",      "category": "날씨/환경", "difficulty": 2},
    {"id": 338, "korean": "천둥 번개가 쳐.",                   "english": "There's thunder and lightning.",       "category": "날씨/환경", "difficulty": 2},
    {"id": 339, "korean": "겨울이 빨리 지나갔으면 좋겠어.",   "english": "I wish winter would pass quickly.",    "category": "날씨/환경", "difficulty": 2},
    {"id": 340, "korean": "날씨가 갑자기 확 바뀌었어.",        "english": "The weather changed all of a sudden.",  "category": "날씨/환경", "difficulty": 2},

    # 여행/공항 (341~360)
    {"id": 341, "korean": "짐을 부치고 싶어요.",               "english": "I'd like to check in my luggage.",     "category": "여행/공항", "difficulty": 2},
    {"id": 342, "korean": "탑승구가 어디예요?",                "english": "Where is the boarding gate?",          "category": "여행/공항", "difficulty": 1},
    {"id": 343, "korean": "여권 좀 보여주세요.",               "english": "May I see your passport, please?",     "category": "여행/공항", "difficulty": 1},
    {"id": 344, "korean": "입국 목적이 무엇인가요?",           "english": "What is the purpose of your visit?",   "category": "여행/공항", "difficulty": 2},
    {"id": 345, "korean": "관광 왔습니다.",                    "english": "I'm here for tourism.",                "category": "여행/공항", "difficulty": 1},
    {"id": 346, "korean": "신고할 물건이 없어요.",             "english": "I have nothing to declare.",           "category": "여행/공항", "difficulty": 2},
    {"id": 347, "korean": "비행기가 연착됐어요.",              "english": "The flight is delayed.",               "category": "여행/공항", "difficulty": 1},
    {"id": 348, "korean": "짐이 아직 안 나왔어요.",            "english": "My luggage hasn't come out yet.",      "category": "여행/공항", "difficulty": 2},
    {"id": 349, "korean": "환전하려고 해요.",                  "english": "I'd like to exchange some money.",     "category": "여행/공항", "difficulty": 2},
    {"id": 350, "korean": "호텔까지 어떻게 가요?",             "english": "How do I get to the hotel?",           "category": "여행/공항", "difficulty": 1},
    {"id": 351, "korean": "체크인은 몇 시예요?",               "english": "What time is check-in?",               "category": "여행/공항", "difficulty": 1},
    {"id": 352, "korean": "늦게 체크아웃해도 될까요?",         "english": "Is a late checkout possible?",         "category": "여행/공항", "difficulty": 2},
    {"id": 353, "korean": "이 근처에 볼 만한 곳이 있나요?",    "english": "Are there any good places to visit nearby?","category": "여행/공항", "difficulty": 2},
    {"id": 354, "korean": "짐을 잠깐 맡아주실 수 있나요?",     "english": "Can you hold my luggage for a bit?",   "category": "여행/공항", "difficulty": 2},
    {"id": 355, "korean": "셔틀버스가 몇 시에 출발해요?",      "english": "What time does the shuttle bus leave?", "category": "여행/공항", "difficulty": 2},
    {"id": 356, "korean": "가이드 투어 신청하고 싶어요.",      "english": "I'd like to book a guided tour.",       "category": "여행/공항", "difficulty": 2},
    {"id": 357, "korean": "여행이 정말 즐거웠어요.",           "english": "The trip was really enjoyable.",       "category": "여행/공항", "difficulty": 1},
    {"id": 358, "korean": "탑승권 좀 보여주시겠어요?",         "english": "Could you show me your boarding pass?", "category": "여행/공항", "difficulty": 2},
    {"id": 359, "korean": "1박 더 묵을 수 있을까요?",          "english": "Is it possible to stay one more night?","category": "여행/공항", "difficulty": 2},
    {"id": 360, "korean": "객실이 아직 준비가 안 됐어요.",      "english": "The room isn't ready yet.",            "category": "여행/공항", "difficulty": 2},

    # 직장생활 (361~380)
    {"id": 361, "korean": "오늘 재택근무예요.",                "english": "I'm working from home today.",         "category": "직장생활", "difficulty": 1},
    {"id": 362, "korean": "회의실 예약해 줄 수 있어요?",       "english": "Can you book the conference room for me?","category": "직장생활", "difficulty": 2},
    {"id": 363, "korean": "보고서 마감이 언제예요?",           "english": "When is the report due?",              "category": "직장생활", "difficulty": 1},
    {"id": 364, "korean": "점심 같이 먹을래요?",               "english": "Would you like to have lunch together?","category": "직장생활", "difficulty": 1},
    {"id": 365, "korean": "야근해야 할 것 같아요.",            "english": "I think I'll have to work overtime.",   "category": "직장생활", "difficulty": 2},
    {"id": 366, "korean": "연차 좀 쓰려고 해요.",              "english": "I'd like to take some time off.",       "category": "직장생활", "difficulty": 2},
    {"id": 367, "korean": "팀 회식이 있어요.",                 "english": "There's a team dinner.",               "category": "직장생활", "difficulty": 1},
    {"id": 368, "korean": "프레젠테이션 준비 잘 됐나요?",      "english": "Are you ready for the presentation?",  "category": "직장생활", "difficulty": 2},
    {"id": 369, "korean": "클라이언트가 수정을 요청했어요.",   "english": "The client requested revisions.",      "category": "직장생활", "difficulty": 2},
    {"id": 370, "korean": "예산이 부족해요.",                  "english": "The budget is insufficient.",          "category": "직장생활", "difficulty": 2},
    {"id": 371, "korean": "팀장님께 보고해야 해요.",           "english": "I need to report to the team leader.",  "category": "직장생활", "difficulty": 2},
    {"id": 372, "korean": "성과 평가가 다음 달이에요.",        "english": "The performance review is next month.", "category": "직장생활", "difficulty": 2},
    {"id": 373, "korean": "출장 경비를 정산해야 해요.",        "english": "I need to settle the business trip expenses.","category": "직장생활", "difficulty": 3},
    {"id": 374, "korean": "업무 인수인계 해야 해요.",          "english": "I need to hand over my work.",          "category": "직장생활", "difficulty": 2},
    {"id": 375, "korean": "신입사원 교육이 있어요.",           "english": "There's a new employee training.",      "category": "직장생활", "difficulty": 2},
    {"id": 376, "korean": "이 메일 참조로 추가해 주세요.",     "english": "Please add me in CC on this email.",    "category": "직장생활", "difficulty": 2},
    {"id": 377, "korean": "이 부분 다시 확인해 주실 수 있어요?","english": "Can you double-check this part?",      "category": "직장생활", "difficulty": 2},
    {"id": 378, "korean": "제 의견을 말씀드려도 될까요?",      "english": "May I share my opinion?",              "category": "직장생활", "difficulty": 2},
    {"id": 379, "korean": "회의 시작 전에 자료 배포해 주세요.","english": "Please distribute the materials before the meeting.","category": "직장생활", "difficulty": 3},
    {"id": 380, "korean": "이 건은 팀장님 결정 사항이에요.",   "english": "This is up to the team leader to decide.","category": "직장생활", "difficulty": 3},

    # 쇼핑 추가 (381~400)
    {"id": 381, "korean": "더 저렴한 거 있어요?",              "english": "Do you have anything cheaper?",        "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 382, "korean": "이거 품절인가요?",                  "english": "Is this out of stock?",                "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 383, "korean": "언제 재입고돼요?",                  "english": "When will it be back in stock?",       "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 384, "korean": "선물 포장 해주실 수 있나요?",        "english": "Can you gift-wrap this?",              "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 385, "korean": "영수증 주세요.",                    "english": "Can I have a receipt, please?",        "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 386, "korean": "온라인으로 주문했어요.",             "english": "I ordered it online.",                 "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 387, "korean": "배송이 언제 돼요?",                  "english": "When will it be delivered?",           "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 388, "korean": "반품하러 왔어요.",                   "english": "I'm here to return this.",             "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 389, "korean": "하자가 있어요.",                     "english": "There's a defect.",                    "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 390, "korean": "세일은 언제 끝나요?",               "english": "When does the sale end?",              "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 391, "korean": "두 개 사면 할인되나요?",             "english": "Is there a discount if I buy two?",    "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 392, "korean": "현금으로 계산할게요.",               "english": "I'll pay in cash.",                    "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 393, "korean": "이게 마지막 재고예요?",              "english": "Is this the last one in stock?",       "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 394, "korean": "다른 색상도 있나요?",               "english": "Do you have this in other colors?",    "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 395, "korean": "멤버십 카드 있으세요?",              "english": "Do you have a membership card?",       "category": "쇼핑/길찾기", "difficulty": 1},
    {"id": 396, "korean": "포인트 적립해 주세요.",              "english": "Please add the points to my account.", "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 397, "korean": "이거 인터넷에서 더 싸게 팔던데요.",  "english": "I saw this cheaper online.",           "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 398, "korean": "묶음 할인 있나요?",                  "english": "Is there a bundle discount?",          "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 399, "korean": "이거 정품 맞죠?",                    "english": "This is the real thing, right?",       "category": "쇼핑/길찾기", "difficulty": 2},
    {"id": 400, "korean": "영수증은 이메일로 받고 싶어요.",     "english": "I'd like to receive the receipt by email.","category": "쇼핑/길찾기", "difficulty": 2},

    # 관계/감정 (401~420)
    {"id": 401, "korean": "넌 내 가장 친한 친구야.",            "english": "You're my best friend.",               "category": "관계/감정", "difficulty": 1},
    {"id": 402, "korean": "솔직하게 말해줘서 고마워.",          "english": "Thank you for being honest with me.",  "category": "관계/감정", "difficulty": 2},
    {"id": 403, "korean": "그 사람이 나한테 화가 난 것 같아.",  "english": "I think they're upset with me.",       "category": "관계/감정", "difficulty": 2},
    {"id": 404, "korean": "그냥 풀고 넘어가자.",                "english": "Let's just let it go.",                "category": "관계/감정", "difficulty": 2},
    {"id": 405, "korean": "오해가 생긴 것 같아.",               "english": "I think there's been a misunderstanding.","category": "관계/감정", "difficulty": 2},
    {"id": 406, "korean": "내 말이 상처가 됐다면 미안해.",      "english": "I'm sorry if my words hurt you.",      "category": "관계/감정", "difficulty": 2},
    {"id": 407, "korean": "네 입장을 이해해.",                  "english": "I understand where you're coming from.","category": "관계/감정", "difficulty": 2},
    {"id": 408, "korean": "너한테 하고 싶은 말이 있어.",        "english": "There's something I want to say to you.","category": "관계/감정", "difficulty": 2},
    {"id": 409, "korean": "너 요새 괜찮아?",                    "english": "Are you doing okay lately?",           "category": "관계/감정", "difficulty": 1},
    {"id": 410, "korean": "힘든 일 있으면 말해.",               "english": "If you're going through something, tell me.","category": "관계/감정", "difficulty": 2},
    {"id": 411, "korean": "네 편이야.",                         "english": "I'm on your side.",                    "category": "관계/감정", "difficulty": 1},
    {"id": 412, "korean": "넌 혼자가 아니야.",                  "english": "You're not alone.",                    "category": "관계/감정", "difficulty": 1},
    {"id": 413, "korean": "그냥 들어줘서 고마워.",              "english": "Thanks for just listening.",           "category": "관계/감정", "difficulty": 2},
    {"id": 414, "korean": "항상 응원하고 있어.",                "english": "I'm always cheering you on.",          "category": "관계/감정", "difficulty": 2},
    {"id": 415, "korean": "너를 믿어.",                         "english": "I trust you.",                         "category": "관계/감정", "difficulty": 1},
    {"id": 416, "korean": "우리 솔직하게 얘기해 볼까?",          "english": "Can we talk honestly?",                "category": "관계/감정", "difficulty": 2},
    {"id": 417, "korean": "기대에 부응하지 못해서 미안해.",      "english": "I'm sorry I let you down.",            "category": "관계/감정", "difficulty": 2},
    {"id": 418, "korean": "예전엔 우리 정말 친했는데.",          "english": "We used to be really close.",          "category": "관계/감정", "difficulty": 2},
    {"id": 419, "korean": "우리 사이가 좀 서먹해졌어.",          "english": "Things have gotten a bit awkward between us.","category": "관계/감정", "difficulty": 3},
    {"id": 420, "korean": "오래된 친구가 제일이야.",             "english": "Old friends are the best.",            "category": "관계/감정", "difficulty": 2},

    # 학교/공부 (421~440)
    {"id": 421, "korean": "시험공부 해야 해.",                  "english": "I need to study for the exam.",        "category": "학교/공부", "difficulty": 1},
    {"id": 422, "korean": "이번 시험 어려웠어?",                "english": "Was the exam difficult this time?",    "category": "학교/공부", "difficulty": 1},
    {"id": 423, "korean": "성적이 많이 올랐어.",                "english": "My grades improved a lot.",            "category": "학교/공부", "difficulty": 2},
    {"id": 424, "korean": "과제 제출 기한이 언제야?",           "english": "When is the assignment due?",          "category": "학교/공부", "difficulty": 1},
    {"id": 425, "korean": "오늘 수업 빠졌어.",                  "english": "I skipped class today.",               "category": "학교/공부", "difficulty": 1},
    {"id": 426, "korean": "교수님한테 질문하러 가야 해.",        "english": "I need to go ask the professor a question.","category": "학교/공부", "difficulty": 2},
    {"id": 427, "korean": "도서관에서 공부할래?",               "english": "Do you want to study at the library?", "category": "학교/공부", "difficulty": 1},
    {"id": 428, "korean": "이번 학기 과목이 너무 많아.",         "english": "I have too many courses this semester.","category": "학교/공부", "difficulty": 2},
    {"id": 429, "korean": "졸업 논문 써야 해.",                 "english": "I need to write my thesis.",           "category": "학교/공부", "difficulty": 2},
    {"id": 430, "korean": "학점이 생각보다 잘 나왔어.",         "english": "I got better grades than I expected.",  "category": "학교/공부", "difficulty": 2},
    {"id": 431, "korean": "교환학생 지원하려고 해.",             "english": "I'm thinking of applying for an exchange program.","category": "학교/공부", "difficulty": 2},
    {"id": 432, "korean": "강의가 너무 빨리 진행돼.",           "english": "The lecture moves too fast.",           "category": "학교/공부", "difficulty": 2},
    {"id": 433, "korean": "노트 필기 빌려줄 수 있어?",          "english": "Can I borrow your notes?",             "category": "학교/공부", "difficulty": 1},
    {"id": 434, "korean": "다음 주에 발표가 있어.",             "english": "I have a presentation next week.",      "category": "학교/공부", "difficulty": 1},
    {"id": 435, "korean": "팀 프로젝트 역할 나눴어?",           "english": "Have you divided the roles for the team project?","category": "학교/공부", "difficulty": 2},
    {"id": 436, "korean": "인턴십 지원했어?",                   "english": "Did you apply for an internship?",     "category": "학교/공부", "difficulty": 1},
    {"id": 437, "korean": "영어 실력을 늘리고 싶어.",           "english": "I want to improve my English skills.",  "category": "학교/공부", "difficulty": 1},
    {"id": 438, "korean": "이 개념이 이해가 안 가.",             "english": "I don't understand this concept.",     "category": "학교/공부", "difficulty": 1},
    {"id": 439, "korean": "다시 한번 설명해 주실 수 있어요?",   "english": "Can you explain that one more time?",   "category": "학교/공부", "difficulty": 1},
    {"id": 440, "korean": "동아리 가입했어?",                   "english": "Did you join a club?",                 "category": "학교/공부", "difficulty": 1},

    # 음식/요리 (441~460)
    {"id": 441, "korean": "뭐 먹고 싶어?",                      "english": "What do you want to eat?",             "category": "음식/요리", "difficulty": 1},
    {"id": 442, "korean": "오늘 내가 요리해줄게.",              "english": "I'll cook for you today.",             "category": "음식/요리", "difficulty": 1},
    {"id": 443, "korean": "냉장고에 뭐 있어?",                  "english": "What's in the fridge?",                "category": "음식/요리", "difficulty": 1},
    {"id": 444, "korean": "이거 어떻게 만들어?",                "english": "How do you make this?",                "category": "음식/요리", "difficulty": 1},
    {"id": 445, "korean": "레시피 좀 알려줘.",                  "english": "Tell me the recipe.",                  "category": "음식/요리", "difficulty": 1},
    {"id": 446, "korean": "너무 짜다.",                          "english": "It's too salty.",                      "category": "음식/요리", "difficulty": 1},
    {"id": 447, "korean": "단 게 당긴다.",                       "english": "I'm craving something sweet.",         "category": "음식/요리", "difficulty": 2},
    {"id": 448, "korean": "배달시킬까?",                         "english": "Should we order delivery?",            "category": "음식/요리", "difficulty": 1},
    {"id": 449, "korean": "소화가 안 돼.",                       "english": "I have indigestion.",                  "category": "음식/요리", "difficulty": 2},
    {"id": 450, "korean": "이 음식 알레르기가 있어요.",          "english": "I'm allergic to this food.",           "category": "음식/요리", "difficulty": 2},
    {"id": 451, "korean": "밀가루 안 들어간 거 있어요?",        "english": "Is there anything without wheat flour?","category": "음식/요리", "difficulty": 2},
    {"id": 452, "korean": "비건 메뉴 있나요?",                  "english": "Do you have vegan options?",           "category": "음식/요리", "difficulty": 2},
    {"id": 453, "korean": "덜 맵게 해주실 수 있어요?",           "english": "Can you make it less spicy?",          "category": "음식/요리", "difficulty": 2},
    {"id": 454, "korean": "요리하는 게 스트레스 해소돼.",        "english": "Cooking helps me de-stress.",           "category": "음식/요리", "difficulty": 2},
    {"id": 455, "korean": "배달비가 너무 비싸.",                 "english": "The delivery fee is too expensive.",   "category": "음식/요리", "difficulty": 2},
    {"id": 456, "korean": "유통기한 확인했어?",                  "english": "Did you check the expiration date?",   "category": "음식/요리", "difficulty": 2},
    {"id": 457, "korean": "이 음식점 단골이야.",                 "english": "This is my go-to restaurant.",         "category": "음식/요리", "difficulty": 2},
    {"id": 458, "korean": "음식이 식기 전에 먹자.",              "english": "Let's eat before the food gets cold.", "category": "음식/요리", "difficulty": 2},
    {"id": 459, "korean": "이 집 음식 정말 맛있어.",             "english": "The food here is really good.",        "category": "음식/요리", "difficulty": 1},
    {"id": 460, "korean": "오늘 특식이야!",                      "english": "It's a special meal today!",           "category": "음식/요리", "difficulty": 1},

    # 교통 (461~480)
    {"id": 461, "korean": "버스가 왜 이렇게 안 와?",             "english": "Why isn't the bus coming?",            "category": "교통", "difficulty": 1},
    {"id": 462, "korean": "지하철로 몇 정거장이야?",             "english": "How many stops is it by subway?",      "category": "교통", "difficulty": 1},
    {"id": 463, "korean": "환승해야 해?",                        "english": "Do I need to transfer?",               "category": "교통", "difficulty": 1},
    {"id": 464, "korean": "교통 체증이 심하다.",                 "english": "There's heavy traffic.",               "category": "교통", "difficulty": 1},
    {"id": 465, "korean": "택시 잡기가 힘들어.",                 "english": "It's hard to get a taxi.",             "category": "교통", "difficulty": 1},
    {"id": 466, "korean": "막차가 몇 시야?",                     "english": "What time is the last train?",         "category": "교통", "difficulty": 1},
    {"id": 467, "korean": "이 버스 맞아?",                       "english": "Is this the right bus?",               "category": "교통", "difficulty": 1},
    {"id": 468, "korean": "교통카드 잔액이 부족해.",             "english": "My transit card balance is insufficient.","category": "교통", "difficulty": 2},
    {"id": 469, "korean": "한 정거장 지나쳤어.",                 "english": "I missed my stop by one.",             "category": "교통", "difficulty": 2},
    {"id": 470, "korean": "주차하기가 너무 힘들어.",             "english": "It's really hard to park.",            "category": "교통", "difficulty": 1},
    {"id": 471, "korean": "주차 요금이 너무 비싸.",              "english": "The parking fee is too expensive.",    "category": "교통", "difficulty": 2},
    {"id": 472, "korean": "내비게이션이 잘못된 길로 안내해.",    "english": "The navigation is giving me wrong directions.","category": "교통", "difficulty": 2},
    {"id": 473, "korean": "이 근처에 주차장 있어?",              "english": "Is there a parking lot nearby?",       "category": "교통", "difficulty": 1},
    {"id": 474, "korean": "기름이 다 떨어져 가.",                "english": "I'm almost out of gas.",               "category": "교통", "difficulty": 2},
    {"id": 475, "korean": "타이어가 펑크났어.",                  "english": "I have a flat tire.",                  "category": "교통", "difficulty": 2},
    {"id": 476, "korean": "몇 번 출구로 나가야 해?",             "english": "Which exit should I take?",            "category": "교통", "difficulty": 1},
    {"id": 477, "korean": "여기서 걸어서 얼마나 걸려?",          "english": "How long does it take to walk from here?","category": "교통", "difficulty": 2},
    {"id": 478, "korean": "자전거 타고 출퇴근해.",               "english": "I commute by bike.",                   "category": "교통", "difficulty": 2},
    {"id": 479, "korean": "고속버스 표 사야 해.",                "english": "I need to buy an express bus ticket.",  "category": "교통", "difficulty": 2},
    {"id": 480, "korean": "이 길로 가면 더 빨라?",               "english": "Is it faster to go this way?",         "category": "교통", "difficulty": 1},

    # 기타/실용 (481~500)
    {"id": 481, "korean": "고마워, 네 덕분이야.",                "english": "Thanks, it's all because of you.",     "category": "기타/실용", "difficulty": 1},
    {"id": 482, "korean": "별거 아니야. 큰일 아니야.",           "english": "It's no big deal.",                    "category": "기타/실용", "difficulty": 1},
    {"id": 483, "korean": "그냥 해본 말이야.",                   "english": "I was just saying.",                   "category": "기타/실용", "difficulty": 2},
    {"id": 484, "korean": "급하게 굴지 마.",                     "english": "Don't rush.",                          "category": "기타/실용", "difficulty": 1},
    {"id": 485, "korean": "잠깐만 기다려줘.",                    "english": "Wait just a moment.",                  "category": "기타/실용", "difficulty": 1},
    {"id": 486, "korean": "도와줘서 정말 고마워.",               "english": "Thank you so much for your help.",     "category": "기타/실용", "difficulty": 1},
    {"id": 487, "korean": "걱정 마, 다 잘 될 거야.",             "english": "Don't worry, everything will be fine.", "category": "기타/실용", "difficulty": 1},
    {"id": 488, "korean": "한번 해보자.",                        "english": "Let's give it a try.",                 "category": "기타/실용", "difficulty": 1},
    {"id": 489, "korean": "포기하지 마.",                        "english": "Don't give up.",                       "category": "기타/실용", "difficulty": 1},
    {"id": 490, "korean": "최선을 다했어.",                      "english": "I did my best.",                       "category": "기타/실용", "difficulty": 1},
    {"id": 491, "korean": "실수해도 괜찮아.",                    "english": "It's okay to make mistakes.",          "category": "기타/실용", "difficulty": 1},
    {"id": 492, "korean": "시간이 해결해 줄 거야.",              "english": "Time will take care of it.",           "category": "기타/실용", "difficulty": 2},
    {"id": 493, "korean": "긍정적으로 생각해.",                  "english": "Think positively.",                    "category": "기타/실용", "difficulty": 1},
    {"id": 494, "korean": "아직 늦지 않았어.",                   "english": "It's not too late yet.",               "category": "기타/실용", "difficulty": 1},
    {"id": 495, "korean": "내일 또 해보자.",                     "english": "Let's try again tomorrow.",            "category": "기타/실용", "difficulty": 1},
    {"id": 496, "korean": "오늘도 수고했어.",                    "english": "Good job today as well.",              "category": "기타/실용", "difficulty": 1},
    {"id": 497, "korean": "네 영어 실력이 많이 늘었어!",         "english": "Your English has improved a lot!",     "category": "기타/실용", "difficulty": 1},
    {"id": 498, "korean": "이렇게 열심히 하다니 대단하다.",       "english": "It's amazing how hard you work.",      "category": "기타/실용", "difficulty": 2},
    {"id": 499, "korean": "처음보다 훨씬 자신감이 생겼어.",      "english": "You've gained so much more confidence than before.","category": "기타/실용", "difficulty": 2},
    {"id": 500, "korean": "계속 연습하면 반드시 잘 할 수 있어.", "english": "If you keep practicing, you'll definitely get better.","category": "기타/실용", "difficulty": 2},
]

# ── 카테고리 메타데이터 ─────────────────────────────────────────
SPEAKING_CATEGORIES = [
    {"id": "전체",        "title": "전체 500문장",     "emoji": "📚", "difficulty": "난이도 1-3"},
    {"id": "인사/대화시작","title": "인사/대화 시작",   "emoji": "👋", "difficulty": "입문"},
    {"id": "공감/리액션", "title": "공감 & 리액션",    "emoji": "😊", "difficulty": "입문"},
    {"id": "의견표현",    "title": "의견 표현",         "emoji": "💬", "difficulty": "초급"},
    {"id": "의사소통",    "title": "의사소통 확인",     "emoji": "🗣️", "difficulty": "초급"},
    {"id": "감정/상태",   "title": "감정 & 상태",       "emoji": "❤️", "difficulty": "입문"},
    {"id": "숙어표현",    "title": "만능 숙어",         "emoji": "✨", "difficulty": "중급"},
    {"id": "집/일상",     "title": "집 & 일상생활",     "emoji": "🏠", "difficulty": "입문"},
    {"id": "카페/식당",   "title": "카페 & 식당",       "emoji": "☕", "difficulty": "입문"},
    {"id": "쇼핑/길찾기", "title": "쇼핑 & 길찾기",    "emoji": "🛍️", "difficulty": "초급"},
    {"id": "약속/만남",   "title": "약속 & 만남",       "emoji": "📅", "difficulty": "입문"},
    {"id": "취미/건강",   "title": "취미 & 건강",       "emoji": "💪", "difficulty": "초급"},
    {"id": "전화/연락",   "title": "전화 & 연락",       "emoji": "📱", "difficulty": "초급"},
    {"id": "날씨/환경",   "title": "날씨 & 환경",       "emoji": "🌤️", "difficulty": "초급"},
    {"id": "여행/공항",   "title": "여행 & 공항",       "emoji": "✈️", "difficulty": "초급"},
    {"id": "직장생활",    "title": "직장생활",          "emoji": "💼", "difficulty": "중급"},
    {"id": "관계/감정",   "title": "관계 & 감정",       "emoji": "🤝", "difficulty": "초급"},
    {"id": "학교/공부",   "title": "학교 & 공부",       "emoji": "📖", "difficulty": "초급"},
    {"id": "음식/요리",   "title": "음식 & 요리",       "emoji": "🍳", "difficulty": "초급"},
    {"id": "교통",        "title": "교통",              "emoji": "🚇", "difficulty": "초급"},
    {"id": "비즈니스이메일","title": "비즈니스 이메일", "emoji": "📧", "difficulty": "고급"},
    {"id": "비즈니스회의","title": "비즈니스 회의",     "emoji": "👔", "difficulty": "고급"},
    {"id": "업무/일정",   "title": "업무 & 일정",       "emoji": "📋", "difficulty": "고급"},
    {"id": "협상/제안",   "title": "협상 & 제안",       "emoji": "🤝", "difficulty": "고급"},
    {"id": "문제해결",    "title": "문제해결 & 피드백", "emoji": "🔧", "difficulty": "고급"},
    {"id": "기타/실용",   "title": "기타 실용 표현",    "emoji": "💡", "difficulty": "입문"},
]
